/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables.records;


import dev.agenvas.db.tables.AgentRun;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Persistent execution lifecycle with immutable input and policy snapshots.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AgentRunRecord extends UpdatableRecordImpl<AgentRunRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.agent_run.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.agent_run.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.agent_run.project_id</code>.
     */
    public void setProjectId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.agent_run.project_id</code>.
     */
    public UUID getProjectId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.agent_run.agent_instance_id</code>.
     */
    public void setAgentInstanceId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.agent_run.agent_instance_id</code>.
     */
    public UUID getAgentInstanceId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.agent_run.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.agent_run.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>public.agent_run.status</code>.
     */
    public void setStatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.agent_run.status</code>.
     */
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.agent_run.instruction</code>.
     */
    public void setInstruction(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.agent_run.instruction</code>.
     */
    public String getInstruction() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.agent_run.context_snapshot_json</code>.
     */
    public void setContextSnapshotJson(JSONB value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.agent_run.context_snapshot_json</code>.
     */
    public JSONB getContextSnapshotJson() {
        return (JSONB) get(6);
    }

    /**
     * Setter for <code>public.agent_run.policy_snapshot_json</code>.
     */
    public void setPolicySnapshotJson(JSONB value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.agent_run.policy_snapshot_json</code>.
     */
    public JSONB getPolicySnapshotJson() {
        return (JSONB) get(7);
    }

    /**
     * Setter for <code>public.agent_run.profile_version</code>.
     */
    public void setProfileVersion(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.agent_run.profile_version</code>.
     */
    public Integer getProfileVersion() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.agent_run.next_step_index</code>.
     */
    public void setNextStepIndex(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.agent_run.next_step_index</code>.
     */
    public Integer getNextStepIndex() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.agent_run.version</code>.
     */
    public void setVersion(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.agent_run.version</code>.
     */
    public Long getVersion() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>public.agent_run.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.agent_run.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(11);
    }

    /**
     * Setter for <code>public.agent_run.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.agent_run.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(12);
    }

    /**
     * Setter for <code>public.agent_run.completed_at</code>.
     */
    public void setCompletedAt(OffsetDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.agent_run.completed_at</code>.
     */
    public OffsetDateTime getCompletedAt() {
        return (OffsetDateTime) get(13);
    }

    /**
     * Setter for <code>public.agent_run.conversation_id</code>.
     */
    public void setConversationId(UUID value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.agent_run.conversation_id</code>.
     */
    public UUID getConversationId() {
        return (UUID) get(14);
    }

    /**
     * Setter for <code>public.agent_run.conversation_turn</code>.
     */
    public void setConversationTurn(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.agent_run.conversation_turn</code>.
     */
    public Long getConversationTurn() {
        return (Long) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AgentRunRecord
     */
    public AgentRunRecord() {
        super(AgentRun.AGENT_RUN);
    }

    /**
     * Create a detached, initialised AgentRunRecord
     */
    public AgentRunRecord(UUID id, UUID projectId, UUID agentInstanceId, UUID userId, String status, String instruction, JSONB contextSnapshotJson, JSONB policySnapshotJson, Integer profileVersion, Integer nextStepIndex, Long version, OffsetDateTime createdAt, OffsetDateTime updatedAt, OffsetDateTime completedAt, UUID conversationId, Long conversationTurn) {
        super(AgentRun.AGENT_RUN);

        setId(id);
        setProjectId(projectId);
        setAgentInstanceId(agentInstanceId);
        setUserId(userId);
        setStatus(status);
        setInstruction(instruction);
        setContextSnapshotJson(contextSnapshotJson);
        setPolicySnapshotJson(policySnapshotJson);
        setProfileVersion(profileVersion);
        setNextStepIndex(nextStepIndex);
        setVersion(version);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setCompletedAt(completedAt);
        setConversationId(conversationId);
        setConversationTurn(conversationTurn);
        resetChangedOnNotNull();
    }
}
