/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables.records;


import dev.agenvas.db.tables.AgentBinding;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Agent 显式输入：固定引用不可变产物版本
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AgentBindingRecord extends UpdatableRecordImpl<AgentBindingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.agent_binding.id</code>. 记录身份
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.agent_binding.id</code>. 记录身份
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.agent_binding.project_id</code>. 所属项目及授权作用域
     */
    public void setProjectId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.agent_binding.project_id</code>. 所属项目及授权作用域
     */
    public UUID getProjectId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.agent_binding.agent_instance_id</code>. Agent
     * 卡片配置身份
     */
    public void setAgentInstanceId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.agent_binding.agent_instance_id</code>. Agent
     * 卡片配置身份
     */
    public UUID getAgentInstanceId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.agent_binding.artifact_id</code>. 业务产物身份
     */
    public void setArtifactId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.agent_binding.artifact_id</code>. 业务产物身份
     */
    public UUID getArtifactId() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>public.agent_binding.selected_version_id</code>.
     * 显式选择的不可变产物版本
     */
    public void setSelectedVersionId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.agent_binding.selected_version_id</code>.
     * 显式选择的不可变产物版本
     */
    public UUID getSelectedVersionId() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>public.agent_binding.created_at</code>. 创建时间（UTC）
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.agent_binding.created_at</code>. 创建时间（UTC）
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AgentBindingRecord
     */
    public AgentBindingRecord() {
        super(AgentBinding.AGENT_BINDING);
    }

    /**
     * Create a detached, initialised AgentBindingRecord
     */
    public AgentBindingRecord(UUID id, UUID projectId, UUID agentInstanceId, UUID artifactId, UUID selectedVersionId, OffsetDateTime createdAt) {
        super(AgentBinding.AGENT_BINDING);

        setId(id);
        setProjectId(projectId);
        setAgentInstanceId(agentInstanceId);
        setArtifactId(artifactId);
        setSelectedVersionId(selectedVersionId);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
