/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables.records;


import dev.agenvas.db.tables.AgentConversation;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Persistent user conversation. Each accepted message starts a separately
 * budgeted AgentRun.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AgentConversationRecord extends UpdatableRecordImpl<AgentConversationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.agent_conversation.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.agent_conversation.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.agent_conversation.project_id</code>.
     */
    public void setProjectId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.agent_conversation.project_id</code>.
     */
    public UUID getProjectId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.agent_conversation.agent_instance_id</code>.
     */
    public void setAgentInstanceId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.agent_conversation.agent_instance_id</code>.
     */
    public UUID getAgentInstanceId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.agent_conversation.title</code>.
     */
    public void setTitle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.agent_conversation.title</code>.
     */
    public String getTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.agent_conversation.turn_count</code>.
     */
    public void setTurnCount(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.agent_conversation.turn_count</code>.
     */
    public Long getTurnCount() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.agent_conversation.version</code>.
     */
    public void setVersion(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.agent_conversation.version</code>.
     */
    public Long getVersion() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.agent_conversation.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.agent_conversation.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.agent_conversation.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.agent_conversation.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AgentConversationRecord
     */
    public AgentConversationRecord() {
        super(AgentConversation.AGENT_CONVERSATION);
    }

    /**
     * Create a detached, initialised AgentConversationRecord
     */
    public AgentConversationRecord(UUID id, UUID projectId, UUID agentInstanceId, String title, Long turnCount, Long version, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(AgentConversation.AGENT_CONVERSATION);

        setId(id);
        setProjectId(projectId);
        setAgentInstanceId(agentInstanceId);
        setTitle(title);
        setTurnCount(turnCount);
        setVersion(version);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
