/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables.records;


import dev.agenvas.db.tables.AppUser;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AppUserRecord extends UpdatableRecordImpl<AppUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.app_user.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.app_user.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.app_user.login_name</code>.
     */
    public void setLoginName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.app_user.login_name</code>.
     */
    public String getLoginName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.app_user.password_hash</code>.
     */
    public void setPasswordHash(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.app_user.password_hash</code>.
     */
    public String getPasswordHash() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.app_user.status</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.app_user.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.app_user.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.app_user.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.app_user.password_changed_at</code>. Time of the
     * latest password change; used for session and audit decisions.
     */
    public void setPasswordChangedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.app_user.password_changed_at</code>. Time of the
     * latest password change; used for session and audit decisions.
     */
    public OffsetDateTime getPasswordChangedAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.app_user.version</code>. Optimistic version for
     * security-sensitive administrator updates.
     */
    public void setVersion(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.app_user.version</code>. Optimistic version for
     * security-sensitive administrator updates.
     */
    public Long getVersion() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppUserRecord
     */
    public AppUserRecord() {
        super(AppUser.APP_USER);
    }

    /**
     * Create a detached, initialised AppUserRecord
     */
    public AppUserRecord(UUID id, String loginName, String passwordHash, String status, OffsetDateTime createdAt, OffsetDateTime passwordChangedAt, Long version) {
        super(AppUser.APP_USER);

        setId(id);
        setLoginName(loginName);
        setPasswordHash(passwordHash);
        setStatus(status);
        setCreatedAt(createdAt);
        setPasswordChangedAt(passwordChangedAt);
        setVersion(version);
        resetChangedOnNotNull();
    }
}
