/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables.records;


import dev.agenvas.db.tables.Artifact;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ArtifactRecord extends UpdatableRecordImpl<ArtifactRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.artifact.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.artifact.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.artifact.project_id</code>.
     */
    public void setProjectId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.artifact.project_id</code>.
     */
    public UUID getProjectId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.artifact.kind</code>.
     */
    public void setKind(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.artifact.kind</code>.
     */
    public String getKind() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.artifact.title</code>.
     */
    public void setTitle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.artifact.title</code>.
     */
    public String getTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.artifact.current_version_id</code>.
     */
    public void setCurrentVersionId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.artifact.current_version_id</code>.
     */
    public UUID getCurrentVersionId() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>public.artifact.archived_at</code>.
     */
    public void setArchivedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.artifact.archived_at</code>.
     */
    public OffsetDateTime getArchivedAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.artifact.version</code>.
     */
    public void setVersion(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.artifact.version</code>.
     */
    public Long getVersion() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.artifact.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.artifact.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.artifact.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.artifact.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArtifactRecord
     */
    public ArtifactRecord() {
        super(Artifact.ARTIFACT);
    }

    /**
     * Create a detached, initialised ArtifactRecord
     */
    public ArtifactRecord(UUID id, UUID projectId, String kind, String title, UUID currentVersionId, OffsetDateTime archivedAt, Long version, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(Artifact.ARTIFACT);

        setId(id);
        setProjectId(projectId);
        setKind(kind);
        setTitle(title);
        setCurrentVersionId(currentVersionId);
        setArchivedAt(archivedAt);
        setVersion(version);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
