/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables.records;


import dev.agenvas.db.tables.AuditLogRetentionSettings;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 全局调用日志保留期限及配置版本
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AuditLogRetentionSettingsRecord extends UpdatableRecordImpl<AuditLogRetentionSettingsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.audit_log_retention_settings.id</code>. 记录身份
     */
    public void setId(Short value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.audit_log_retention_settings.id</code>. 记录身份
     */
    public Short getId() {
        return (Short) get(0);
    }

    /**
     * Setter for
     * <code>public.audit_log_retention_settings.retention_days</code>.
     * 调用日志保留天数；为空表示永久，清理须管理员显式执行
     */
    public void setRetentionDays(Integer value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>public.audit_log_retention_settings.retention_days</code>.
     * 调用日志保留天数；为空表示永久，清理须管理员显式执行
     */
    public Integer getRetentionDays() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.audit_log_retention_settings.version</code>.
     * 乐观并发控制版本，更新时递增并校验预期值
     */
    public void setVersion(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.audit_log_retention_settings.version</code>.
     * 乐观并发控制版本，更新时递增并校验预期值
     */
    public Integer getVersion() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Short> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuditLogRetentionSettingsRecord
     */
    public AuditLogRetentionSettingsRecord() {
        super(AuditLogRetentionSettings.AUDIT_LOG_RETENTION_SETTINGS);
    }

    /**
     * Create a detached, initialised AuditLogRetentionSettingsRecord
     */
    public AuditLogRetentionSettingsRecord(Short id, Integer retentionDays, Integer version) {
        super(AuditLogRetentionSettings.AUDIT_LOG_RETENTION_SETTINGS);

        setId(id);
        setRetentionDays(retentionDays);
        setVersion(version);
        resetChangedOnNotNull();
    }
}
