/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables.records;


import dev.agenvas.db.tables.CallLogDebug;

import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Opt-in HTTP bodies and URLs, with credentials and private reasoning removed;
 * never part of project export.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CallLogDebugRecord extends UpdatableRecordImpl<CallLogDebugRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.call_log_debug.call_id</code>.
     */
    public void setCallId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.call_log_debug.call_id</code>.
     */
    public UUID getCallId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.call_log_debug.schema_version</code>.
     */
    public void setSchemaVersion(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.call_log_debug.schema_version</code>.
     */
    public Integer getSchemaVersion() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.call_log_debug.exchanges_json</code>.
     */
    public void setExchangesJson(JSONB value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.call_log_debug.exchanges_json</code>.
     */
    public JSONB getExchangesJson() {
        return (JSONB) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CallLogDebugRecord
     */
    public CallLogDebugRecord() {
        super(CallLogDebug.CALL_LOG_DEBUG);
    }

    /**
     * Create a detached, initialised CallLogDebugRecord
     */
    public CallLogDebugRecord(UUID callId, Integer schemaVersion, JSONB exchangesJson) {
        super(CallLogDebug.CALL_LOG_DEBUG);

        setCallId(callId);
        setSchemaVersion(schemaVersion);
        setExchangesJson(exchangesJson);
        resetChangedOnNotNull();
    }
}
