/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables.records;


import dev.agenvas.db.tables.CanvasItem;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 画布空间卡片及卡片独立的标题、版本选择与内容选择 epoch
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CanvasItemRecord extends UpdatableRecordImpl<CanvasItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.canvas_item.id</code>. 记录身份
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.canvas_item.id</code>. 记录身份
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.canvas_item.project_id</code>. 所属项目及授权作用域
     */
    public void setProjectId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.canvas_item.project_id</code>. 所属项目及授权作用域
     */
    public UUID getProjectId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.canvas_item.subject_type</code>. 卡片承载 Agent 或
     * Artifact
     */
    public void setSubjectType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.canvas_item.subject_type</code>. 卡片承载 Agent 或
     * Artifact
     */
    public String getSubjectType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.canvas_item.subject_id</code>. 卡片业务对象身份
     */
    public void setSubjectId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.canvas_item.subject_id</code>. 卡片业务对象身份
     */
    public UUID getSubjectId() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>public.canvas_item.artifact_id</code>. 业务产物身份
     */
    public void setArtifactId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.canvas_item.artifact_id</code>. 业务产物身份
     */
    public UUID getArtifactId() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>public.canvas_item.x</code>. 画布水平坐标
     */
    public void setX(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.canvas_item.x</code>. 画布水平坐标
     */
    public BigDecimal getX() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>public.canvas_item.y</code>. 画布垂直坐标
     */
    public void setY(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.canvas_item.y</code>. 画布垂直坐标
     */
    public BigDecimal getY() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>public.canvas_item.width</code>. 媒体像素宽度或画布卡片宽度
     */
    public void setWidth(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.canvas_item.width</code>. 媒体像素宽度或画布卡片宽度
     */
    public BigDecimal getWidth() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>public.canvas_item.height</code>. 媒体像素高度或画布卡片高度
     */
    public void setHeight(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.canvas_item.height</code>. 媒体像素高度或画布卡片高度
     */
    public BigDecimal getHeight() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>public.canvas_item.z_index</code>. 画布层叠顺序
     */
    public void setZIndex(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.canvas_item.z_index</code>. 画布层叠顺序
     */
    public Integer getZIndex() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.canvas_item.group_id</code>. 卡片所属画布分组
     */
    public void setGroupId(UUID value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.canvas_item.group_id</code>. 卡片所属画布分组
     */
    public UUID getGroupId() {
        return (UUID) get(10);
    }

    /**
     * Setter for <code>public.canvas_item.locked</code>. 是否禁止交互修改卡片布局
     */
    public void setLocked(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.canvas_item.locked</code>. 是否禁止交互修改卡片布局
     */
    public Boolean getLocked() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>public.canvas_item.version</code>. 乐观并发控制版本，更新时递增并校验预期值
     */
    public void setVersion(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.canvas_item.version</code>. 乐观并发控制版本，更新时递增并校验预期值
     */
    public Long getVersion() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>public.canvas_item.created_at</code>. 创建时间（UTC）
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.canvas_item.created_at</code>. 创建时间（UTC）
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(13);
    }

    /**
     * Setter for <code>public.canvas_item.updated_at</code>. 最后状态或配置更新时间（UTC）
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.canvas_item.updated_at</code>. 最后状态或配置更新时间（UTC）
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(14);
    }

    /**
     * Setter for <code>public.canvas_item.agent_instance_id</code>. Agent
     * 卡片配置身份
     */
    public void setAgentInstanceId(UUID value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.canvas_item.agent_instance_id</code>. Agent
     * 卡片配置身份
     */
    public UUID getAgentInstanceId() {
        return (UUID) get(15);
    }

    /**
     * Setter for <code>public.canvas_item.title</code>. Per-card display title
     * initialized from its subject and edited independently afterward.
     */
    public void setTitle(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.canvas_item.title</code>. Per-card display title
     * initialized from its subject and edited independently afterward.
     */
    public String getTitle() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.canvas_item.selected_version_id</code>. Version
     * displayed by this card. Media cards own this independently of the
     * Artifact default.
     */
    public void setSelectedVersionId(UUID value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.canvas_item.selected_version_id</code>. Version
     * displayed by this card. Media cards own this independently of the
     * Artifact default.
     */
    public UUID getSelectedVersionId() {
        return (UUID) get(17);
    }

    /**
     * Setter for <code>public.canvas_item.media_selection_epoch</code>. Content
     * selection revision, independent of layout CAS; prevents late tasks from
     * replacing user selections.
     */
    public void setMediaSelectionEpoch(Long value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.canvas_item.media_selection_epoch</code>. Content
     * selection revision, independent of layout CAS; prevents late tasks from
     * replacing user selections.
     */
    public Long getMediaSelectionEpoch() {
        return (Long) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CanvasItemRecord
     */
    public CanvasItemRecord() {
        super(CanvasItem.CANVAS_ITEM);
    }

    /**
     * Create a detached, initialised CanvasItemRecord
     */
    public CanvasItemRecord(UUID id, UUID projectId, String subjectType, UUID subjectId, UUID artifactId, BigDecimal x, BigDecimal y, BigDecimal width, BigDecimal height, Integer zIndex, UUID groupId, Boolean locked, Long version, OffsetDateTime createdAt, OffsetDateTime updatedAt, UUID agentInstanceId, String title, UUID selectedVersionId, Long mediaSelectionEpoch) {
        super(CanvasItem.CANVAS_ITEM);

        setId(id);
        setProjectId(projectId);
        setSubjectType(subjectType);
        setSubjectId(subjectId);
        setArtifactId(artifactId);
        setX(x);
        setY(y);
        setWidth(width);
        setHeight(height);
        setZIndex(zIndex);
        setGroupId(groupId);
        setLocked(locked);
        setVersion(version);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setAgentInstanceId(agentInstanceId);
        setTitle(title);
        setSelectedVersionId(selectedVersionId);
        setMediaSelectionEpoch(mediaSelectionEpoch);
        resetChangedOnNotNull();
    }
}
