/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables.records;


import dev.agenvas.db.tables.CanvasItemMediaInputSource;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Manual and connection reasons that keep a deduplicated media input alive.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CanvasItemMediaInputSourceRecord extends UpdatableRecordImpl<CanvasItemMediaInputSourceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.canvas_item_media_input_source.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.canvas_item_media_input_source.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.canvas_item_media_input_source.project_id</code>.
     */
    public void setProjectId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.canvas_item_media_input_source.project_id</code>.
     */
    public UUID getProjectId() {
        return (UUID) get(1);
    }

    /**
     * Setter for
     * <code>public.canvas_item_media_input_source.canvas_item_id</code>.
     */
    public void setCanvasItemId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>public.canvas_item_media_input_source.canvas_item_id</code>.
     */
    public UUID getCanvasItemId() {
        return (UUID) get(2);
    }

    /**
     * Setter for
     * <code>public.canvas_item_media_input_source.artifact_version_id</code>.
     */
    public void setArtifactVersionId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>public.canvas_item_media_input_source.artifact_version_id</code>.
     */
    public UUID getArtifactVersionId() {
        return (UUID) get(3);
    }

    /**
     * Setter for
     * <code>public.canvas_item_media_input_source.source_type</code>.
     */
    public void setSourceType(String value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>public.canvas_item_media_input_source.source_type</code>.
     */
    public String getSourceType() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>public.canvas_item_media_input_source.connection_id</code>.
     */
    public void setConnectionId(UUID value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>public.canvas_item_media_input_source.connection_id</code>.
     */
    public UUID getConnectionId() {
        return (UUID) get(5);
    }

    /**
     * Setter for <code>public.canvas_item_media_input_source.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.canvas_item_media_input_source.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CanvasItemMediaInputSourceRecord
     */
    public CanvasItemMediaInputSourceRecord() {
        super(CanvasItemMediaInputSource.CANVAS_ITEM_MEDIA_INPUT_SOURCE);
    }

    /**
     * Create a detached, initialised CanvasItemMediaInputSourceRecord
     */
    public CanvasItemMediaInputSourceRecord(UUID id, UUID projectId, UUID canvasItemId, UUID artifactVersionId, String sourceType, UUID connectionId, OffsetDateTime createdAt) {
        super(CanvasItemMediaInputSource.CANVAS_ITEM_MEDIA_INPUT_SOURCE);

        setId(id);
        setProjectId(projectId);
        setCanvasItemId(canvasItemId);
        setArtifactVersionId(artifactVersionId);
        setSourceType(sourceType);
        setConnectionId(connectionId);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
