/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables.records;


import dev.agenvas.db.tables.CanvasItemMediaInput;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 媒体卡片显式选取的精确输入版本、角色、顺序和显示颜色
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CanvasItemMediaInputRecord extends UpdatableRecordImpl<CanvasItemMediaInputRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.canvas_item_media_input.project_id</code>.
     * 所属项目及授权作用域
     */
    public void setProjectId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.canvas_item_media_input.project_id</code>.
     * 所属项目及授权作用域
     */
    public UUID getProjectId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.canvas_item_media_input.canvas_item_id</code>.
     * 固定的目标或上下文画布卡片
     */
    public void setCanvasItemId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.canvas_item_media_input.canvas_item_id</code>.
     * 固定的目标或上下文画布卡片
     */
    public UUID getCanvasItemId() {
        return (UUID) get(1);
    }

    /**
     * Setter for
     * <code>public.canvas_item_media_input.artifact_version_id</code>.
     * 固定的不可变产物版本
     */
    public void setArtifactVersionId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>public.canvas_item_media_input.artifact_version_id</code>.
     * 固定的不可变产物版本
     */
    public UUID getArtifactVersionId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.canvas_item_media_input.input_role</code>. 媒体输入角色
     */
    public void setInputRole(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.canvas_item_media_input.input_role</code>. 媒体输入角色
     */
    public String getInputRole() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.canvas_item_media_input.input_order</code>.
     * 同角色媒体输入顺序
     */
    public void setInputOrder(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.canvas_item_media_input.input_order</code>.
     * 同角色媒体输入顺序
     */
    public Integer getInputOrder() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.canvas_item_media_input.color</code>.
     * 媒体输入来源连线的显示颜色
     */
    public void setColor(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.canvas_item_media_input.color</code>.
     * 媒体输入来源连线的显示颜色
     */
    public String getColor() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.canvas_item_media_input.created_at</code>.
     * 创建时间（UTC）
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.canvas_item_media_input.created_at</code>.
     * 创建时间（UTC）
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.canvas_item_media_input.updated_at</code>.
     * 最后状态或配置更新时间（UTC）
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.canvas_item_media_input.updated_at</code>.
     * 最后状态或配置更新时间（UTC）
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<UUID, UUID, UUID> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CanvasItemMediaInputRecord
     */
    public CanvasItemMediaInputRecord() {
        super(CanvasItemMediaInput.CANVAS_ITEM_MEDIA_INPUT);
    }

    /**
     * Create a detached, initialised CanvasItemMediaInputRecord
     */
    public CanvasItemMediaInputRecord(UUID projectId, UUID canvasItemId, UUID artifactVersionId, String inputRole, Integer inputOrder, String color, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(CanvasItemMediaInput.CANVAS_ITEM_MEDIA_INPUT);

        setProjectId(projectId);
        setCanvasItemId(canvasItemId);
        setArtifactVersionId(artifactVersionId);
        setInputRole(inputRole);
        setInputOrder(inputOrder);
        setColor(color);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
