/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables.records;


import dev.agenvas.db.tables.ComfyuiConfigVersion;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ComfyuiConfigVersionRecord extends UpdatableRecordImpl<ComfyuiConfigVersionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.comfyui_config_version.config_version</code>.
     */
    public void setConfigVersion(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.comfyui_config_version.config_version</code>.
     */
    public Integer getConfigVersion() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.comfyui_config_version.origin</code>.
     */
    public void setOrigin(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.comfyui_config_version.origin</code>.
     */
    public String getOrigin() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.comfyui_config_version.origin_sha256</code>.
     */
    public void setOriginSha256(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.comfyui_config_version.origin_sha256</code>.
     */
    public String getOriginSha256() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.comfyui_config_version.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.comfyui_config_version.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ComfyuiConfigVersionRecord
     */
    public ComfyuiConfigVersionRecord() {
        super(ComfyuiConfigVersion.COMFYUI_CONFIG_VERSION);
    }

    /**
     * Create a detached, initialised ComfyuiConfigVersionRecord
     */
    public ComfyuiConfigVersionRecord(Integer configVersion, String origin, String originSha256, OffsetDateTime createdAt) {
        super(ComfyuiConfigVersion.COMFYUI_CONFIG_VERSION);

        setConfigVersion(configVersion);
        setOrigin(origin);
        setOriginSha256(originSha256);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
