/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables.records;


import dev.agenvas.db.tables.CreativeDataResetMarker;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CreativeDataResetMarkerRecord extends UpdatableRecordImpl<CreativeDataResetMarkerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.creative_data_reset_marker.id</code>.
     */
    public void setId(Short value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.creative_data_reset_marker.id</code>.
     */
    public Short getId() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>public.creative_data_reset_marker.completed_at</code>.
     */
    public void setCompletedAt(OffsetDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.creative_data_reset_marker.completed_at</code>.
     */
    public OffsetDateTime getCompletedAt() {
        return (OffsetDateTime) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Short> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CreativeDataResetMarkerRecord
     */
    public CreativeDataResetMarkerRecord() {
        super(CreativeDataResetMarker.CREATIVE_DATA_RESET_MARKER);
    }

    /**
     * Create a detached, initialised CreativeDataResetMarkerRecord
     */
    public CreativeDataResetMarkerRecord(Short id, OffsetDateTime completedAt) {
        super(CreativeDataResetMarker.CREATIVE_DATA_RESET_MARKER);

        setId(id);
        setCompletedAt(completedAt);
        resetChangedOnNotNull();
    }
}
