/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables.records;


import dev.agenvas.db.tables.ExecutionPlan;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Immutable proposal content and revision identity; only status may change
 * after proposal.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ExecutionPlanRecord extends UpdatableRecordImpl<ExecutionPlanRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.execution_plan.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.execution_plan.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.execution_plan.project_id</code>.
     */
    public void setProjectId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.execution_plan.project_id</code>.
     */
    public UUID getProjectId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.execution_plan.run_id</code>.
     */
    public void setRunId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.execution_plan.run_id</code>.
     */
    public UUID getRunId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.execution_plan.revision</code>.
     */
    public void setRevision(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.execution_plan.revision</code>.
     */
    public Integer getRevision() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.execution_plan.stage</code>.
     */
    public void setStage(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.execution_plan.stage</code>.
     */
    public String getStage() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.execution_plan.status</code>.
     */
    public void setStatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.execution_plan.status</code>.
     */
    public String getStatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.execution_plan.objective</code>.
     */
    public void setObjective(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.execution_plan.objective</code>.
     */
    public String getObjective() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.execution_plan.plan_json</code>.
     */
    public void setPlanJson(JSONB value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.execution_plan.plan_json</code>.
     */
    public JSONB getPlanJson() {
        return (JSONB) get(7);
    }

    /**
     * Setter for <code>public.execution_plan.input_snapshot_json</code>.
     */
    public void setInputSnapshotJson(JSONB value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.execution_plan.input_snapshot_json</code>.
     */
    public JSONB getInputSnapshotJson() {
        return (JSONB) get(8);
    }

    /**
     * Setter for <code>public.execution_plan.input_snapshot_hash</code>.
     */
    public void setInputSnapshotHash(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.execution_plan.input_snapshot_hash</code>.
     */
    public String getInputSnapshotHash() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.execution_plan.plan_hash</code>.
     */
    public void setPlanHash(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.execution_plan.plan_hash</code>.
     */
    public String getPlanHash() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.execution_plan.provider_config_version</code>.
     */
    public void setProviderConfigVersion(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.execution_plan.provider_config_version</code>.
     */
    public Integer getProviderConfigVersion() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.execution_plan.workflow_version</code>.
     */
    public void setWorkflowVersion(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.execution_plan.workflow_version</code>.
     */
    public String getWorkflowVersion() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.execution_plan.estimate_json</code>.
     */
    public void setEstimateJson(JSONB value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.execution_plan.estimate_json</code>.
     */
    public JSONB getEstimateJson() {
        return (JSONB) get(13);
    }

    /**
     * Setter for <code>public.execution_plan.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.execution_plan.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(14);
    }

    /**
     * Setter for <code>public.execution_plan.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.execution_plan.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExecutionPlanRecord
     */
    public ExecutionPlanRecord() {
        super(ExecutionPlan.EXECUTION_PLAN);
    }

    /**
     * Create a detached, initialised ExecutionPlanRecord
     */
    public ExecutionPlanRecord(UUID id, UUID projectId, UUID runId, Integer revision, String stage, String status, String objective, JSONB planJson, JSONB inputSnapshotJson, String inputSnapshotHash, String planHash, Integer providerConfigVersion, String workflowVersion, JSONB estimateJson, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(ExecutionPlan.EXECUTION_PLAN);

        setId(id);
        setProjectId(projectId);
        setRunId(runId);
        setRevision(revision);
        setStage(stage);
        setStatus(status);
        setObjective(objective);
        setPlanJson(planJson);
        setInputSnapshotJson(inputSnapshotJson);
        setInputSnapshotHash(inputSnapshotHash);
        setPlanHash(planHash);
        setProviderConfigVersion(providerConfigVersion);
        setWorkflowVersion(workflowVersion);
        setEstimateJson(estimateJson);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
