/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables.records;


import dev.agenvas.db.tables.ExportProposal;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Agent-suggested immutable export input; only an authenticated user may
 * authorize a Task.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ExportProposalRecord extends UpdatableRecordImpl<ExportProposalRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.export_proposal.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.export_proposal.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.export_proposal.project_id</code>.
     */
    public void setProjectId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.export_proposal.project_id</code>.
     */
    public UUID getProjectId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.export_proposal.run_id</code>.
     */
    public void setRunId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.export_proposal.run_id</code>.
     */
    public UUID getRunId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.export_proposal.status</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.export_proposal.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.export_proposal.input_json</code>.
     */
    public void setInputJson(JSONB value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.export_proposal.input_json</code>.
     */
    public JSONB getInputJson() {
        return (JSONB) get(4);
    }

    /**
     * Setter for <code>public.export_proposal.input_pins_json</code>.
     */
    public void setInputPinsJson(JSONB value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.export_proposal.input_pins_json</code>.
     */
    public JSONB getInputPinsJson() {
        return (JSONB) get(5);
    }

    /**
     * Setter for <code>public.export_proposal.proposal_hash</code>.
     */
    public void setProposalHash(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.export_proposal.proposal_hash</code>.
     */
    public String getProposalHash() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.export_proposal.project_version</code>.
     */
    public void setProjectVersion(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.export_proposal.project_version</code>.
     */
    public Long getProjectVersion() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.export_proposal.approved_task_id</code>.
     */
    public void setApprovedTaskId(UUID value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.export_proposal.approved_task_id</code>.
     */
    public UUID getApprovedTaskId() {
        return (UUID) get(8);
    }

    /**
     * Setter for <code>public.export_proposal.decided_by_user_id</code>.
     */
    public void setDecidedByUserId(UUID value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.export_proposal.decided_by_user_id</code>.
     */
    public UUID getDecidedByUserId() {
        return (UUID) get(9);
    }

    /**
     * Setter for <code>public.export_proposal.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.export_proposal.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(10);
    }

    /**
     * Setter for <code>public.export_proposal.decided_at</code>.
     */
    public void setDecidedAt(OffsetDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.export_proposal.decided_at</code>.
     */
    public OffsetDateTime getDecidedAt() {
        return (OffsetDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExportProposalRecord
     */
    public ExportProposalRecord() {
        super(ExportProposal.EXPORT_PROPOSAL);
    }

    /**
     * Create a detached, initialised ExportProposalRecord
     */
    public ExportProposalRecord(UUID id, UUID projectId, UUID runId, String status, JSONB inputJson, JSONB inputPinsJson, String proposalHash, Long projectVersion, UUID approvedTaskId, UUID decidedByUserId, OffsetDateTime createdAt, OffsetDateTime decidedAt) {
        super(ExportProposal.EXPORT_PROPOSAL);

        setId(id);
        setProjectId(projectId);
        setRunId(runId);
        setStatus(status);
        setInputJson(inputJson);
        setInputPinsJson(inputPinsJson);
        setProposalHash(proposalHash);
        setProjectVersion(projectVersion);
        setApprovedTaskId(approvedTaskId);
        setDecidedByUserId(decidedByUserId);
        setCreatedAt(createdAt);
        setDecidedAt(decidedAt);
        resetChangedOnNotNull();
    }
}
