/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables.records;


import dev.agenvas.db.tables.InstallationLock;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 管理员初始化的单例事务锁行
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InstallationLockRecord extends UpdatableRecordImpl<InstallationLockRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.installation_lock.id</code>. 记录身份
     */
    public void setId(Short value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.installation_lock.id</code>. 记录身份
     */
    public Short getId() {
        return (Short) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Short> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InstallationLockRecord
     */
    public InstallationLockRecord() {
        super(InstallationLock.INSTALLATION_LOCK);
    }

    /**
     * Create a detached, initialised InstallationLockRecord
     */
    public InstallationLockRecord(Short id) {
        super(InstallationLock.INSTALLATION_LOCK);

        setId(id);
        resetChangedOnNotNull();
    }
}
