/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables.records;


import dev.agenvas.db.tables.LibraryEntry;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LibraryEntryRecord extends UpdatableRecordImpl<LibraryEntryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.library_entry.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.library_entry.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.library_entry.owner_id</code>.
     */
    public void setOwnerId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.library_entry.owner_id</code>.
     */
    public UUID getOwnerId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.library_entry.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.library_entry.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.library_entry.category</code>.
     */
    public void setCategory(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.library_entry.category</code>.
     */
    public String getCategory() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.library_entry.kind</code>.
     */
    public void setKind(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.library_entry.kind</code>.
     */
    public String getKind() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.library_entry.content_schema_version</code>.
     */
    public void setContentSchemaVersion(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.library_entry.content_schema_version</code>.
     */
    public Integer getContentSchemaVersion() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.library_entry.text_content</code>.
     */
    public void setTextContent(JSONB value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.library_entry.text_content</code>.
     */
    public JSONB getTextContent() {
        return (JSONB) get(6);
    }

    /**
     * Setter for <code>public.library_entry.file_id</code>.
     */
    public void setFileId(UUID value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.library_entry.file_id</code>.
     */
    public UUID getFileId() {
        return (UUID) get(7);
    }

    /**
     * Setter for <code>public.library_entry.source_version_id</code>.
     */
    public void setSourceVersionId(UUID value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.library_entry.source_version_id</code>.
     */
    public UUID getSourceVersionId() {
        return (UUID) get(8);
    }

    /**
     * Setter for <code>public.library_entry.source_json</code>.
     */
    public void setSourceJson(JSONB value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.library_entry.source_json</code>.
     */
    public JSONB getSourceJson() {
        return (JSONB) get(9);
    }

    /**
     * Setter for <code>public.library_entry.favorite</code>.
     */
    public void setFavorite(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.library_entry.favorite</code>.
     */
    public Boolean getFavorite() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>public.library_entry.trashed_at</code>.
     */
    public void setTrashedAt(OffsetDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.library_entry.trashed_at</code>.
     */
    public OffsetDateTime getTrashedAt() {
        return (OffsetDateTime) get(11);
    }

    /**
     * Setter for <code>public.library_entry.version</code>.
     */
    public void setVersion(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.library_entry.version</code>.
     */
    public Long getVersion() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>public.library_entry.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.library_entry.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(13);
    }

    /**
     * Setter for <code>public.library_entry.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.library_entry.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LibraryEntryRecord
     */
    public LibraryEntryRecord() {
        super(LibraryEntry.LIBRARY_ENTRY);
    }

    /**
     * Create a detached, initialised LibraryEntryRecord
     */
    public LibraryEntryRecord(UUID id, UUID ownerId, String name, String category, String kind, Integer contentSchemaVersion, JSONB textContent, UUID fileId, UUID sourceVersionId, JSONB sourceJson, Boolean favorite, OffsetDateTime trashedAt, Long version, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(LibraryEntry.LIBRARY_ENTRY);

        setId(id);
        setOwnerId(ownerId);
        setName(name);
        setCategory(category);
        setKind(kind);
        setContentSchemaVersion(contentSchemaVersion);
        setTextContent(textContent);
        setFileId(fileId);
        setSourceVersionId(sourceVersionId);
        setSourceJson(sourceJson);
        setFavorite(favorite);
        setTrashedAt(trashedAt);
        setVersion(version);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
