/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables.records;


import dev.agenvas.db.tables.LibraryCommand;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Durable local transfers; no provider submission or generation retry
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LibraryCommandRecord extends UpdatableRecordImpl<LibraryCommandRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.library_command.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.library_command.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.library_command.owner_id</code>.
     */
    public void setOwnerId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.library_command.owner_id</code>.
     */
    public UUID getOwnerId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.library_command.command_key</code>.
     */
    public void setCommandKey(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.library_command.command_key</code>.
     */
    public String getCommandKey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.library_command.payload_hash</code>.
     */
    public void setPayloadHash(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.library_command.payload_hash</code>.
     */
    public String getPayloadHash() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.library_command.kind</code>.
     */
    public void setKind(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.library_command.kind</code>.
     */
    public String getKind() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.library_command.input_json</code>.
     */
    public void setInputJson(JSONB value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.library_command.input_json</code>.
     */
    public JSONB getInputJson() {
        return (JSONB) get(5);
    }

    /**
     * Setter for <code>public.library_command.status</code>.
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.library_command.status</code>.
     */
    public String getStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.library_command.epoch</code>.
     */
    public void setEpoch(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.library_command.epoch</code>.
     */
    public Long getEpoch() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.library_command.lease_until</code>.
     */
    public void setLeaseUntil(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.library_command.lease_until</code>.
     */
    public OffsetDateTime getLeaseUntil() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>public.library_command.result_json</code>.
     */
    public void setResultJson(JSONB value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.library_command.result_json</code>.
     */
    public JSONB getResultJson() {
        return (JSONB) get(9);
    }

    /**
     * Setter for <code>public.library_command.error_code</code>.
     */
    public void setErrorCode(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.library_command.error_code</code>.
     */
    public String getErrorCode() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.library_command.error_detail</code>.
     */
    public void setErrorDetail(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.library_command.error_detail</code>.
     */
    public String getErrorDetail() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.library_command.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.library_command.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(12);
    }

    /**
     * Setter for <code>public.library_command.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.library_command.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LibraryCommandRecord
     */
    public LibraryCommandRecord() {
        super(LibraryCommand.LIBRARY_COMMAND);
    }

    /**
     * Create a detached, initialised LibraryCommandRecord
     */
    public LibraryCommandRecord(UUID id, UUID ownerId, String commandKey, String payloadHash, String kind, JSONB inputJson, String status, Long epoch, OffsetDateTime leaseUntil, JSONB resultJson, String errorCode, String errorDetail, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(LibraryCommand.LIBRARY_COMMAND);

        setId(id);
        setOwnerId(ownerId);
        setCommandKey(commandKey);
        setPayloadHash(payloadHash);
        setKind(kind);
        setInputJson(inputJson);
        setStatus(status);
        setEpoch(epoch);
        setLeaseUntil(leaseUntil);
        setResultJson(resultJson);
        setErrorCode(errorCode);
        setErrorDetail(errorDetail);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
