/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables.records;


import dev.agenvas.db.tables.LlmProviderConfig;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Immutable versioned LLM endpoint and AES-GCM encrypted credential; old
 * versions remain for recovery.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LlmProviderConfigRecord extends UpdatableRecordImpl<LlmProviderConfigRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.llm_provider_config.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.llm_provider_config.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.llm_provider_config.version</code>.
     */
    public void setVersion(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.llm_provider_config.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.llm_provider_config.endpoint</code>.
     */
    public void setEndpoint(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.llm_provider_config.endpoint</code>.
     */
    public String getEndpoint() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.llm_provider_config.model_id</code>.
     */
    public void setModelId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.llm_provider_config.model_id</code>.
     */
    public String getModelId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.llm_provider_config.credential_ciphertext</code>.
     */
    public void setCredentialCiphertext(byte[] value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.llm_provider_config.credential_ciphertext</code>.
     */
    public byte[] getCredentialCiphertext() {
        return (byte[]) get(4);
    }

    /**
     * Setter for <code>public.llm_provider_config.credential_nonce</code>.
     */
    public void setCredentialNonce(byte[] value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.llm_provider_config.credential_nonce</code>.
     */
    public byte[] getCredentialNonce() {
        return (byte[]) get(5);
    }

    /**
     * Setter for <code>public.llm_provider_config.key_version</code>.
     */
    public void setKeyVersion(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.llm_provider_config.key_version</code>.
     */
    public Integer getKeyVersion() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.llm_provider_config.key_mask</code>.
     */
    public void setKeyMask(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.llm_provider_config.key_mask</code>.
     */
    public String getKeyMask() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.llm_provider_config.tool_calling_verified</code>.
     */
    public void setToolCallingVerified(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.llm_provider_config.tool_calling_verified</code>.
     */
    public Boolean getToolCallingVerified() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>public.llm_provider_config.active</code>.
     */
    public void setActive(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.llm_provider_config.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>public.llm_provider_config.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.llm_provider_config.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LlmProviderConfigRecord
     */
    public LlmProviderConfigRecord() {
        super(LlmProviderConfig.LLM_PROVIDER_CONFIG);
    }

    /**
     * Create a detached, initialised LlmProviderConfigRecord
     */
    public LlmProviderConfigRecord(UUID id, Integer version, String endpoint, String modelId, byte[] credentialCiphertext, byte[] credentialNonce, Integer keyVersion, String keyMask, Boolean toolCallingVerified, Boolean active, OffsetDateTime createdAt) {
        super(LlmProviderConfig.LLM_PROVIDER_CONFIG);

        setId(id);
        setVersion(version);
        setEndpoint(endpoint);
        setModelId(modelId);
        setCredentialCiphertext(credentialCiphertext);
        setCredentialNonce(credentialNonce);
        setKeyVersion(keyVersion);
        setKeyMask(keyMask);
        setToolCallingVerified(toolCallingVerified);
        setActive(active);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
