/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables.records;


import dev.agenvas.db.tables.MediaTemplateImage;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 模板参考图片的归档存储元数据
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MediaTemplateImageRecord extends UpdatableRecordImpl<MediaTemplateImageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.media_template_image.id</code>. 记录身份
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.media_template_image.id</code>. 记录身份
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.media_template_image.owner_id</code>. 所属用户及授权作用域
     */
    public void setOwnerId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.media_template_image.owner_id</code>. 所属用户及授权作用域
     */
    public UUID getOwnerId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.media_template_image.metadata_json</code>.
     * 存储对象元数据，包含定位和完整性验证所需信息
     */
    public void setMetadataJson(JSONB value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.media_template_image.metadata_json</code>.
     * 存储对象元数据，包含定位和完整性验证所需信息
     */
    public JSONB getMetadataJson() {
        return (JSONB) get(2);
    }

    /**
     * Setter for <code>public.media_template_image.created_at</code>. 创建时间（UTC）
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.media_template_image.created_at</code>. 创建时间（UTC）
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MediaTemplateImageRecord
     */
    public MediaTemplateImageRecord() {
        super(MediaTemplateImage.MEDIA_TEMPLATE_IMAGE);
    }

    /**
     * Create a detached, initialised MediaTemplateImageRecord
     */
    public MediaTemplateImageRecord(UUID id, UUID ownerId, JSONB metadataJson, OffsetDateTime createdAt) {
        super(MediaTemplateImage.MEDIA_TEMPLATE_IMAGE);

        setId(id);
        setOwnerId(ownerId);
        setMetadataJson(metadataJson);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
