/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables.records;


import dev.agenvas.db.tables.MediaStyle;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 媒体生成风格目录及内置风格缩略图
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MediaStyleRecord extends UpdatableRecordImpl<MediaStyleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.media_style.id</code>. 记录身份
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.media_style.id</code>. 记录身份
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.media_style.name</code>. 显示名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.media_style.name</code>. 显示名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.media_style.category</code>. 目录分类
     */
    public void setCategory(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.media_style.category</code>. 目录分类
     */
    public String getCategory() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.media_style.prompt_suffix</code>. 选用风格附加的提示词
     */
    public void setPromptSuffix(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.media_style.prompt_suffix</code>. 选用风格附加的提示词
     */
    public String getPromptSuffix() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.media_style.enabled</code>. 目录条目是否允许创建新任务
     */
    public void setEnabled(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.media_style.enabled</code>. 目录条目是否允许创建新任务
     */
    public Boolean getEnabled() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.media_style.version</code>. 乐观并发控制版本，更新时递增并校验预期值
     */
    public void setVersion(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.media_style.version</code>. 乐观并发控制版本，更新时递增并校验预期值
     */
    public Long getVersion() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.media_style.builtin_key</code>. 内置风格稳定标识；用户风格为空
     */
    public void setBuiltinKey(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.media_style.builtin_key</code>. 内置风格稳定标识；用户风格为空
     */
    public String getBuiltinKey() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.media_style.thumbnail_bytes</code>. 内置风格缩略图字节
     */
    public void setThumbnailBytes(byte[] value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.media_style.thumbnail_bytes</code>. 内置风格缩略图字节
     */
    public byte[] getThumbnailBytes() {
        return (byte[]) get(7);
    }

    /**
     * Setter for <code>public.media_style.thumbnail_content_type</code>. 风格缩略图
     * MIME 类型
     */
    public void setThumbnailContentType(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.media_style.thumbnail_content_type</code>. 风格缩略图
     * MIME 类型
     */
    public String getThumbnailContentType() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.media_style.created_at</code>. 创建时间（UTC）
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.media_style.created_at</code>. 创建时间（UTC）
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for <code>public.media_style.updated_at</code>. 最后状态或配置更新时间（UTC）
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.media_style.updated_at</code>. 最后状态或配置更新时间（UTC）
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MediaStyleRecord
     */
    public MediaStyleRecord() {
        super(MediaStyle.MEDIA_STYLE);
    }

    /**
     * Create a detached, initialised MediaStyleRecord
     */
    public MediaStyleRecord(UUID id, String name, String category, String promptSuffix, Boolean enabled, Long version, String builtinKey, byte[] thumbnailBytes, String thumbnailContentType, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(MediaStyle.MEDIA_STYLE);

        setId(id);
        setName(name);
        setCategory(category);
        setPromptSuffix(promptSuffix);
        setEnabled(enabled);
        setVersion(version);
        setBuiltinKey(builtinKey);
        setThumbnailBytes(thumbnailBytes);
        setThumbnailContentType(thumbnailContentType);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
