/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables.records;


import dev.agenvas.db.tables.MediaFunctionSetting;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Administrator-selected video processing capabilities, independent of
 * generation defaults
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MediaFunctionSettingRecord extends UpdatableRecordImpl<MediaFunctionSettingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.media_function_setting.operation</code>.
     */
    public void setOperation(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.media_function_setting.operation</code>.
     */
    public String getOperation() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.media_function_setting.capability_id</code>.
     */
    public void setCapabilityId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.media_function_setting.capability_id</code>.
     */
    public UUID getCapabilityId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.media_function_setting.version</code>.
     */
    public void setVersion(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.media_function_setting.version</code>.
     */
    public Long getVersion() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.media_function_setting.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.media_function_setting.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MediaFunctionSettingRecord
     */
    public MediaFunctionSettingRecord() {
        super(MediaFunctionSetting.MEDIA_FUNCTION_SETTING);
    }

    /**
     * Create a detached, initialised MediaFunctionSettingRecord
     */
    public MediaFunctionSettingRecord(String operation, UUID capabilityId, Long version, OffsetDateTime updatedAt) {
        super(MediaFunctionSetting.MEDIA_FUNCTION_SETTING);

        setOperation(operation);
        setCapabilityId(capabilityId);
        setVersion(version);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
