/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables.records;


import dev.agenvas.db.tables.PlanStep;

import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlanStepRecord extends UpdatableRecordImpl<PlanStepRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.plan_step.plan_id</code>.
     */
    public void setPlanId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.plan_step.plan_id</code>.
     */
    public UUID getPlanId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.plan_step.project_id</code>.
     */
    public void setProjectId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.plan_step.project_id</code>.
     */
    public UUID getProjectId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.plan_step.step_key</code>.
     */
    public void setStepKey(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.plan_step.step_key</code>.
     */
    public String getStepKey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.plan_step.ordinal</code>.
     */
    public void setOrdinal(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.plan_step.ordinal</code>.
     */
    public Integer getOrdinal() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.plan_step.kind</code>.
     */
    public void setKind(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.plan_step.kind</code>.
     */
    public String getKind() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.plan_step.shot_artifact_id</code>.
     */
    public void setShotArtifactId(UUID value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.plan_step.shot_artifact_id</code>.
     */
    public UUID getShotArtifactId() {
        return (UUID) get(5);
    }

    /**
     * Setter for <code>public.plan_step.shot_version_id</code>.
     */
    public void setShotVersionId(UUID value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.plan_step.shot_version_id</code>.
     */
    public UUID getShotVersionId() {
        return (UUID) get(6);
    }

    /**
     * Setter for <code>public.plan_step.image_artifact_id</code>.
     */
    public void setImageArtifactId(UUID value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.plan_step.image_artifact_id</code>.
     */
    public UUID getImageArtifactId() {
        return (UUID) get(7);
    }

    /**
     * Setter for <code>public.plan_step.image_version_id</code>.
     */
    public void setImageVersionId(UUID value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.plan_step.image_version_id</code>.
     */
    public UUID getImageVersionId() {
        return (UUID) get(8);
    }

    /**
     * Setter for <code>public.plan_step.output_slot_key</code>.
     */
    public void setOutputSlotKey(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.plan_step.output_slot_key</code>.
     */
    public String getOutputSlotKey() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.plan_step.input_json</code>.
     */
    public void setInputJson(JSONB value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.plan_step.input_json</code>.
     */
    public JSONB getInputJson() {
        return (JSONB) get(10);
    }

    /**
     * Setter for <code>public.plan_step.dependency_keys_json</code>.
     */
    public void setDependencyKeysJson(JSONB value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.plan_step.dependency_keys_json</code>.
     */
    public JSONB getDependencyKeysJson() {
        return (JSONB) get(11);
    }

    /**
     * Setter for <code>public.plan_step.capability_id</code>.
     */
    public void setCapabilityId(UUID value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.plan_step.capability_id</code>.
     */
    public UUID getCapabilityId() {
        return (UUID) get(12);
    }

    /**
     * Setter for <code>public.plan_step.capability_version</code>.
     */
    public void setCapabilityVersion(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.plan_step.capability_version</code>.
     */
    public Integer getCapabilityVersion() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>public.plan_step.connection_id</code>.
     */
    public void setConnectionId(UUID value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.plan_step.connection_id</code>.
     */
    public UUID getConnectionId() {
        return (UUID) get(14);
    }

    /**
     * Setter for <code>public.plan_step.connection_version</code>.
     */
    public void setConnectionVersion(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.plan_step.connection_version</code>.
     */
    public Integer getConnectionVersion() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>public.plan_step.mapping_sha256</code>.
     */
    public void setMappingSha256(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.plan_step.mapping_sha256</code>.
     */
    public String getMappingSha256() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.plan_step.adapter_id</code>.
     */
    public void setAdapterId(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.plan_step.adapter_id</code>.
     */
    public String getAdapterId() {
        return (String) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlanStepRecord
     */
    public PlanStepRecord() {
        super(PlanStep.PLAN_STEP);
    }

    /**
     * Create a detached, initialised PlanStepRecord
     */
    public PlanStepRecord(UUID planId, UUID projectId, String stepKey, Integer ordinal, String kind, UUID shotArtifactId, UUID shotVersionId, UUID imageArtifactId, UUID imageVersionId, String outputSlotKey, JSONB inputJson, JSONB dependencyKeysJson, UUID capabilityId, Integer capabilityVersion, UUID connectionId, Integer connectionVersion, String mappingSha256, String adapterId) {
        super(PlanStep.PLAN_STEP);

        setPlanId(planId);
        setProjectId(projectId);
        setStepKey(stepKey);
        setOrdinal(ordinal);
        setKind(kind);
        setShotArtifactId(shotArtifactId);
        setShotVersionId(shotVersionId);
        setImageArtifactId(imageArtifactId);
        setImageVersionId(imageVersionId);
        setOutputSlotKey(outputSlotKey);
        setInputJson(inputJson);
        setDependencyKeysJson(dependencyKeysJson);
        setCapabilityId(capabilityId);
        setCapabilityVersion(capabilityVersion);
        setConnectionId(connectionId);
        setConnectionVersion(connectionVersion);
        setMappingSha256(mappingSha256);
        setAdapterId(adapterId);
        resetChangedOnNotNull();
    }
}
