/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables.records;


import dev.agenvas.db.tables.ProjectEvent;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Per-project transactional event log and replay outbox ordered by the project
 * counter.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProjectEventRecord extends UpdatableRecordImpl<ProjectEventRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.project_event.project_id</code>.
     */
    public void setProjectId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.project_event.project_id</code>.
     */
    public UUID getProjectId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.project_event.seq</code>. Commit-safe
     * project-local waterline allocated while holding the project row lock.
     */
    public void setSeq(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.project_event.seq</code>. Commit-safe
     * project-local waterline allocated while holding the project row lock.
     */
    public Long getSeq() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.project_event.event_id</code>.
     */
    public void setEventId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.project_event.event_id</code>.
     */
    public UUID getEventId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.project_event.type</code>.
     */
    public void setType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.project_event.type</code>.
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.project_event.schema_version</code>.
     */
    public void setSchemaVersion(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.project_event.schema_version</code>.
     */
    public Integer getSchemaVersion() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.project_event.aggregate_id</code>.
     */
    public void setAggregateId(UUID value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.project_event.aggregate_id</code>.
     */
    public UUID getAggregateId() {
        return (UUID) get(5);
    }

    /**
     * Setter for <code>public.project_event.aggregate_version</code>.
     */
    public void setAggregateVersion(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.project_event.aggregate_version</code>.
     */
    public Long getAggregateVersion() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.project_event.payload_json</code>.
     */
    public void setPayloadJson(JSONB value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.project_event.payload_json</code>.
     */
    public JSONB getPayloadJson() {
        return (JSONB) get(7);
    }

    /**
     * Setter for <code>public.project_event.occurred_at</code>.
     */
    public void setOccurredAt(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.project_event.occurred_at</code>.
     */
    public OffsetDateTime getOccurredAt() {
        return (OffsetDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectEventRecord
     */
    public ProjectEventRecord() {
        super(ProjectEvent.PROJECT_EVENT);
    }

    /**
     * Create a detached, initialised ProjectEventRecord
     */
    public ProjectEventRecord(UUID projectId, Long seq, UUID eventId, String type, Integer schemaVersion, UUID aggregateId, Long aggregateVersion, JSONB payloadJson, OffsetDateTime occurredAt) {
        super(ProjectEvent.PROJECT_EVENT);

        setProjectId(projectId);
        setSeq(seq);
        setEventId(eventId);
        setType(type);
        setSchemaVersion(schemaVersion);
        setAggregateId(aggregateId);
        setAggregateVersion(aggregateVersion);
        setPayloadJson(payloadJson);
        setOccurredAt(occurredAt);
        resetChangedOnNotNull();
    }
}
