/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables.records;


import dev.agenvas.db.tables.SkillPublishOperation;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Durable fenced local archival; no model or Provider execution
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SkillPublishOperationRecord extends UpdatableRecordImpl<SkillPublishOperationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.skill_publish_operation.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.skill_publish_operation.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.skill_publish_operation.owner_id</code>.
     */
    public void setOwnerId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.skill_publish_operation.owner_id</code>.
     */
    public UUID getOwnerId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.skill_publish_operation.skill_id</code>.
     */
    public void setSkillId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.skill_publish_operation.skill_id</code>.
     */
    public UUID getSkillId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.skill_publish_operation.command_key</code>.
     */
    public void setCommandKey(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.skill_publish_operation.command_key</code>.
     */
    public String getCommandKey() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.skill_publish_operation.payload_hash</code>.
     */
    public void setPayloadHash(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.skill_publish_operation.payload_hash</code>.
     */
    public String getPayloadHash() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.skill_publish_operation.input_json</code>.
     */
    public void setInputJson(JSONB value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.skill_publish_operation.input_json</code>.
     */
    public JSONB getInputJson() {
        return (JSONB) get(5);
    }

    /**
     * Setter for <code>public.skill_publish_operation.progress_json</code>.
     */
    public void setProgressJson(JSONB value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.skill_publish_operation.progress_json</code>.
     */
    public JSONB getProgressJson() {
        return (JSONB) get(6);
    }

    /**
     * Setter for <code>public.skill_publish_operation.status</code>.
     */
    public void setStatus(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.skill_publish_operation.status</code>.
     */
    public String getStatus() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.skill_publish_operation.epoch</code>.
     */
    public void setEpoch(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.skill_publish_operation.epoch</code>.
     */
    public Long getEpoch() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.skill_publish_operation.lease_until</code>.
     */
    public void setLeaseUntil(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.skill_publish_operation.lease_until</code>.
     */
    public OffsetDateTime getLeaseUntil() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for <code>public.skill_publish_operation.result_version_id</code>.
     */
    public void setResultVersionId(UUID value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.skill_publish_operation.result_version_id</code>.
     */
    public UUID getResultVersionId() {
        return (UUID) get(10);
    }

    /**
     * Setter for <code>public.skill_publish_operation.error_code</code>.
     */
    public void setErrorCode(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.skill_publish_operation.error_code</code>.
     */
    public String getErrorCode() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.skill_publish_operation.error_detail</code>.
     */
    public void setErrorDetail(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.skill_publish_operation.error_detail</code>.
     */
    public String getErrorDetail() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.skill_publish_operation.pins_cleaned</code>.
     */
    public void setPinsCleaned(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.skill_publish_operation.pins_cleaned</code>.
     */
    public Boolean getPinsCleaned() {
        return (Boolean) get(13);
    }

    /**
     * Setter for <code>public.skill_publish_operation.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.skill_publish_operation.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(14);
    }

    /**
     * Setter for <code>public.skill_publish_operation.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.skill_publish_operation.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SkillPublishOperationRecord
     */
    public SkillPublishOperationRecord() {
        super(SkillPublishOperation.SKILL_PUBLISH_OPERATION);
    }

    /**
     * Create a detached, initialised SkillPublishOperationRecord
     */
    public SkillPublishOperationRecord(UUID id, UUID ownerId, UUID skillId, String commandKey, String payloadHash, JSONB inputJson, JSONB progressJson, String status, Long epoch, OffsetDateTime leaseUntil, UUID resultVersionId, String errorCode, String errorDetail, Boolean pinsCleaned, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(SkillPublishOperation.SKILL_PUBLISH_OPERATION);

        setId(id);
        setOwnerId(ownerId);
        setSkillId(skillId);
        setCommandKey(commandKey);
        setPayloadHash(payloadHash);
        setInputJson(inputJson);
        setProgressJson(progressJson);
        setStatus(status);
        setEpoch(epoch);
        setLeaseUntil(leaseUntil);
        setResultVersionId(resultVersionId);
        setErrorCode(errorCode);
        setErrorDetail(errorDetail);
        setPinsCleaned(pinsCleaned);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
