/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables.records;


import dev.agenvas.db.tables.StorageSettings;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 当前存储配置选择及并发控制版本；已有资产保留原路由
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StorageSettingsRecord extends UpdatableRecordImpl<StorageSettingsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.storage_settings.singleton</code>. 全局存储配置的单例键
     */
    public void setSingleton(Boolean value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.storage_settings.singleton</code>. 全局存储配置的单例键
     */
    public Boolean getSingleton() {
        return (Boolean) get(0);
    }

    /**
     * Setter for <code>public.storage_settings.version</code>.
     * 乐观并发控制版本，更新时递增并校验预期值
     */
    public void setVersion(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.storage_settings.version</code>.
     * 乐观并发控制版本，更新时递增并校验预期值
     */
    public Integer getVersion() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.storage_settings.active_profile_id</code>.
     * 当前写入使用的存储配置；已有资产按原路由读取
     */
    public void setActiveProfileId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.storage_settings.active_profile_id</code>.
     * 当前写入使用的存储配置；已有资产按原路由读取
     */
    public UUID getActiveProfileId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.storage_settings.relay_profile_id</code>.
     * Optional media relay destination; independent of the archive default
     */
    public void setRelayProfileId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.storage_settings.relay_profile_id</code>.
     * Optional media relay destination; independent of the archive default
     */
    public UUID getRelayProfileId() {
        return (UUID) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Boolean> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StorageSettingsRecord
     */
    public StorageSettingsRecord() {
        super(StorageSettings.STORAGE_SETTINGS);
    }

    /**
     * Create a detached, initialised StorageSettingsRecord
     */
    public StorageSettingsRecord(Boolean singleton, Integer version, UUID activeProfileId, UUID relayProfileId) {
        super(StorageSettings.STORAGE_SETTINGS);

        setSingleton(singleton);
        setVersion(version);
        setActiveProfileId(activeProfileId);
        setRelayProfileId(relayProfileId);
        resetChangedOnNotNull();
    }
}
