/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables.records;


import dev.agenvas.db.tables.StorageSettings;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StorageSettingsRecord extends UpdatableRecordImpl<StorageSettingsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.storage_settings.singleton</code>.
     */
    public void setSingleton(Boolean value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.storage_settings.singleton</code>.
     */
    public Boolean getSingleton() {
        return (Boolean) get(0);
    }

    /**
     * Setter for <code>public.storage_settings.version</code>.
     */
    public void setVersion(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.storage_settings.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.storage_settings.active_profile_id</code>.
     */
    public void setActiveProfileId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.storage_settings.active_profile_id</code>.
     */
    public UUID getActiveProfileId() {
        return (UUID) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Boolean> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StorageSettingsRecord
     */
    public StorageSettingsRecord() {
        super(StorageSettings.STORAGE_SETTINGS);
    }

    /**
     * Create a detached, initialised StorageSettingsRecord
     */
    public StorageSettingsRecord(Boolean singleton, Integer version, UUID activeProfileId) {
        super(StorageSettings.STORAGE_SETTINGS);

        setSingleton(singleton);
        setVersion(version);
        setActiveProfileId(activeProfileId);
        resetChangedOnNotNull();
    }
}
