/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables.records;


import dev.agenvas.db.tables.TaskArtifactTarget;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Immutable content selection precondition captured when a generation Task is
 * created.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TaskArtifactTargetRecord extends UpdatableRecordImpl<TaskArtifactTargetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.task_artifact_target.task_id</code>.
     */
    public void setTaskId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.task_artifact_target.task_id</code>.
     */
    public UUID getTaskId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.task_artifact_target.project_id</code>.
     */
    public void setProjectId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.task_artifact_target.project_id</code>.
     */
    public UUID getProjectId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.task_artifact_target.artifact_id</code>.
     */
    public void setArtifactId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.task_artifact_target.artifact_id</code>.
     */
    public UUID getArtifactId() {
        return (UUID) get(2);
    }

    /**
     * Setter for
     * <code>public.task_artifact_target.expected_current_version_id</code>.
     */
    public void setExpectedCurrentVersionId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>public.task_artifact_target.expected_current_version_id</code>.
     */
    public UUID getExpectedCurrentVersionId() {
        return (UUID) get(3);
    }

    /**
     * Setter for
     * <code>public.task_artifact_target.expected_artifact_version</code>.
     */
    public void setExpectedArtifactVersion(Long value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>public.task_artifact_target.expected_artifact_version</code>.
     */
    public Long getExpectedArtifactVersion() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.task_artifact_target.output_slot_key</code>. A
     * named output in an approved plan; no Artifact identity exists until the
     * result arrives.
     */
    public void setOutputSlotKey(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.task_artifact_target.output_slot_key</code>. A
     * named output in an approved plan; no Artifact identity exists until the
     * result arrives.
     */
    public String getOutputSlotKey() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.task_artifact_target.canvas_item_id</code>.
     */
    public void setCanvasItemId(UUID value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.task_artifact_target.canvas_item_id</code>.
     */
    public UUID getCanvasItemId() {
        return (UUID) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TaskArtifactTargetRecord
     */
    public TaskArtifactTargetRecord() {
        super(TaskArtifactTarget.TASK_ARTIFACT_TARGET);
    }

    /**
     * Create a detached, initialised TaskArtifactTargetRecord
     */
    public TaskArtifactTargetRecord(UUID taskId, UUID projectId, UUID artifactId, UUID expectedCurrentVersionId, Long expectedArtifactVersion, String outputSlotKey, UUID canvasItemId) {
        super(TaskArtifactTarget.TASK_ARTIFACT_TARGET);

        setTaskId(taskId);
        setProjectId(projectId);
        setArtifactId(artifactId);
        setExpectedCurrentVersionId(expectedCurrentVersionId);
        setExpectedArtifactVersion(expectedArtifactVersion);
        setOutputSlotKey(outputSlotKey);
        setCanvasItemId(canvasItemId);
        resetChangedOnNotNull();
    }
}
