/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables.records;


import dev.agenvas.db.tables.TaskArtifactTarget;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 任务固定目标与受理时的版本选择；结果不能覆盖并发用户选择
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TaskArtifactTargetRecord extends UpdatableRecordImpl<TaskArtifactTargetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.task_artifact_target.task_id</code>. 持久任务身份
     */
    public void setTaskId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.task_artifact_target.task_id</code>. 持久任务身份
     */
    public UUID getTaskId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.task_artifact_target.project_id</code>.
     * 所属项目及授权作用域
     */
    public void setProjectId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.task_artifact_target.project_id</code>.
     * 所属项目及授权作用域
     */
    public UUID getProjectId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.task_artifact_target.artifact_id</code>. 业务产物身份
     */
    public void setArtifactId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.task_artifact_target.artifact_id</code>. 业务产物身份
     */
    public UUID getArtifactId() {
        return (UUID) get(2);
    }

    /**
     * Setter for
     * <code>public.task_artifact_target.expected_current_version_id</code>.
     * 受理时的产物当前版本，结果提交时进行 CAS 校验
     */
    public void setExpectedCurrentVersionId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>public.task_artifact_target.expected_current_version_id</code>.
     * 受理时的产物当前版本，结果提交时进行 CAS 校验
     */
    public UUID getExpectedCurrentVersionId() {
        return (UUID) get(3);
    }

    /**
     * Setter for
     * <code>public.task_artifact_target.expected_artifact_version</code>.
     * 受理时的产物并发控制版本
     */
    public void setExpectedArtifactVersion(Long value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>public.task_artifact_target.expected_artifact_version</code>.
     * 受理时的产物并发控制版本
     */
    public Long getExpectedArtifactVersion() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.task_artifact_target.canvas_item_id</code>.
     * 固定的目标或上下文画布卡片
     */
    public void setCanvasItemId(UUID value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.task_artifact_target.canvas_item_id</code>.
     * 固定的目标或上下文画布卡片
     */
    public UUID getCanvasItemId() {
        return (UUID) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TaskArtifactTargetRecord
     */
    public TaskArtifactTargetRecord() {
        super(TaskArtifactTarget.TASK_ARTIFACT_TARGET);
    }

    /**
     * Create a detached, initialised TaskArtifactTargetRecord
     */
    public TaskArtifactTargetRecord(UUID taskId, UUID projectId, UUID artifactId, UUID expectedCurrentVersionId, Long expectedArtifactVersion, UUID canvasItemId) {
        super(TaskArtifactTarget.TASK_ARTIFACT_TARGET);

        setTaskId(taskId);
        setProjectId(projectId);
        setArtifactId(artifactId);
        setExpectedCurrentVersionId(expectedCurrentVersionId);
        setExpectedArtifactVersion(expectedArtifactVersion);
        setCanvasItemId(canvasItemId);
        resetChangedOnNotNull();
    }
}
