/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables.records;


import dev.agenvas.db.tables.ToolExecution;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * One caller-driven tool invocation. Reservation, business mutation and result
 * commit together.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ToolExecutionRecord extends UpdatableRecordImpl<ToolExecutionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tool_execution.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tool_execution.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.tool_execution.project_id</code>.
     */
    public void setProjectId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tool_execution.project_id</code>.
     */
    public UUID getProjectId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.tool_execution.run_id</code>.
     */
    public void setRunId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tool_execution.run_id</code>.
     */
    public UUID getRunId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.tool_execution.step_index</code>.
     */
    public void setStepIndex(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tool_execution.step_index</code>.
     */
    public Integer getStepIndex() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.tool_execution.tool_call_id</code>.
     */
    public void setToolCallId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tool_execution.tool_call_id</code>.
     */
    public String getToolCallId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.tool_execution.tool_name</code>.
     */
    public void setToolName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.tool_execution.tool_name</code>.
     */
    public String getToolName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.tool_execution.argument_hash</code>.
     */
    public void setArgumentHash(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.tool_execution.argument_hash</code>.
     */
    public String getArgumentHash() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.tool_execution.status</code>.
     */
    public void setStatus(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.tool_execution.status</code>.
     */
    public String getStatus() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.tool_execution.result_json</code>.
     */
    public void setResultJson(JSONB value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.tool_execution.result_json</code>.
     */
    public JSONB getResultJson() {
        return (JSONB) get(8);
    }

    /**
     * Setter for <code>public.tool_execution.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.tool_execution.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for <code>public.tool_execution.completed_at</code>.
     */
    public void setCompletedAt(OffsetDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.tool_execution.completed_at</code>.
     */
    public OffsetDateTime getCompletedAt() {
        return (OffsetDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ToolExecutionRecord
     */
    public ToolExecutionRecord() {
        super(ToolExecution.TOOL_EXECUTION);
    }

    /**
     * Create a detached, initialised ToolExecutionRecord
     */
    public ToolExecutionRecord(UUID id, UUID projectId, UUID runId, Integer stepIndex, String toolCallId, String toolName, String argumentHash, String status, JSONB resultJson, OffsetDateTime createdAt, OffsetDateTime completedAt) {
        super(ToolExecution.TOOL_EXECUTION);

        setId(id);
        setProjectId(projectId);
        setRunId(runId);
        setStepIndex(stepIndex);
        setToolCallId(toolCallId);
        setToolName(toolName);
        setArgumentHash(argumentHash);
        setStatus(status);
        setResultJson(resultJson);
        setCreatedAt(createdAt);
        setCompletedAt(completedAt);
        resetChangedOnNotNull();
    }
}
