/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables;


import dev.agenvas.db.Indexes;
import dev.agenvas.db.Keys;
import dev.agenvas.db.Public;
import dev.agenvas.db.tables.AgentBinding.AgentBindingPath;
import dev.agenvas.db.tables.AgentConversation.AgentConversationPath;
import dev.agenvas.db.tables.AgentRun.AgentRunPath;
import dev.agenvas.db.tables.CanvasItem.CanvasItemPath;
import dev.agenvas.db.tables.Project.ProjectPath;
import dev.agenvas.db.tables.records.AgentInstanceRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Persistent card configuration only; no thread, request principal, or mutable
 * run context.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AgentInstance extends TableImpl<AgentInstanceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.agent_instance</code>
     */
    public static final AgentInstance AGENT_INSTANCE = new AgentInstance();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AgentInstanceRecord> getRecordType() {
        return AgentInstanceRecord.class;
    }

    /**
     * The column <code>public.agent_instance.id</code>.
     */
    public final TableField<AgentInstanceRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.agent_instance.project_id</code>.
     */
    public final TableField<AgentInstanceRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.agent_instance.profile_key</code>.
     */
    public final TableField<AgentInstanceRecord, String> PROFILE_KEY = createField(DSL.name("profile_key"), SQLDataType.VARCHAR(80).nullable(false), this, "");

    /**
     * The column <code>public.agent_instance.profile_version</code>.
     */
    public final TableField<AgentInstanceRecord, Integer> PROFILE_VERSION = createField(DSL.name("profile_version"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.agent_instance.name</code>.
     */
    public final TableField<AgentInstanceRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(120).nullable(false), this, "");

    /**
     * The column <code>public.agent_instance.instruction</code>.
     */
    public final TableField<AgentInstanceRecord, String> INSTRUCTION = createField(DSL.name("instruction"), SQLDataType.VARCHAR(8000).nullable(false), this, "");

    /**
     * The column <code>public.agent_instance.output_group_id</code>.
     */
    public final TableField<AgentInstanceRecord, UUID> OUTPUT_GROUP_ID = createField(DSL.name("output_group_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.agent_instance.version</code>.
     */
    public final TableField<AgentInstanceRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.agent_instance.created_at</code>.
     */
    public final TableField<AgentInstanceRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.agent_instance.updated_at</code>.
     */
    public final TableField<AgentInstanceRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.agent_instance.current_conversation_id</code>.
     * Selected conversation only; switching it never cancels or reassigns an
     * active Run.
     */
    public final TableField<AgentInstanceRecord, UUID> CURRENT_CONVERSATION_ID = createField(DSL.name("current_conversation_id"), SQLDataType.UUID, this, "Selected conversation only; switching it never cancels or reassigns an active Run.");

    private AgentInstance(Name alias, Table<AgentInstanceRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AgentInstance(Name alias, Table<AgentInstanceRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Persistent card configuration only; no thread, request principal, or mutable run context."), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.agent_instance</code> table reference
     */
    public AgentInstance(String alias) {
        this(DSL.name(alias), AGENT_INSTANCE);
    }

    /**
     * Create an aliased <code>public.agent_instance</code> table reference
     */
    public AgentInstance(Name alias) {
        this(alias, AGENT_INSTANCE);
    }

    /**
     * Create a <code>public.agent_instance</code> table reference
     */
    public AgentInstance() {
        this(DSL.name("agent_instance"), null);
    }

    public <O extends Record> AgentInstance(Table<O> path, ForeignKey<O, AgentInstanceRecord> childPath, InverseForeignKey<O, AgentInstanceRecord> parentPath) {
        super(path, childPath, parentPath, AGENT_INSTANCE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AgentInstancePath extends AgentInstance implements Path<AgentInstanceRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AgentInstancePath(Table<O> path, ForeignKey<O, AgentInstanceRecord> childPath, InverseForeignKey<O, AgentInstanceRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AgentInstancePath(Name alias, Table<AgentInstanceRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AgentInstancePath as(String alias) {
            return new AgentInstancePath(DSL.name(alias), this);
        }

        @Override
        public AgentInstancePath as(Name alias) {
            return new AgentInstancePath(alias, this);
        }

        @Override
        public AgentInstancePath as(Table<?> alias) {
            return new AgentInstancePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IX_AGENT_INSTANCE_PROJECT);
    }

    @Override
    public UniqueKey<AgentInstanceRecord> getPrimaryKey() {
        return Keys.AGENT_INSTANCE_PKEY;
    }

    @Override
    public List<UniqueKey<AgentInstanceRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UQ_AGENT_INSTANCE_PROJECT_ID);
    }

    @Override
    public List<ForeignKey<AgentInstanceRecord, ?>> getReferences() {
        return Arrays.asList(Keys.AGENT_INSTANCE__FK_AGENT_CURRENT_CONVERSATION, Keys.AGENT_INSTANCE__FK_AGENT_INSTANCE_PROJECT);
    }

    private transient AgentConversationPath _agentConversation;

    /**
     * Get the implicit join path to the <code>public.agent_conversation</code>
     * table.
     */
    public AgentConversationPath agentConversation() {
        if (_agentConversation == null)
            _agentConversation = new AgentConversationPath(this, Keys.AGENT_INSTANCE__FK_AGENT_CURRENT_CONVERSATION, null);

        return _agentConversation;
    }

    private transient ProjectPath _project;

    /**
     * Get the implicit join path to the <code>public.project</code> table.
     */
    public ProjectPath project() {
        if (_project == null)
            _project = new ProjectPath(this, Keys.AGENT_INSTANCE__FK_AGENT_INSTANCE_PROJECT, null);

        return _project;
    }

    private transient AgentBindingPath _agentBinding;

    /**
     * Get the implicit to-many join path to the
     * <code>public.agent_binding</code> table
     */
    public AgentBindingPath agentBinding() {
        if (_agentBinding == null)
            _agentBinding = new AgentBindingPath(this, null, Keys.AGENT_BINDING__FK_AGENT_BINDING_AGENT.getInverseKey());

        return _agentBinding;
    }

    private transient AgentRunPath _agentRun;

    /**
     * Get the implicit to-many join path to the <code>public.agent_run</code>
     * table
     */
    public AgentRunPath agentRun() {
        if (_agentRun == null)
            _agentRun = new AgentRunPath(this, null, Keys.AGENT_RUN__FK_AGENT_RUN_AGENT.getInverseKey());

        return _agentRun;
    }

    private transient CanvasItemPath _canvasItem;

    /**
     * Get the implicit to-many join path to the <code>public.canvas_item</code>
     * table
     */
    public CanvasItemPath canvasItem() {
        if (_canvasItem == null)
            _canvasItem = new CanvasItemPath(this, null, Keys.CANVAS_ITEM__FK_CANVAS_ITEM_AGENT.getInverseKey());

        return _canvasItem;
    }

    @Override
    public List<Check<AgentInstanceRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("ck_agent_instruction_not_blank"), "((length(btrim((instruction)::text)) > 0))", true),
            Internal.createCheck(this, DSL.name("ck_agent_name_not_blank"), "((length(btrim((name)::text)) > 0))", true),
            Internal.createCheck(this, DSL.name("ck_agent_profile_key_not_blank"), "((length(btrim((profile_key)::text)) > 0))", true),
            Internal.createCheck(this, DSL.name("ck_agent_profile_version_positive"), "((profile_version > 0))", true),
            Internal.createCheck(this, DSL.name("ck_agent_version_non_negative"), "((version >= 0))", true)
        );
    }

    @Override
    public AgentInstance as(String alias) {
        return new AgentInstance(DSL.name(alias), this);
    }

    @Override
    public AgentInstance as(Name alias) {
        return new AgentInstance(alias, this);
    }

    @Override
    public AgentInstance as(Table<?> alias) {
        return new AgentInstance(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AgentInstance rename(String name) {
        return new AgentInstance(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AgentInstance rename(Name name) {
        return new AgentInstance(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AgentInstance rename(Table<?> name) {
        return new AgentInstance(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentInstance where(Condition condition) {
        return new AgentInstance(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentInstance where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentInstance where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentInstance where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentInstance where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentInstance where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentInstance where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentInstance where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentInstance whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentInstance whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
