/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables;


import dev.agenvas.db.Indexes;
import dev.agenvas.db.Keys;
import dev.agenvas.db.Public;
import dev.agenvas.db.tables.AgentConversation.AgentConversationPath;
import dev.agenvas.db.tables.AgentInstance.AgentInstancePath;
import dev.agenvas.db.tables.AppUser.AppUserPath;
import dev.agenvas.db.tables.CallLog.CallLogPath;
import dev.agenvas.db.tables.LlmTurn.LlmTurnPath;
import dev.agenvas.db.tables.Project.ProjectPath;
import dev.agenvas.db.tables.Task.TaskPath;
import dev.agenvas.db.tables.ToolExecution.ToolExecutionPath;
import dev.agenvas.db.tables.UsageLedger.UsageLedgerPath;
import dev.agenvas.db.tables.records.AgentRunRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Persistent execution lifecycle with immutable input and policy snapshots.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AgentRun extends TableImpl<AgentRunRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.agent_run</code>
     */
    public static final AgentRun AGENT_RUN = new AgentRun();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AgentRunRecord> getRecordType() {
        return AgentRunRecord.class;
    }

    /**
     * The column <code>public.agent_run.id</code>.
     */
    public final TableField<AgentRunRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.agent_run.project_id</code>.
     */
    public final TableField<AgentRunRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.agent_run.agent_instance_id</code>.
     */
    public final TableField<AgentRunRecord, UUID> AGENT_INSTANCE_ID = createField(DSL.name("agent_instance_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.agent_run.user_id</code>.
     */
    public final TableField<AgentRunRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.agent_run.status</code>.
     */
    public final TableField<AgentRunRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>public.agent_run.instruction</code>.
     */
    public final TableField<AgentRunRecord, String> INSTRUCTION = createField(DSL.name("instruction"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.agent_run.context_snapshot_json</code>.
     */
    public final TableField<AgentRunRecord, JSONB> CONTEXT_SNAPSHOT_JSON = createField(DSL.name("context_snapshot_json"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>public.agent_run.policy_snapshot_json</code>.
     */
    public final TableField<AgentRunRecord, JSONB> POLICY_SNAPSHOT_JSON = createField(DSL.name("policy_snapshot_json"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>public.agent_run.profile_version</code>.
     */
    public final TableField<AgentRunRecord, Integer> PROFILE_VERSION = createField(DSL.name("profile_version"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.agent_run.next_step_index</code>.
     */
    public final TableField<AgentRunRecord, Integer> NEXT_STEP_INDEX = createField(DSL.name("next_step_index"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.agent_run.version</code>.
     */
    public final TableField<AgentRunRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.agent_run.created_at</code>.
     */
    public final TableField<AgentRunRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.agent_run.updated_at</code>.
     */
    public final TableField<AgentRunRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.agent_run.completed_at</code>.
     */
    public final TableField<AgentRunRecord, OffsetDateTime> COMPLETED_AT = createField(DSL.name("completed_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.agent_run.conversation_id</code>.
     */
    public final TableField<AgentRunRecord, UUID> CONVERSATION_ID = createField(DSL.name("conversation_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.agent_run.conversation_turn</code>.
     */
    public final TableField<AgentRunRecord, Long> CONVERSATION_TURN = createField(DSL.name("conversation_turn"), SQLDataType.BIGINT.nullable(false), this, "");

    private AgentRun(Name alias, Table<AgentRunRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AgentRun(Name alias, Table<AgentRunRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Persistent execution lifecycle with immutable input and policy snapshots."), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.agent_run</code> table reference
     */
    public AgentRun(String alias) {
        this(DSL.name(alias), AGENT_RUN);
    }

    /**
     * Create an aliased <code>public.agent_run</code> table reference
     */
    public AgentRun(Name alias) {
        this(alias, AGENT_RUN);
    }

    /**
     * Create a <code>public.agent_run</code> table reference
     */
    public AgentRun() {
        this(DSL.name("agent_run"), null);
    }

    public <O extends Record> AgentRun(Table<O> path, ForeignKey<O, AgentRunRecord> childPath, InverseForeignKey<O, AgentRunRecord> parentPath) {
        super(path, childPath, parentPath, AGENT_RUN);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AgentRunPath extends AgentRun implements Path<AgentRunRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AgentRunPath(Table<O> path, ForeignKey<O, AgentRunRecord> childPath, InverseForeignKey<O, AgentRunRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AgentRunPath(Name alias, Table<AgentRunRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AgentRunPath as(String alias) {
            return new AgentRunPath(DSL.name(alias), this);
        }

        @Override
        public AgentRunPath as(Name alias) {
            return new AgentRunPath(alias, this);
        }

        @Override
        public AgentRunPath as(Table<?> alias) {
            return new AgentRunPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IX_AGENT_RUN_PROJECT_CREATED, Indexes.IX_AGENT_RUN_STATUS);
    }

    @Override
    public UniqueKey<AgentRunRecord> getPrimaryKey() {
        return Keys.AGENT_RUN_PKEY;
    }

    @Override
    public List<UniqueKey<AgentRunRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UQ_AGENT_RUN_PROJECT_ID, Keys.UQ_RUN_CONVERSATION_TURN);
    }

    @Override
    public List<ForeignKey<AgentRunRecord, ?>> getReferences() {
        return Arrays.asList(Keys.AGENT_RUN__FK_AGENT_RUN_AGENT, Keys.AGENT_RUN__FK_AGENT_RUN_PROJECT, Keys.AGENT_RUN__FK_AGENT_RUN_USER, Keys.AGENT_RUN__FK_RUN_CONVERSATION);
    }

    private transient AgentInstancePath _agentInstance;

    /**
     * Get the implicit join path to the <code>public.agent_instance</code>
     * table.
     */
    public AgentInstancePath agentInstance() {
        if (_agentInstance == null)
            _agentInstance = new AgentInstancePath(this, Keys.AGENT_RUN__FK_AGENT_RUN_AGENT, null);

        return _agentInstance;
    }

    private transient ProjectPath _project;

    /**
     * Get the implicit join path to the <code>public.project</code> table.
     */
    public ProjectPath project() {
        if (_project == null)
            _project = new ProjectPath(this, Keys.AGENT_RUN__FK_AGENT_RUN_PROJECT, null);

        return _project;
    }

    private transient AppUserPath _appUser;

    /**
     * Get the implicit join path to the <code>public.app_user</code> table.
     */
    public AppUserPath appUser() {
        if (_appUser == null)
            _appUser = new AppUserPath(this, Keys.AGENT_RUN__FK_AGENT_RUN_USER, null);

        return _appUser;
    }

    private transient AgentConversationPath _agentConversation;

    /**
     * Get the implicit join path to the <code>public.agent_conversation</code>
     * table.
     */
    public AgentConversationPath agentConversation() {
        if (_agentConversation == null)
            _agentConversation = new AgentConversationPath(this, Keys.AGENT_RUN__FK_RUN_CONVERSATION, null);

        return _agentConversation;
    }

    private transient CallLogPath _callLog;

    /**
     * Get the implicit to-many join path to the <code>public.call_log</code>
     * table
     */
    public CallLogPath callLog() {
        if (_callLog == null)
            _callLog = new CallLogPath(this, null, Keys.CALL_LOG__CALL_LOG_PROJECT_ID_RUN_ID_FKEY.getInverseKey());

        return _callLog;
    }

    private transient LlmTurnPath _llmTurn;

    /**
     * Get the implicit to-many join path to the <code>public.llm_turn</code>
     * table
     */
    public LlmTurnPath llmTurn() {
        if (_llmTurn == null)
            _llmTurn = new LlmTurnPath(this, null, Keys.LLM_TURN__FK_LLM_TURN_RUN.getInverseKey());

        return _llmTurn;
    }

    private transient TaskPath _task;

    /**
     * Get the implicit to-many join path to the <code>public.task</code> table
     */
    public TaskPath task() {
        if (_task == null)
            _task = new TaskPath(this, null, Keys.TASK__FK_TASK_RUN.getInverseKey());

        return _task;
    }

    private transient ToolExecutionPath _toolExecution;

    /**
     * Get the implicit to-many join path to the
     * <code>public.tool_execution</code> table
     */
    public ToolExecutionPath toolExecution() {
        if (_toolExecution == null)
            _toolExecution = new ToolExecutionPath(this, null, Keys.TOOL_EXECUTION__FK_TOOL_EXECUTION_RUN.getInverseKey());

        return _toolExecution;
    }

    private transient UsageLedgerPath _usageLedger;

    /**
     * Get the implicit to-many join path to the
     * <code>public.usage_ledger</code> table
     */
    public UsageLedgerPath usageLedger() {
        if (_usageLedger == null)
            _usageLedger = new UsageLedgerPath(this, null, Keys.USAGE_LEDGER__FK_USAGE_RUN_PROJECT.getInverseKey());

        return _usageLedger;
    }

    @Override
    public List<Check<AgentRunRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("ck_agent_run_completion"), "(((((status)::text = ANY ((ARRAY['CANCELED'::character varying, 'FAILED'::character varying, 'SUCCEEDED'::character varying])::text[])) AND (completed_at IS NOT NULL)) OR (((status)::text <> ALL ((ARRAY['CANCELED'::character varying, 'FAILED'::character varying, 'SUCCEEDED'::character varying])::text[])) AND (completed_at IS NULL))))", true),
            Internal.createCheck(this, DSL.name("ck_agent_run_instruction_not_blank"), "((length(btrim(instruction)) > 0))", true),
            Internal.createCheck(this, DSL.name("ck_agent_run_next_step_non_negative"), "((next_step_index >= 0))", true),
            Internal.createCheck(this, DSL.name("ck_agent_run_profile_version_positive"), "((profile_version > 0))", true),
            Internal.createCheck(this, DSL.name("ck_agent_run_status"), "(((status)::text = ANY ((ARRAY['QUEUED'::character varying, 'RUNNING'::character varying, 'WAITING_TASKS'::character varying, 'BLOCKED'::character varying, 'CANCEL_REQUESTED'::character varying, 'CANCELED'::character varying, 'FAILED'::character varying, 'SUCCEEDED'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("ck_agent_run_version_non_negative"), "((version >= 0))", true),
            Internal.createCheck(this, DSL.name("ck_run_conversation_turn"), "((conversation_turn > 0))", true)
        );
    }

    @Override
    public AgentRun as(String alias) {
        return new AgentRun(DSL.name(alias), this);
    }

    @Override
    public AgentRun as(Name alias) {
        return new AgentRun(alias, this);
    }

    @Override
    public AgentRun as(Table<?> alias) {
        return new AgentRun(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AgentRun rename(String name) {
        return new AgentRun(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AgentRun rename(Name name) {
        return new AgentRun(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AgentRun rename(Table<?> name) {
        return new AgentRun(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentRun where(Condition condition) {
        return new AgentRun(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentRun where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentRun where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentRun where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentRun where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentRun where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentRun where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentRun where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentRun whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentRun whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
