/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables;


import dev.agenvas.db.Indexes;
import dev.agenvas.db.Keys;
import dev.agenvas.db.Public;
import dev.agenvas.db.tables.AgentBinding.AgentBindingPath;
import dev.agenvas.db.tables.Artifact.ArtifactPath;
import dev.agenvas.db.tables.ArtifactVersionReference.ArtifactVersionReferencePath;
import dev.agenvas.db.tables.MediaDraft.MediaDraftPath;
import dev.agenvas.db.tables.PlanStep.PlanStepPath;
import dev.agenvas.db.tables.ShotDurationUpgrade.ShotDurationUpgradePath;
import dev.agenvas.db.tables.ShotKeyframeSelection.ShotKeyframeSelectionPath;
import dev.agenvas.db.tables.TaskArtifactTarget.TaskArtifactTargetPath;
import dev.agenvas.db.tables.records.ArtifactVersionRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Immutable content revisions. Selection changes update
 * artifact.current_version_id only.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ArtifactVersion extends TableImpl<ArtifactVersionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.artifact_version</code>
     */
    public static final ArtifactVersion ARTIFACT_VERSION = new ArtifactVersion();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ArtifactVersionRecord> getRecordType() {
        return ArtifactVersionRecord.class;
    }

    /**
     * The column <code>public.artifact_version.id</code>.
     */
    public final TableField<ArtifactVersionRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.artifact_version.project_id</code>.
     */
    public final TableField<ArtifactVersionRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.artifact_version.artifact_id</code>.
     */
    public final TableField<ArtifactVersionRecord, UUID> ARTIFACT_ID = createField(DSL.name("artifact_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.artifact_version.version_no</code>.
     */
    public final TableField<ArtifactVersionRecord, Integer> VERSION_NO = createField(DSL.name("version_no"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.artifact_version.schema_version</code>.
     */
    public final TableField<ArtifactVersionRecord, Integer> SCHEMA_VERSION = createField(DSL.name("schema_version"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.artifact_version.content_json</code>.
     */
    public final TableField<ArtifactVersionRecord, JSONB> CONTENT_JSON = createField(DSL.name("content_json"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>public.artifact_version.input_refs_json</code>.
     */
    public final TableField<ArtifactVersionRecord, JSONB> INPUT_REFS_JSON = createField(DSL.name("input_refs_json"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>public.artifact_version.created_by_kind</code>.
     */
    public final TableField<ArtifactVersionRecord, String> CREATED_BY_KIND = createField(DSL.name("created_by_kind"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>public.artifact_version.run_id</code>.
     */
    public final TableField<ArtifactVersionRecord, UUID> RUN_ID = createField(DSL.name("run_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.artifact_version.created_at</code>.
     */
    public final TableField<ArtifactVersionRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    private ArtifactVersion(Name alias, Table<ArtifactVersionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ArtifactVersion(Name alias, Table<ArtifactVersionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Immutable content revisions. Selection changes update artifact.current_version_id only."), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.artifact_version</code> table reference
     */
    public ArtifactVersion(String alias) {
        this(DSL.name(alias), ARTIFACT_VERSION);
    }

    /**
     * Create an aliased <code>public.artifact_version</code> table reference
     */
    public ArtifactVersion(Name alias) {
        this(alias, ARTIFACT_VERSION);
    }

    /**
     * Create a <code>public.artifact_version</code> table reference
     */
    public ArtifactVersion() {
        this(DSL.name("artifact_version"), null);
    }

    public <O extends Record> ArtifactVersion(Table<O> path, ForeignKey<O, ArtifactVersionRecord> childPath, InverseForeignKey<O, ArtifactVersionRecord> parentPath) {
        super(path, childPath, parentPath, ARTIFACT_VERSION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ArtifactVersionPath extends ArtifactVersion implements Path<ArtifactVersionRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ArtifactVersionPath(Table<O> path, ForeignKey<O, ArtifactVersionRecord> childPath, InverseForeignKey<O, ArtifactVersionRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ArtifactVersionPath(Name alias, Table<ArtifactVersionRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ArtifactVersionPath as(String alias) {
            return new ArtifactVersionPath(DSL.name(alias), this);
        }

        @Override
        public ArtifactVersionPath as(Name alias) {
            return new ArtifactVersionPath(alias, this);
        }

        @Override
        public ArtifactVersionPath as(Table<?> alias) {
            return new ArtifactVersionPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IX_ARTIFACT_VERSION_HISTORY);
    }

    @Override
    public UniqueKey<ArtifactVersionRecord> getPrimaryKey() {
        return Keys.ARTIFACT_VERSION_PKEY;
    }

    @Override
    public List<UniqueKey<ArtifactVersionRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UQ_ARTIFACT_VERSION_ARTIFACT_ID, Keys.UQ_ARTIFACT_VERSION_NUMBER, Keys.UQ_ARTIFACT_VERSION_PROJECT_ARTIFACT_ID, Keys.UQ_ARTIFACT_VERSION_PROJECT_ID);
    }

    @Override
    public List<ForeignKey<ArtifactVersionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ARTIFACT_VERSION__FK_ARTIFACT_VERSION_ARTIFACT);
    }

    private transient ArtifactPath _artifact;

    /**
     * Get the implicit join path to the <code>public.artifact</code> table.
     */
    public ArtifactPath artifact() {
        if (_artifact == null)
            _artifact = new ArtifactPath(this, Keys.ARTIFACT_VERSION__FK_ARTIFACT_VERSION_ARTIFACT, null);

        return _artifact;
    }

    private transient AgentBindingPath _agentBinding;

    /**
     * Get the implicit to-many join path to the
     * <code>public.agent_binding</code> table
     */
    public AgentBindingPath agentBinding() {
        if (_agentBinding == null)
            _agentBinding = new AgentBindingPath(this, null, Keys.AGENT_BINDING__FK_AGENT_BINDING_VERSION.getInverseKey());

        return _agentBinding;
    }

    private transient ArtifactVersionReferencePath _fkArtifactReferenceSource;

    /**
     * Get the implicit to-many join path to the
     * <code>public.artifact_version_reference</code> table, via the
     * <code>fk_artifact_reference_source</code> key
     */
    public ArtifactVersionReferencePath fkArtifactReferenceSource() {
        if (_fkArtifactReferenceSource == null)
            _fkArtifactReferenceSource = new ArtifactVersionReferencePath(this, null, Keys.ARTIFACT_VERSION_REFERENCE__FK_ARTIFACT_REFERENCE_SOURCE.getInverseKey());

        return _fkArtifactReferenceSource;
    }

    private transient ArtifactVersionReferencePath _fkArtifactReferenceTarget;

    /**
     * Get the implicit to-many join path to the
     * <code>public.artifact_version_reference</code> table, via the
     * <code>fk_artifact_reference_target</code> key
     */
    public ArtifactVersionReferencePath fkArtifactReferenceTarget() {
        if (_fkArtifactReferenceTarget == null)
            _fkArtifactReferenceTarget = new ArtifactVersionReferencePath(this, null, Keys.ARTIFACT_VERSION_REFERENCE__FK_ARTIFACT_REFERENCE_TARGET.getInverseKey());

        return _fkArtifactReferenceTarget;
    }

    private transient ShotKeyframeSelectionPath _fkKeyframeImageVersion;

    /**
     * Get the implicit to-many join path to the
     * <code>public.shot_keyframe_selection</code> table, via the
     * <code>fk_keyframe_image_version</code> key
     */
    public ShotKeyframeSelectionPath fkKeyframeImageVersion() {
        if (_fkKeyframeImageVersion == null)
            _fkKeyframeImageVersion = new ShotKeyframeSelectionPath(this, null, Keys.SHOT_KEYFRAME_SELECTION__FK_KEYFRAME_IMAGE_VERSION.getInverseKey());

        return _fkKeyframeImageVersion;
    }

    private transient ShotKeyframeSelectionPath _fkKeyframeShotVersion;

    /**
     * Get the implicit to-many join path to the
     * <code>public.shot_keyframe_selection</code> table, via the
     * <code>fk_keyframe_shot_version</code> key
     */
    public ShotKeyframeSelectionPath fkKeyframeShotVersion() {
        if (_fkKeyframeShotVersion == null)
            _fkKeyframeShotVersion = new ShotKeyframeSelectionPath(this, null, Keys.SHOT_KEYFRAME_SELECTION__FK_KEYFRAME_SHOT_VERSION.getInverseKey());

        return _fkKeyframeShotVersion;
    }

    private transient MediaDraftPath _mediaDraft;

    /**
     * Get the implicit to-many join path to the <code>public.media_draft</code>
     * table
     */
    public MediaDraftPath mediaDraft() {
        if (_mediaDraft == null)
            _mediaDraft = new MediaDraftPath(this, null, Keys.MEDIA_DRAFT__FK_MEDIA_DRAFT_INPUT.getInverseKey());

        return _mediaDraft;
    }

    private transient PlanStepPath _fkPlanStepImageVersion;

    /**
     * Get the implicit to-many join path to the <code>public.plan_step</code>
     * table, via the <code>fk_plan_step_image_version</code> key
     */
    public PlanStepPath fkPlanStepImageVersion() {
        if (_fkPlanStepImageVersion == null)
            _fkPlanStepImageVersion = new PlanStepPath(this, null, Keys.PLAN_STEP__FK_PLAN_STEP_IMAGE_VERSION.getInverseKey());

        return _fkPlanStepImageVersion;
    }

    private transient PlanStepPath _fkPlanStepShotVersion;

    /**
     * Get the implicit to-many join path to the <code>public.plan_step</code>
     * table, via the <code>fk_plan_step_shot_version</code> key
     */
    public PlanStepPath fkPlanStepShotVersion() {
        if (_fkPlanStepShotVersion == null)
            _fkPlanStepShotVersion = new PlanStepPath(this, null, Keys.PLAN_STEP__FK_PLAN_STEP_SHOT_VERSION.getInverseKey());

        return _fkPlanStepShotVersion;
    }

    private transient TaskArtifactTargetPath _taskArtifactTarget;

    /**
     * Get the implicit to-many join path to the
     * <code>public.task_artifact_target</code> table
     */
    public TaskArtifactTargetPath taskArtifactTarget() {
        if (_taskArtifactTarget == null)
            _taskArtifactTarget = new TaskArtifactTargetPath(this, null, Keys.TASK_ARTIFACT_TARGET__FK_TASK_ARTIFACT_TARGET_VERSION.getInverseKey());

        return _taskArtifactTarget;
    }

    private transient ShotDurationUpgradePath _shotDurationUpgradeNewVersionIdFkey;

    /**
     * Get the implicit to-many join path to the
     * <code>public.shot_duration_upgrade</code> table, via the
     * <code>shot_duration_upgrade_new_version_id_fkey</code> key
     */
    public ShotDurationUpgradePath shotDurationUpgradeNewVersionIdFkey() {
        if (_shotDurationUpgradeNewVersionIdFkey == null)
            _shotDurationUpgradeNewVersionIdFkey = new ShotDurationUpgradePath(this, null, Keys.SHOT_DURATION_UPGRADE__SHOT_DURATION_UPGRADE_NEW_VERSION_ID_FKEY.getInverseKey());

        return _shotDurationUpgradeNewVersionIdFkey;
    }

    private transient ShotDurationUpgradePath _shotDurationUpgradeOldVersionIdFkey;

    /**
     * Get the implicit to-many join path to the
     * <code>public.shot_duration_upgrade</code> table, via the
     * <code>shot_duration_upgrade_old_version_id_fkey</code> key
     */
    public ShotDurationUpgradePath shotDurationUpgradeOldVersionIdFkey() {
        if (_shotDurationUpgradeOldVersionIdFkey == null)
            _shotDurationUpgradeOldVersionIdFkey = new ShotDurationUpgradePath(this, null, Keys.SHOT_DURATION_UPGRADE__SHOT_DURATION_UPGRADE_OLD_VERSION_ID_FKEY.getInverseKey());

        return _shotDurationUpgradeOldVersionIdFkey;
    }

    @Override
    public List<Check<ArtifactVersionRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("ck_artifact_content_object"), "((jsonb_typeof(content_json) = 'object'::text))", true),
            Internal.createCheck(this, DSL.name("ck_artifact_created_by_kind"), "(((created_by_kind)::text = ANY ((ARRAY['USER'::character varying, 'AGENT'::character varying, 'TASK'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("ck_artifact_input_refs_array"), "((jsonb_typeof(input_refs_json) = 'array'::text))", true),
            Internal.createCheck(this, DSL.name("ck_artifact_schema_version_positive"), "((schema_version > 0))", true),
            Internal.createCheck(this, DSL.name("ck_artifact_version_no_positive"), "((version_no > 0))", true)
        );
    }

    @Override
    public ArtifactVersion as(String alias) {
        return new ArtifactVersion(DSL.name(alias), this);
    }

    @Override
    public ArtifactVersion as(Name alias) {
        return new ArtifactVersion(alias, this);
    }

    @Override
    public ArtifactVersion as(Table<?> alias) {
        return new ArtifactVersion(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ArtifactVersion rename(String name) {
        return new ArtifactVersion(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ArtifactVersion rename(Name name) {
        return new ArtifactVersion(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ArtifactVersion rename(Table<?> name) {
        return new ArtifactVersion(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ArtifactVersion where(Condition condition) {
        return new ArtifactVersion(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ArtifactVersion where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ArtifactVersion where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ArtifactVersion where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ArtifactVersion where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ArtifactVersion where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ArtifactVersion where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ArtifactVersion where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ArtifactVersion whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ArtifactVersion whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
