/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables;


import dev.agenvas.db.Indexes;
import dev.agenvas.db.Keys;
import dev.agenvas.db.Public;
import dev.agenvas.db.tables.AgentBinding.AgentBindingPath;
import dev.agenvas.db.tables.ArtifactVersion.ArtifactVersionPath;
import dev.agenvas.db.tables.CanvasItem.CanvasItemPath;
import dev.agenvas.db.tables.Project.ProjectPath;
import dev.agenvas.db.tables.TaskArtifactTarget.TaskArtifactTargetPath;
import dev.agenvas.db.tables.records.ArtifactRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Artifact extends TableImpl<ArtifactRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.artifact</code>
     */
    public static final Artifact ARTIFACT = new Artifact();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ArtifactRecord> getRecordType() {
        return ArtifactRecord.class;
    }

    /**
     * The column <code>public.artifact.id</code>.
     */
    public final TableField<ArtifactRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.artifact.project_id</code>.
     */
    public final TableField<ArtifactRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.artifact.kind</code>.
     */
    public final TableField<ArtifactRecord, String> KIND = createField(DSL.name("kind"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>public.artifact.title</code>.
     */
    public final TableField<ArtifactRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(160).nullable(false), this, "");

    /**
     * The column <code>public.artifact.resource_default_version_id</code>.
     * Explicit library default used for new CanvasItems; card version selection
     * never updates it.
     */
    public final TableField<ArtifactRecord, UUID> RESOURCE_DEFAULT_VERSION_ID = createField(DSL.name("resource_default_version_id"), SQLDataType.UUID, this, "Explicit library default used for new CanvasItems; card version selection never updates it.");

    /**
     * The column <code>public.artifact.archived_at</code>.
     */
    public final TableField<ArtifactRecord, OffsetDateTime> ARCHIVED_AT = createField(DSL.name("archived_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.artifact.version</code>.
     */
    public final TableField<ArtifactRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.artifact.created_at</code>.
     */
    public final TableField<ArtifactRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.artifact.updated_at</code>.
     */
    public final TableField<ArtifactRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    private Artifact(Name alias, Table<ArtifactRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Artifact(Name alias, Table<ArtifactRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.artifact</code> table reference
     */
    public Artifact(String alias) {
        this(DSL.name(alias), ARTIFACT);
    }

    /**
     * Create an aliased <code>public.artifact</code> table reference
     */
    public Artifact(Name alias) {
        this(alias, ARTIFACT);
    }

    /**
     * Create a <code>public.artifact</code> table reference
     */
    public Artifact() {
        this(DSL.name("artifact"), null);
    }

    public <O extends Record> Artifact(Table<O> path, ForeignKey<O, ArtifactRecord> childPath, InverseForeignKey<O, ArtifactRecord> parentPath) {
        super(path, childPath, parentPath, ARTIFACT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ArtifactPath extends Artifact implements Path<ArtifactRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ArtifactPath(Table<O> path, ForeignKey<O, ArtifactRecord> childPath, InverseForeignKey<O, ArtifactRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ArtifactPath(Name alias, Table<ArtifactRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ArtifactPath as(String alias) {
            return new ArtifactPath(DSL.name(alias), this);
        }

        @Override
        public ArtifactPath as(Name alias) {
            return new ArtifactPath(alias, this);
        }

        @Override
        public ArtifactPath as(Table<?> alias) {
            return new ArtifactPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IX_ARTIFACT_PROJECT_ACTIVE);
    }

    @Override
    public UniqueKey<ArtifactRecord> getPrimaryKey() {
        return Keys.ARTIFACT_PKEY;
    }

    @Override
    public List<UniqueKey<ArtifactRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UQ_ARTIFACT_PROJECT_ID);
    }

    @Override
    public List<ForeignKey<ArtifactRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ARTIFACT__FK_ARTIFACT_PROJECT, Keys.ARTIFACT__FK_ARTIFACT_RESOURCE_DEFAULT_VERSION);
    }

    private transient ProjectPath _project;

    /**
     * Get the implicit join path to the <code>public.project</code> table.
     */
    public ProjectPath project() {
        if (_project == null)
            _project = new ProjectPath(this, Keys.ARTIFACT__FK_ARTIFACT_PROJECT, null);

        return _project;
    }

    private transient ArtifactVersionPath _artifactVersion;

    /**
     * Get the implicit join path to the <code>public.artifact_version</code>
     * table.
     */
    public ArtifactVersionPath artifactVersion() {
        if (_artifactVersion == null)
            _artifactVersion = new ArtifactVersionPath(this, Keys.ARTIFACT__FK_ARTIFACT_RESOURCE_DEFAULT_VERSION, null);

        return _artifactVersion;
    }

    private transient AgentBindingPath _agentBinding;

    /**
     * Get the implicit to-many join path to the
     * <code>public.agent_binding</code> table
     */
    public AgentBindingPath agentBinding() {
        if (_agentBinding == null)
            _agentBinding = new AgentBindingPath(this, null, Keys.AGENT_BINDING__FK_AGENT_BINDING_ARTIFACT.getInverseKey());

        return _agentBinding;
    }

    private transient CanvasItemPath _canvasItem;

    /**
     * Get the implicit to-many join path to the <code>public.canvas_item</code>
     * table
     */
    public CanvasItemPath canvasItem() {
        if (_canvasItem == null)
            _canvasItem = new CanvasItemPath(this, null, Keys.CANVAS_ITEM__FK_CANVAS_ITEM_ARTIFACT.getInverseKey());

        return _canvasItem;
    }

    private transient TaskArtifactTargetPath _taskArtifactTarget;

    /**
     * Get the implicit to-many join path to the
     * <code>public.task_artifact_target</code> table
     */
    public TaskArtifactTargetPath taskArtifactTarget() {
        if (_taskArtifactTarget == null)
            _taskArtifactTarget = new TaskArtifactTargetPath(this, null, Keys.TASK_ARTIFACT_TARGET__FK_TASK_ARTIFACT_TARGET_ARTIFACT.getInverseKey());

        return _taskArtifactTarget;
    }

    @Override
    public List<Check<ArtifactRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("ck_artifact_kind"), "(((kind)::text = ANY ((ARRAY['TEXT'::character varying, 'IMAGE'::character varying, 'VIDEO'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("ck_artifact_title_not_blank"), "((length(btrim((title)::text)) > 0))", true),
            Internal.createCheck(this, DSL.name("ck_artifact_version_non_negative"), "((version >= 0))", true)
        );
    }

    @Override
    public Artifact as(String alias) {
        return new Artifact(DSL.name(alias), this);
    }

    @Override
    public Artifact as(Name alias) {
        return new Artifact(alias, this);
    }

    @Override
    public Artifact as(Table<?> alias) {
        return new Artifact(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Artifact rename(String name) {
        return new Artifact(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Artifact rename(Name name) {
        return new Artifact(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Artifact rename(Table<?> name) {
        return new Artifact(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Artifact where(Condition condition) {
        return new Artifact(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Artifact where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Artifact where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Artifact where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Artifact where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Artifact where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Artifact where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Artifact where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Artifact whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Artifact whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
