/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables;


import dev.agenvas.db.Keys;
import dev.agenvas.db.Public;
import dev.agenvas.db.tables.records.AuditDebugSettingsRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 全局调用调试开关，默认不保存调用正文
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AuditDebugSettings extends TableImpl<AuditDebugSettingsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.audit_debug_settings</code>
     */
    public static final AuditDebugSettings AUDIT_DEBUG_SETTINGS = new AuditDebugSettings();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuditDebugSettingsRecord> getRecordType() {
        return AuditDebugSettingsRecord.class;
    }

    /**
     * The column <code>public.audit_debug_settings.id</code>. 记录身份
     */
    public final TableField<AuditDebugSettingsRecord, Short> ID = createField(DSL.name("id"), SQLDataType.SMALLINT.nullable(false), this, "记录身份");

    /**
     * The column <code>public.audit_debug_settings.debug_mode</code>.
     * 是否显式启用已脱敏调用正文调试
     */
    public final TableField<AuditDebugSettingsRecord, Boolean> DEBUG_MODE = createField(DSL.name("debug_mode"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "是否显式启用已脱敏调用正文调试");

    /**
     * The column <code>public.audit_debug_settings.version</code>.
     * 乐观并发控制版本，更新时递增并校验预期值
     */
    public final TableField<AuditDebugSettingsRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "乐观并发控制版本，更新时递增并校验预期值");

    private AuditDebugSettings(Name alias, Table<AuditDebugSettingsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AuditDebugSettings(Name alias, Table<AuditDebugSettingsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("全局调用调试开关，默认不保存调用正文"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.audit_debug_settings</code> table
     * reference
     */
    public AuditDebugSettings(String alias) {
        this(DSL.name(alias), AUDIT_DEBUG_SETTINGS);
    }

    /**
     * Create an aliased <code>public.audit_debug_settings</code> table
     * reference
     */
    public AuditDebugSettings(Name alias) {
        this(alias, AUDIT_DEBUG_SETTINGS);
    }

    /**
     * Create a <code>public.audit_debug_settings</code> table reference
     */
    public AuditDebugSettings() {
        this(DSL.name("audit_debug_settings"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AuditDebugSettingsRecord> getPrimaryKey() {
        return Keys.AUDIT_DEBUG_SETTINGS_PKEY;
    }

    @Override
    public List<Check<AuditDebugSettingsRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("audit_debug_settings_id_check"), "((id = 1))", true),
            Internal.createCheck(this, DSL.name("audit_debug_settings_version_check"), "((version > 0))", true)
        );
    }

    @Override
    public AuditDebugSettings as(String alias) {
        return new AuditDebugSettings(DSL.name(alias), this);
    }

    @Override
    public AuditDebugSettings as(Name alias) {
        return new AuditDebugSettings(alias, this);
    }

    @Override
    public AuditDebugSettings as(Table<?> alias) {
        return new AuditDebugSettings(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditDebugSettings rename(String name) {
        return new AuditDebugSettings(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditDebugSettings rename(Name name) {
        return new AuditDebugSettings(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditDebugSettings rename(Table<?> name) {
        return new AuditDebugSettings(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditDebugSettings where(Condition condition) {
        return new AuditDebugSettings(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditDebugSettings where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditDebugSettings where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditDebugSettings where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditDebugSettings where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditDebugSettings where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditDebugSettings where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditDebugSettings where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditDebugSettings whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditDebugSettings whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
