/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables;


import dev.agenvas.db.Keys;
import dev.agenvas.db.Public;
import dev.agenvas.db.tables.CallLog.CallLogPath;
import dev.agenvas.db.tables.records.CallLogDebugRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 仅在明确启用调试时保存的已脱敏请求与响应正文
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CallLogDebug extends TableImpl<CallLogDebugRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.call_log_debug</code>
     */
    public static final CallLogDebug CALL_LOG_DEBUG = new CallLogDebug();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CallLogDebugRecord> getRecordType() {
        return CallLogDebugRecord.class;
    }

    /**
     * The column <code>public.call_log_debug.call_id</code>. 对应的公开调用审计记录
     */
    public final TableField<CallLogDebugRecord, UUID> CALL_ID = createField(DSL.name("call_id"), SQLDataType.UUID.nullable(false), this, "对应的公开调用审计记录");

    /**
     * The column <code>public.call_log_debug.schema_version</code>. 持久 JSON
     * 内容格式版本
     */
    public final TableField<CallLogDebugRecord, Integer> SCHEMA_VERSION = createField(DSL.name("schema_version"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "持久 JSON 内容格式版本");

    /**
     * The column <code>public.call_log_debug.exchanges_json</code>. 已脱敏调用交换正文数组
     */
    public final TableField<CallLogDebugRecord, JSONB> EXCHANGES_JSON = createField(DSL.name("exchanges_json"), SQLDataType.JSONB.nullable(false), this, "已脱敏调用交换正文数组");

    private CallLogDebug(Name alias, Table<CallLogDebugRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CallLogDebug(Name alias, Table<CallLogDebugRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("仅在明确启用调试时保存的已脱敏请求与响应正文"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.call_log_debug</code> table reference
     */
    public CallLogDebug(String alias) {
        this(DSL.name(alias), CALL_LOG_DEBUG);
    }

    /**
     * Create an aliased <code>public.call_log_debug</code> table reference
     */
    public CallLogDebug(Name alias) {
        this(alias, CALL_LOG_DEBUG);
    }

    /**
     * Create a <code>public.call_log_debug</code> table reference
     */
    public CallLogDebug() {
        this(DSL.name("call_log_debug"), null);
    }

    public <O extends Record> CallLogDebug(Table<O> path, ForeignKey<O, CallLogDebugRecord> childPath, InverseForeignKey<O, CallLogDebugRecord> parentPath) {
        super(path, childPath, parentPath, CALL_LOG_DEBUG);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CallLogDebugPath extends CallLogDebug implements Path<CallLogDebugRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CallLogDebugPath(Table<O> path, ForeignKey<O, CallLogDebugRecord> childPath, InverseForeignKey<O, CallLogDebugRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CallLogDebugPath(Name alias, Table<CallLogDebugRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CallLogDebugPath as(String alias) {
            return new CallLogDebugPath(DSL.name(alias), this);
        }

        @Override
        public CallLogDebugPath as(Name alias) {
            return new CallLogDebugPath(alias, this);
        }

        @Override
        public CallLogDebugPath as(Table<?> alias) {
            return new CallLogDebugPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<CallLogDebugRecord> getPrimaryKey() {
        return Keys.CALL_LOG_DEBUG_PKEY;
    }

    @Override
    public List<ForeignKey<CallLogDebugRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CALL_LOG_DEBUG__CALL_LOG_DEBUG_CALL_ID_FKEY);
    }

    private transient CallLogPath _callLog;

    /**
     * Get the implicit join path to the <code>public.call_log</code> table.
     */
    public CallLogPath callLog() {
        if (_callLog == null)
            _callLog = new CallLogPath(this, Keys.CALL_LOG_DEBUG__CALL_LOG_DEBUG_CALL_ID_FKEY, null);

        return _callLog;
    }

    @Override
    public List<Check<CallLogDebugRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("call_log_debug_exchanges_json_check"), "((jsonb_typeof(exchanges_json) = 'array'::text))", true),
            Internal.createCheck(this, DSL.name("call_log_debug_schema_version_check"), "((schema_version = 1))", true)
        );
    }

    @Override
    public CallLogDebug as(String alias) {
        return new CallLogDebug(DSL.name(alias), this);
    }

    @Override
    public CallLogDebug as(Name alias) {
        return new CallLogDebug(alias, this);
    }

    @Override
    public CallLogDebug as(Table<?> alias) {
        return new CallLogDebug(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CallLogDebug rename(String name) {
        return new CallLogDebug(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CallLogDebug rename(Name name) {
        return new CallLogDebug(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CallLogDebug rename(Table<?> name) {
        return new CallLogDebug(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CallLogDebug where(Condition condition) {
        return new CallLogDebug(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CallLogDebug where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CallLogDebug where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CallLogDebug where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CallLogDebug where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CallLogDebug where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CallLogDebug where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CallLogDebug where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CallLogDebug whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CallLogDebug whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
