/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables;


import dev.agenvas.db.Indexes;
import dev.agenvas.db.Keys;
import dev.agenvas.db.Public;
import dev.agenvas.db.tables.ArtifactVersion.ArtifactVersionPath;
import dev.agenvas.db.tables.CanvasItemMediaInputSource.CanvasItemMediaInputSourcePath;
import dev.agenvas.db.tables.MediaDraft.MediaDraftPath;
import dev.agenvas.db.tables.records.CanvasItemMediaInputRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Deduplicated exact media versions; dynamicValues maps named capability slots
 * to these version identities.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CanvasItemMediaInput extends TableImpl<CanvasItemMediaInputRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.canvas_item_media_input</code>
     */
    public static final CanvasItemMediaInput CANVAS_ITEM_MEDIA_INPUT = new CanvasItemMediaInput();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CanvasItemMediaInputRecord> getRecordType() {
        return CanvasItemMediaInputRecord.class;
    }

    /**
     * The column <code>public.canvas_item_media_input.project_id</code>.
     */
    public final TableField<CanvasItemMediaInputRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.canvas_item_media_input.canvas_item_id</code>.
     */
    public final TableField<CanvasItemMediaInputRecord, UUID> CANVAS_ITEM_ID = createField(DSL.name("canvas_item_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column
     * <code>public.canvas_item_media_input.artifact_version_id</code>.
     */
    public final TableField<CanvasItemMediaInputRecord, UUID> ARTIFACT_VERSION_ID = createField(DSL.name("artifact_version_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.canvas_item_media_input.input_role</code>.
     */
    public final TableField<CanvasItemMediaInputRecord, String> INPUT_ROLE = createField(DSL.name("input_role"), SQLDataType.VARCHAR(24).nullable(false), this, "");

    /**
     * The column <code>public.canvas_item_media_input.input_order</code>.
     */
    public final TableField<CanvasItemMediaInputRecord, Integer> INPUT_ORDER = createField(DSL.name("input_order"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.canvas_item_media_input.color</code>.
     */
    public final TableField<CanvasItemMediaInputRecord, String> COLOR = createField(DSL.name("color"), SQLDataType.VARCHAR(7).nullable(false), this, "");

    /**
     * The column <code>public.canvas_item_media_input.created_at</code>.
     */
    public final TableField<CanvasItemMediaInputRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.canvas_item_media_input.updated_at</code>.
     */
    public final TableField<CanvasItemMediaInputRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    private CanvasItemMediaInput(Name alias, Table<CanvasItemMediaInputRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CanvasItemMediaInput(Name alias, Table<CanvasItemMediaInputRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Deduplicated exact media versions; dynamicValues maps named capability slots to these version identities."), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.canvas_item_media_input</code> table
     * reference
     */
    public CanvasItemMediaInput(String alias) {
        this(DSL.name(alias), CANVAS_ITEM_MEDIA_INPUT);
    }

    /**
     * Create an aliased <code>public.canvas_item_media_input</code> table
     * reference
     */
    public CanvasItemMediaInput(Name alias) {
        this(alias, CANVAS_ITEM_MEDIA_INPUT);
    }

    /**
     * Create a <code>public.canvas_item_media_input</code> table reference
     */
    public CanvasItemMediaInput() {
        this(DSL.name("canvas_item_media_input"), null);
    }

    public <O extends Record> CanvasItemMediaInput(Table<O> path, ForeignKey<O, CanvasItemMediaInputRecord> childPath, InverseForeignKey<O, CanvasItemMediaInputRecord> parentPath) {
        super(path, childPath, parentPath, CANVAS_ITEM_MEDIA_INPUT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CanvasItemMediaInputPath extends CanvasItemMediaInput implements Path<CanvasItemMediaInputRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CanvasItemMediaInputPath(Table<O> path, ForeignKey<O, CanvasItemMediaInputRecord> childPath, InverseForeignKey<O, CanvasItemMediaInputRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CanvasItemMediaInputPath(Name alias, Table<CanvasItemMediaInputRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CanvasItemMediaInputPath as(String alias) {
            return new CanvasItemMediaInputPath(DSL.name(alias), this);
        }

        @Override
        public CanvasItemMediaInputPath as(Name alias) {
            return new CanvasItemMediaInputPath(alias, this);
        }

        @Override
        public CanvasItemMediaInputPath as(Table<?> alias) {
            return new CanvasItemMediaInputPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.UQ_CANVAS_ITEM_MEDIA_INPUT_END_FRAME, Indexes.UQ_CANVAS_ITEM_MEDIA_INPUT_START_FRAME);
    }

    @Override
    public UniqueKey<CanvasItemMediaInputRecord> getPrimaryKey() {
        return Keys.CANVAS_ITEM_MEDIA_INPUT_PKEY;
    }

    @Override
    public List<UniqueKey<CanvasItemMediaInputRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UQ_CANVAS_ITEM_MEDIA_INPUT_ORDER);
    }

    @Override
    public List<ForeignKey<CanvasItemMediaInputRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CANVAS_ITEM_MEDIA_INPUT__FK_CANVAS_ITEM_MEDIA_INPUT_DRAFT, Keys.CANVAS_ITEM_MEDIA_INPUT__FK_CANVAS_ITEM_MEDIA_INPUT_VERSION);
    }

    private transient MediaDraftPath _mediaDraft;

    /**
     * Get the implicit join path to the <code>public.media_draft</code> table.
     */
    public MediaDraftPath mediaDraft() {
        if (_mediaDraft == null)
            _mediaDraft = new MediaDraftPath(this, Keys.CANVAS_ITEM_MEDIA_INPUT__FK_CANVAS_ITEM_MEDIA_INPUT_DRAFT, null);

        return _mediaDraft;
    }

    private transient ArtifactVersionPath _artifactVersion;

    /**
     * Get the implicit join path to the <code>public.artifact_version</code>
     * table.
     */
    public ArtifactVersionPath artifactVersion() {
        if (_artifactVersion == null)
            _artifactVersion = new ArtifactVersionPath(this, Keys.CANVAS_ITEM_MEDIA_INPUT__FK_CANVAS_ITEM_MEDIA_INPUT_VERSION, null);

        return _artifactVersion;
    }

    private transient CanvasItemMediaInputSourcePath _canvasItemMediaInputSource;

    /**
     * Get the implicit to-many join path to the
     * <code>public.canvas_item_media_input_source</code> table
     */
    public CanvasItemMediaInputSourcePath canvasItemMediaInputSource() {
        if (_canvasItemMediaInputSource == null)
            _canvasItemMediaInputSource = new CanvasItemMediaInputSourcePath(this, null, Keys.CANVAS_ITEM_MEDIA_INPUT_SOURCE__FK_CANVAS_ITEM_MEDIA_INPUT_SOURCE_INPUT.getInverseKey());

        return _canvasItemMediaInputSource;
    }

    @Override
    public List<Check<CanvasItemMediaInputRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("ck_canvas_item_media_input_color"), "(((color)::text ~ '^#[0-9A-F]{6}$'::text))", true),
            Internal.createCheck(this, DSL.name("ck_canvas_item_media_input_order"), "((input_order >= 0))", true),
            Internal.createCheck(this, DSL.name("ck_canvas_item_media_input_role"), "(((input_role)::text = ANY ((ARRAY['REFERENCE'::character varying, 'START_FRAME'::character varying, 'END_FRAME'::character varying, 'AUDIO_REFERENCE'::character varying, 'VIDEO_REFERENCE'::character varying])::text[])))", true)
        );
    }

    @Override
    public CanvasItemMediaInput as(String alias) {
        return new CanvasItemMediaInput(DSL.name(alias), this);
    }

    @Override
    public CanvasItemMediaInput as(Name alias) {
        return new CanvasItemMediaInput(alias, this);
    }

    @Override
    public CanvasItemMediaInput as(Table<?> alias) {
        return new CanvasItemMediaInput(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CanvasItemMediaInput rename(String name) {
        return new CanvasItemMediaInput(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CanvasItemMediaInput rename(Name name) {
        return new CanvasItemMediaInput(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CanvasItemMediaInput rename(Table<?> name) {
        return new CanvasItemMediaInput(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CanvasItemMediaInput where(Condition condition) {
        return new CanvasItemMediaInput(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CanvasItemMediaInput where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CanvasItemMediaInput where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CanvasItemMediaInput where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CanvasItemMediaInput where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CanvasItemMediaInput where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CanvasItemMediaInput where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CanvasItemMediaInput where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CanvasItemMediaInput whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CanvasItemMediaInput whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
