/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables;


import dev.agenvas.db.Keys;
import dev.agenvas.db.Public;
import dev.agenvas.db.tables.records.InstallationLockRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 管理员初始化的单例事务锁行
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InstallationLock extends TableImpl<InstallationLockRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.installation_lock</code>
     */
    public static final InstallationLock INSTALLATION_LOCK = new InstallationLock();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InstallationLockRecord> getRecordType() {
        return InstallationLockRecord.class;
    }

    /**
     * The column <code>public.installation_lock.id</code>. 记录身份
     */
    public final TableField<InstallationLockRecord, Short> ID = createField(DSL.name("id"), SQLDataType.SMALLINT.nullable(false), this, "记录身份");

    /**
     * The column <code>public.installation_lock.initialized_at</code>.
     * 首次管理员初始化的完成时间；停用或删除管理员不会重新开放初始化
     */
    public final TableField<InstallationLockRecord, OffsetDateTime> INITIALIZED_AT = createField(DSL.name("initialized_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "首次管理员初始化的完成时间；停用或删除管理员不会重新开放初始化");

    private InstallationLock(Name alias, Table<InstallationLockRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private InstallationLock(Name alias, Table<InstallationLockRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("管理员初始化的单例事务锁行"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.installation_lock</code> table reference
     */
    public InstallationLock(String alias) {
        this(DSL.name(alias), INSTALLATION_LOCK);
    }

    /**
     * Create an aliased <code>public.installation_lock</code> table reference
     */
    public InstallationLock(Name alias) {
        this(alias, INSTALLATION_LOCK);
    }

    /**
     * Create a <code>public.installation_lock</code> table reference
     */
    public InstallationLock() {
        this(DSL.name("installation_lock"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<InstallationLockRecord> getPrimaryKey() {
        return Keys.INSTALLATION_LOCK_PKEY;
    }

    @Override
    public List<Check<InstallationLockRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("ck_installation_lock_singleton"), "((id = 1))", true)
        );
    }

    @Override
    public InstallationLock as(String alias) {
        return new InstallationLock(DSL.name(alias), this);
    }

    @Override
    public InstallationLock as(Name alias) {
        return new InstallationLock(alias, this);
    }

    @Override
    public InstallationLock as(Table<?> alias) {
        return new InstallationLock(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public InstallationLock rename(String name) {
        return new InstallationLock(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public InstallationLock rename(Name name) {
        return new InstallationLock(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public InstallationLock rename(Table<?> name) {
        return new InstallationLock(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InstallationLock where(Condition condition) {
        return new InstallationLock(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InstallationLock where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InstallationLock where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InstallationLock where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InstallationLock where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InstallationLock where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InstallationLock where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InstallationLock where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InstallationLock whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InstallationLock whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
