/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables;


import dev.agenvas.db.Indexes;
import dev.agenvas.db.Keys;
import dev.agenvas.db.Public;
import dev.agenvas.db.tables.AgentRun.AgentRunPath;
import dev.agenvas.db.tables.ToolExecution.ToolExecutionPath;
import dev.agenvas.db.tables.records.LlmTurnRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 固定模型配置版本的持久模型回合，保存完整响应后才执行工具
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LlmTurn extends TableImpl<LlmTurnRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.llm_turn</code>
     */
    public static final LlmTurn LLM_TURN = new LlmTurn();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LlmTurnRecord> getRecordType() {
        return LlmTurnRecord.class;
    }

    /**
     * The column <code>public.llm_turn.project_id</code>. 所属项目及授权作用域
     */
    public final TableField<LlmTurnRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "所属项目及授权作用域");

    /**
     * The column <code>public.llm_turn.run_id</code>. 所属 Agent Run；用户直连任务为空
     */
    public final TableField<LlmTurnRecord, UUID> RUN_ID = createField(DSL.name("run_id"), SQLDataType.UUID.nullable(false), this, "所属 Agent Run；用户直连任务为空");

    /**
     * The column <code>public.llm_turn.step_index</code>. Run 内模型回合序号
     */
    public final TableField<LlmTurnRecord, Integer> STEP_INDEX = createField(DSL.name("step_index"), SQLDataType.INTEGER.nullable(false), this, "Run 内模型回合序号");

    /**
     * The column <code>public.llm_turn.status</code>. 持久状态，允许值由 CHECK 约束限定
     */
    public final TableField<LlmTurnRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(20).nullable(false), this, "持久状态，允许值由 CHECK 约束限定");

    /**
     * The column <code>public.llm_turn.model_config_version</code>. 本模型回合固定使用的
     * LLM 配置版本
     */
    public final TableField<LlmTurnRecord, Integer> MODEL_CONFIG_VERSION = createField(DSL.name("model_config_version"), SQLDataType.INTEGER.nullable(false), this, "本模型回合固定使用的 LLM 配置版本");

    /**
     * The column <code>public.llm_turn.request_json</code>. 固定的模型请求或媒体审批批次
     */
    public final TableField<LlmTurnRecord, JSONB> REQUEST_JSON = createField(DSL.name("request_json"), SQLDataType.JSONB.nullable(false), this, "固定的模型请求或媒体审批批次");

    /**
     * The column <code>public.llm_turn.response_json</code>. 已提交的命令响应或完整模型响应
     */
    public final TableField<LlmTurnRecord, JSONB> RESPONSE_JSON = createField(DSL.name("response_json"), SQLDataType.JSONB, this, "已提交的命令响应或完整模型响应");

    /**
     * The column <code>public.llm_turn.created_at</code>. 创建时间（UTC）
     */
    public final TableField<LlmTurnRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "创建时间（UTC）");

    /**
     * The column <code>public.llm_turn.responded_at</code>. 完整响应持久化时间
     */
    public final TableField<LlmTurnRecord, OffsetDateTime> RESPONDED_AT = createField(DSL.name("responded_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "完整响应持久化时间");

    private LlmTurn(Name alias, Table<LlmTurnRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private LlmTurn(Name alias, Table<LlmTurnRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("固定模型配置版本的持久模型回合，保存完整响应后才执行工具"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.llm_turn</code> table reference
     */
    public LlmTurn(String alias) {
        this(DSL.name(alias), LLM_TURN);
    }

    /**
     * Create an aliased <code>public.llm_turn</code> table reference
     */
    public LlmTurn(Name alias) {
        this(alias, LLM_TURN);
    }

    /**
     * Create a <code>public.llm_turn</code> table reference
     */
    public LlmTurn() {
        this(DSL.name("llm_turn"), null);
    }

    public <O extends Record> LlmTurn(Table<O> path, ForeignKey<O, LlmTurnRecord> childPath, InverseForeignKey<O, LlmTurnRecord> parentPath) {
        super(path, childPath, parentPath, LLM_TURN);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class LlmTurnPath extends LlmTurn implements Path<LlmTurnRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> LlmTurnPath(Table<O> path, ForeignKey<O, LlmTurnRecord> childPath, InverseForeignKey<O, LlmTurnRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private LlmTurnPath(Name alias, Table<LlmTurnRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public LlmTurnPath as(String alias) {
            return new LlmTurnPath(DSL.name(alias), this);
        }

        @Override
        public LlmTurnPath as(Name alias) {
            return new LlmTurnPath(alias, this);
        }

        @Override
        public LlmTurnPath as(Table<?> alias) {
            return new LlmTurnPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IX_LLM_TURN_PROJECT_RUN);
    }

    @Override
    public UniqueKey<LlmTurnRecord> getPrimaryKey() {
        return Keys.LLM_TURN_PKEY;
    }

    @Override
    public List<ForeignKey<LlmTurnRecord, ?>> getReferences() {
        return Arrays.asList(Keys.LLM_TURN__FK_LLM_TURN_RUN);
    }

    private transient AgentRunPath _agentRun;

    /**
     * Get the implicit join path to the <code>public.agent_run</code> table.
     */
    public AgentRunPath agentRun() {
        if (_agentRun == null)
            _agentRun = new AgentRunPath(this, Keys.LLM_TURN__FK_LLM_TURN_RUN, null);

        return _agentRun;
    }

    private transient ToolExecutionPath _toolExecution;

    /**
     * Get the implicit to-many join path to the
     * <code>public.tool_execution</code> table
     */
    public ToolExecutionPath toolExecution() {
        if (_toolExecution == null)
            _toolExecution = new ToolExecutionPath(this, null, Keys.TOOL_EXECUTION__FK_TOOL_EXECUTION_TURN.getInverseKey());

        return _toolExecution;
    }

    @Override
    public List<Check<LlmTurnRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("ck_llm_turn_config_version"), "((model_config_version > 0))", true),
            Internal.createCheck(this, DSL.name("ck_llm_turn_request_object"), "((jsonb_typeof(request_json) = 'object'::text))", true),
            Internal.createCheck(this, DSL.name("ck_llm_turn_response_object"), "(((response_json IS NULL) OR (jsonb_typeof(response_json) = 'object'::text)))", true),
            Internal.createCheck(this, DSL.name("ck_llm_turn_response_state"), "(((((status)::text = 'REQUESTED'::text) AND (response_json IS NULL) AND (responded_at IS NULL)) OR (((status)::text = 'RESPONDED'::text) AND (response_json IS NOT NULL) AND (responded_at IS NOT NULL))))", true),
            Internal.createCheck(this, DSL.name("ck_llm_turn_status"), "(((status)::text = ANY ((ARRAY['REQUESTED'::character varying, 'RESPONDED'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("ck_llm_turn_step"), "((step_index >= 0))", true)
        );
    }

    @Override
    public LlmTurn as(String alias) {
        return new LlmTurn(DSL.name(alias), this);
    }

    @Override
    public LlmTurn as(Name alias) {
        return new LlmTurn(alias, this);
    }

    @Override
    public LlmTurn as(Table<?> alias) {
        return new LlmTurn(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public LlmTurn rename(String name) {
        return new LlmTurn(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public LlmTurn rename(Name name) {
        return new LlmTurn(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public LlmTurn rename(Table<?> name) {
        return new LlmTurn(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LlmTurn where(Condition condition) {
        return new LlmTurn(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LlmTurn where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LlmTurn where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LlmTurn where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LlmTurn where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LlmTurn where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LlmTurn where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LlmTurn where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LlmTurn whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LlmTurn whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
