/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables;


import dev.agenvas.db.Keys;
import dev.agenvas.db.Public;
import dev.agenvas.db.tables.MediaCapability.MediaCapabilityPath;
import dev.agenvas.db.tables.records.MediaFunctionSettingRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Administrator-selected image/video processing capabilities, independent of
 * generation defaults
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MediaFunctionSetting extends TableImpl<MediaFunctionSettingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.media_function_setting</code>
     */
    public static final MediaFunctionSetting MEDIA_FUNCTION_SETTING = new MediaFunctionSetting();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MediaFunctionSettingRecord> getRecordType() {
        return MediaFunctionSettingRecord.class;
    }

    /**
     * The column <code>public.media_function_setting.operation</code>.
     * Qualified IMAGE_ or VIDEO_ tool identity
     */
    public final TableField<MediaFunctionSettingRecord, String> OPERATION = createField(DSL.name("operation"), SQLDataType.VARCHAR(32).nullable(false), this, "Qualified IMAGE_ or VIDEO_ tool identity");

    /**
     * The column <code>public.media_function_setting.capability_id</code>.
     * Selected published capability; null disables new execution
     */
    public final TableField<MediaFunctionSettingRecord, UUID> CAPABILITY_ID = createField(DSL.name("capability_id"), SQLDataType.UUID, this, "Selected published capability; null disables new execution");

    /**
     * The column <code>public.media_function_setting.version</code>. CAS
     * version changed only by explicit function setting updates
     */
    public final TableField<MediaFunctionSettingRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "CAS version changed only by explicit function setting updates");

    /**
     * The column <code>public.media_function_setting.updated_at</code>. Last
     * function setting update time in UTC
     */
    public final TableField<MediaFunctionSettingRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "Last function setting update time in UTC");

    private MediaFunctionSetting(Name alias, Table<MediaFunctionSettingRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MediaFunctionSetting(Name alias, Table<MediaFunctionSettingRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Administrator-selected image/video processing capabilities, independent of generation defaults"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.media_function_setting</code> table
     * reference
     */
    public MediaFunctionSetting(String alias) {
        this(DSL.name(alias), MEDIA_FUNCTION_SETTING);
    }

    /**
     * Create an aliased <code>public.media_function_setting</code> table
     * reference
     */
    public MediaFunctionSetting(Name alias) {
        this(alias, MEDIA_FUNCTION_SETTING);
    }

    /**
     * Create a <code>public.media_function_setting</code> table reference
     */
    public MediaFunctionSetting() {
        this(DSL.name("media_function_setting"), null);
    }

    public <O extends Record> MediaFunctionSetting(Table<O> path, ForeignKey<O, MediaFunctionSettingRecord> childPath, InverseForeignKey<O, MediaFunctionSettingRecord> parentPath) {
        super(path, childPath, parentPath, MEDIA_FUNCTION_SETTING);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MediaFunctionSettingPath extends MediaFunctionSetting implements Path<MediaFunctionSettingRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MediaFunctionSettingPath(Table<O> path, ForeignKey<O, MediaFunctionSettingRecord> childPath, InverseForeignKey<O, MediaFunctionSettingRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MediaFunctionSettingPath(Name alias, Table<MediaFunctionSettingRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MediaFunctionSettingPath as(String alias) {
            return new MediaFunctionSettingPath(DSL.name(alias), this);
        }

        @Override
        public MediaFunctionSettingPath as(Name alias) {
            return new MediaFunctionSettingPath(alias, this);
        }

        @Override
        public MediaFunctionSettingPath as(Table<?> alias) {
            return new MediaFunctionSettingPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<MediaFunctionSettingRecord> getPrimaryKey() {
        return Keys.MEDIA_FUNCTION_SETTING_PKEY;
    }

    @Override
    public List<ForeignKey<MediaFunctionSettingRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MEDIA_FUNCTION_SETTING__MEDIA_FUNCTION_SETTING_CAPABILITY_ID_FKEY);
    }

    private transient MediaCapabilityPath _mediaCapability;

    /**
     * Get the implicit join path to the <code>public.media_capability</code>
     * table.
     */
    public MediaCapabilityPath mediaCapability() {
        if (_mediaCapability == null)
            _mediaCapability = new MediaCapabilityPath(this, Keys.MEDIA_FUNCTION_SETTING__MEDIA_FUNCTION_SETTING_CAPABILITY_ID_FKEY, null);

        return _mediaCapability;
    }

    @Override
    public List<Check<MediaFunctionSettingRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("media_function_setting_operation_check"), "(((operation)::text = ANY ((ARRAY['IMAGE_SMART_EDIT'::character varying, 'IMAGE_RELIGHT'::character varying, 'IMAGE_OUTPAINT'::character varying, 'IMAGE_THREE_VIEW'::character varying, 'IMAGE_LAYER_SPLIT'::character varying, 'IMAGE_EXPRESSION_EDIT'::character varying, 'IMAGE_REMOVE_BACKGROUND'::character varying, 'IMAGE_OBJECT_REMOVE'::character varying, 'IMAGE_VIEW_ANGLE'::character varying, 'IMAGE_DEPTH_MAP'::character varying, 'IMAGE_UPSCALE'::character varying, 'IMAGE_CROP'::character varying, 'IMAGE_ROTATE'::character varying, 'IMAGE_FLIP_HORIZONTAL'::character varying, 'IMAGE_FLIP_VERTICAL'::character varying, 'VIDEO_DEPTH_MAP'::character varying, 'VIDEO_EXTRACT_AUDIO'::character varying, 'VIDEO_UPSCALE'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("media_function_setting_version_check"), "((version >= 0))", true)
        );
    }

    @Override
    public MediaFunctionSetting as(String alias) {
        return new MediaFunctionSetting(DSL.name(alias), this);
    }

    @Override
    public MediaFunctionSetting as(Name alias) {
        return new MediaFunctionSetting(alias, this);
    }

    @Override
    public MediaFunctionSetting as(Table<?> alias) {
        return new MediaFunctionSetting(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaFunctionSetting rename(String name) {
        return new MediaFunctionSetting(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaFunctionSetting rename(Name name) {
        return new MediaFunctionSetting(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaFunctionSetting rename(Table<?> name) {
        return new MediaFunctionSetting(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaFunctionSetting where(Condition condition) {
        return new MediaFunctionSetting(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaFunctionSetting where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaFunctionSetting where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaFunctionSetting where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaFunctionSetting where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaFunctionSetting where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaFunctionSetting where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaFunctionSetting where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaFunctionSetting whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaFunctionSetting whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
