/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables;


import dev.agenvas.db.Keys;
import dev.agenvas.db.Public;
import dev.agenvas.db.tables.AppUser.AppUserPath;
import dev.agenvas.db.tables.MediaTemplateImage.MediaTemplateImagePath;
import dev.agenvas.db.tables.MediaTemplateImportSource.MediaTemplateImportSourcePath;
import dev.agenvas.db.tables.Project.ProjectPath;
import dev.agenvas.db.tables.records.MediaTemplateImportCommandRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MediaTemplateImportCommand extends TableImpl<MediaTemplateImportCommandRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.media_template_import_command</code>
     */
    public static final MediaTemplateImportCommand MEDIA_TEMPLATE_IMPORT_COMMAND = new MediaTemplateImportCommand();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MediaTemplateImportCommandRecord> getRecordType() {
        return MediaTemplateImportCommandRecord.class;
    }

    /**
     * The column <code>public.media_template_import_command.id</code>.
     */
    public final TableField<MediaTemplateImportCommandRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.media_template_import_command.owner_id</code>.
     */
    public final TableField<MediaTemplateImportCommandRecord, UUID> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.media_template_import_command.project_id</code>.
     */
    public final TableField<MediaTemplateImportCommandRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.media_template_import_command.command_key</code>.
     */
    public final TableField<MediaTemplateImportCommandRecord, String> COMMAND_KEY = createField(DSL.name("command_key"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column
     * <code>public.media_template_import_command.payload_hash</code>.
     */
    public final TableField<MediaTemplateImportCommandRecord, String> PAYLOAD_HASH = createField(DSL.name("payload_hash"), SQLDataType.CHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.media_template_import_command.input_json</code>.
     */
    public final TableField<MediaTemplateImportCommandRecord, JSONB> INPUT_JSON = createField(DSL.name("input_json"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>public.media_template_import_command.result_json</code>.
     */
    public final TableField<MediaTemplateImportCommandRecord, JSONB> RESULT_JSON = createField(DSL.name("result_json"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.media_template_import_command.created_at</code>.
     */
    public final TableField<MediaTemplateImportCommandRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    private MediaTemplateImportCommand(Name alias, Table<MediaTemplateImportCommandRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MediaTemplateImportCommand(Name alias, Table<MediaTemplateImportCommandRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.media_template_import_command</code> table
     * reference
     */
    public MediaTemplateImportCommand(String alias) {
        this(DSL.name(alias), MEDIA_TEMPLATE_IMPORT_COMMAND);
    }

    /**
     * Create an aliased <code>public.media_template_import_command</code> table
     * reference
     */
    public MediaTemplateImportCommand(Name alias) {
        this(alias, MEDIA_TEMPLATE_IMPORT_COMMAND);
    }

    /**
     * Create a <code>public.media_template_import_command</code> table
     * reference
     */
    public MediaTemplateImportCommand() {
        this(DSL.name("media_template_import_command"), null);
    }

    public <O extends Record> MediaTemplateImportCommand(Table<O> path, ForeignKey<O, MediaTemplateImportCommandRecord> childPath, InverseForeignKey<O, MediaTemplateImportCommandRecord> parentPath) {
        super(path, childPath, parentPath, MEDIA_TEMPLATE_IMPORT_COMMAND);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MediaTemplateImportCommandPath extends MediaTemplateImportCommand implements Path<MediaTemplateImportCommandRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MediaTemplateImportCommandPath(Table<O> path, ForeignKey<O, MediaTemplateImportCommandRecord> childPath, InverseForeignKey<O, MediaTemplateImportCommandRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MediaTemplateImportCommandPath(Name alias, Table<MediaTemplateImportCommandRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MediaTemplateImportCommandPath as(String alias) {
            return new MediaTemplateImportCommandPath(DSL.name(alias), this);
        }

        @Override
        public MediaTemplateImportCommandPath as(Name alias) {
            return new MediaTemplateImportCommandPath(alias, this);
        }

        @Override
        public MediaTemplateImportCommandPath as(Table<?> alias) {
            return new MediaTemplateImportCommandPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<MediaTemplateImportCommandRecord> getPrimaryKey() {
        return Keys.MEDIA_TEMPLATE_IMPORT_COMMAND_PKEY;
    }

    @Override
    public List<UniqueKey<MediaTemplateImportCommandRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.MEDIA_TEMPLATE_IMPORT_COMMAND_PROJECT_ID_COMMAND_KEY_KEY);
    }

    @Override
    public List<ForeignKey<MediaTemplateImportCommandRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MEDIA_TEMPLATE_IMPORT_COMMAND__MEDIA_TEMPLATE_IMPORT_COMMAND_OWNER_ID_FKEY, Keys.MEDIA_TEMPLATE_IMPORT_COMMAND__MEDIA_TEMPLATE_IMPORT_COMMAND_PROJECT_ID_FKEY);
    }

    private transient AppUserPath _appUser;

    /**
     * Get the implicit join path to the <code>public.app_user</code> table.
     */
    public AppUserPath appUser() {
        if (_appUser == null)
            _appUser = new AppUserPath(this, Keys.MEDIA_TEMPLATE_IMPORT_COMMAND__MEDIA_TEMPLATE_IMPORT_COMMAND_OWNER_ID_FKEY, null);

        return _appUser;
    }

    private transient ProjectPath _project;

    /**
     * Get the implicit join path to the <code>public.project</code> table.
     */
    public ProjectPath project() {
        if (_project == null)
            _project = new ProjectPath(this, Keys.MEDIA_TEMPLATE_IMPORT_COMMAND__MEDIA_TEMPLATE_IMPORT_COMMAND_PROJECT_ID_FKEY, null);

        return _project;
    }

    private transient MediaTemplateImportSourcePath _mediaTemplateImportSource;

    /**
     * Get the implicit to-many join path to the
     * <code>public.media_template_import_source</code> table
     */
    public MediaTemplateImportSourcePath mediaTemplateImportSource() {
        if (_mediaTemplateImportSource == null)
            _mediaTemplateImportSource = new MediaTemplateImportSourcePath(this, null, Keys.MEDIA_TEMPLATE_IMPORT_SOURCE__MEDIA_TEMPLATE_IMPORT_SOURCE_COMMAND_ID_FKEY.getInverseKey());

        return _mediaTemplateImportSource;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.media_template_image</code> table
     */
    public MediaTemplateImagePath mediaTemplateImage() {
        return mediaTemplateImportSource().mediaTemplateImage();
    }

    @Override
    public List<Check<MediaTemplateImportCommandRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("media_template_import_command_command_key_check"), "((length(btrim((command_key)::text)) > 0))", true),
            Internal.createCheck(this, DSL.name("media_template_import_command_input_json_check"), "(((jsonb_typeof(input_json) = 'object'::text) AND ((input_json ->> 'schemaVersion'::text) = '1'::text)))", true),
            Internal.createCheck(this, DSL.name("media_template_import_command_payload_hash_check"), "((payload_hash ~ '^[0-9a-f]{64}$'::text))", true),
            Internal.createCheck(this, DSL.name("media_template_import_command_result_json_check"), "(((result_json IS NULL) OR (jsonb_typeof(result_json) = 'object'::text)))", true)
        );
    }

    @Override
    public MediaTemplateImportCommand as(String alias) {
        return new MediaTemplateImportCommand(DSL.name(alias), this);
    }

    @Override
    public MediaTemplateImportCommand as(Name alias) {
        return new MediaTemplateImportCommand(alias, this);
    }

    @Override
    public MediaTemplateImportCommand as(Table<?> alias) {
        return new MediaTemplateImportCommand(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaTemplateImportCommand rename(String name) {
        return new MediaTemplateImportCommand(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaTemplateImportCommand rename(Name name) {
        return new MediaTemplateImportCommand(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaTemplateImportCommand rename(Table<?> name) {
        return new MediaTemplateImportCommand(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaTemplateImportCommand where(Condition condition) {
        return new MediaTemplateImportCommand(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaTemplateImportCommand where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaTemplateImportCommand where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaTemplateImportCommand where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaTemplateImportCommand where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaTemplateImportCommand where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaTemplateImportCommand where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaTemplateImportCommand where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaTemplateImportCommand whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaTemplateImportCommand whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
