/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables;


import dev.agenvas.db.Indexes;
import dev.agenvas.db.Keys;
import dev.agenvas.db.Public;
import dev.agenvas.db.tables.StorageProfile.StorageProfilePath;
import dev.agenvas.db.tables.records.MediaRelayObjectRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Temporary provider input copies registered before upload, retained for
 * durable cleanup
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MediaRelayObject extends TableImpl<MediaRelayObjectRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.media_relay_object</code>
     */
    public static final MediaRelayObject MEDIA_RELAY_OBJECT = new MediaRelayObject();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MediaRelayObjectRecord> getRecordType() {
        return MediaRelayObjectRecord.class;
    }

    /**
     * The column <code>public.media_relay_object.id</code>. Server-generated
     * copy identity
     */
    public final TableField<MediaRelayObjectRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "Server-generated copy identity");

    /**
     * The column <code>public.media_relay_object.profile_id</code>. Pinned
     * object storage connection for this temporary copy
     */
    public final TableField<MediaRelayObjectRecord, UUID> PROFILE_ID = createField(DSL.name("profile_id"), SQLDataType.UUID.nullable(false), this, "Pinned object storage connection for this temporary copy");

    /**
     * The column <code>public.media_relay_object.object_key</code>. Private
     * object key; never a URL or signature
     */
    public final TableField<MediaRelayObjectRecord, String> OBJECT_KEY = createField(DSL.name("object_key"), SQLDataType.CLOB.nullable(false), this, "Private object key; never a URL or signature");

    /**
     * The column <code>public.media_relay_object.expires_at</code>. Earliest
     * deletion time, later than provider input URL expiration
     */
    public final TableField<MediaRelayObjectRecord, OffsetDateTime> EXPIRES_AT = createField(DSL.name("expires_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "Earliest deletion time, later than provider input URL expiration");

    /**
     * The column <code>public.media_relay_object.created_at</code>. Copy
     * registration time before network upload
     */
    public final TableField<MediaRelayObjectRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "Copy registration time before network upload");

    private MediaRelayObject(Name alias, Table<MediaRelayObjectRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MediaRelayObject(Name alias, Table<MediaRelayObjectRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Temporary provider input copies registered before upload, retained for durable cleanup"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.media_relay_object</code> table reference
     */
    public MediaRelayObject(String alias) {
        this(DSL.name(alias), MEDIA_RELAY_OBJECT);
    }

    /**
     * Create an aliased <code>public.media_relay_object</code> table reference
     */
    public MediaRelayObject(Name alias) {
        this(alias, MEDIA_RELAY_OBJECT);
    }

    /**
     * Create a <code>public.media_relay_object</code> table reference
     */
    public MediaRelayObject() {
        this(DSL.name("media_relay_object"), null);
    }

    public <O extends Record> MediaRelayObject(Table<O> path, ForeignKey<O, MediaRelayObjectRecord> childPath, InverseForeignKey<O, MediaRelayObjectRecord> parentPath) {
        super(path, childPath, parentPath, MEDIA_RELAY_OBJECT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MediaRelayObjectPath extends MediaRelayObject implements Path<MediaRelayObjectRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MediaRelayObjectPath(Table<O> path, ForeignKey<O, MediaRelayObjectRecord> childPath, InverseForeignKey<O, MediaRelayObjectRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MediaRelayObjectPath(Name alias, Table<MediaRelayObjectRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MediaRelayObjectPath as(String alias) {
            return new MediaRelayObjectPath(DSL.name(alias), this);
        }

        @Override
        public MediaRelayObjectPath as(Name alias) {
            return new MediaRelayObjectPath(alias, this);
        }

        @Override
        public MediaRelayObjectPath as(Table<?> alias) {
            return new MediaRelayObjectPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MEDIA_RELAY_OBJECT_EXPIRY_IDX);
    }

    @Override
    public UniqueKey<MediaRelayObjectRecord> getPrimaryKey() {
        return Keys.MEDIA_RELAY_OBJECT_PKEY;
    }

    @Override
    public List<UniqueKey<MediaRelayObjectRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.MEDIA_RELAY_OBJECT_LOCATION_UNIQUE);
    }

    @Override
    public List<ForeignKey<MediaRelayObjectRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MEDIA_RELAY_OBJECT__MEDIA_RELAY_OBJECT_PROFILE_ID_FKEY);
    }

    private transient StorageProfilePath _storageProfile;

    /**
     * Get the implicit join path to the <code>public.storage_profile</code>
     * table.
     */
    public StorageProfilePath storageProfile() {
        if (_storageProfile == null)
            _storageProfile = new StorageProfilePath(this, Keys.MEDIA_RELAY_OBJECT__MEDIA_RELAY_OBJECT_PROFILE_ID_FKEY, null);

        return _storageProfile;
    }

    @Override
    public List<Check<MediaRelayObjectRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("media_relay_object_retention_check"), "((expires_at > created_at))", true)
        );
    }

    @Override
    public MediaRelayObject as(String alias) {
        return new MediaRelayObject(DSL.name(alias), this);
    }

    @Override
    public MediaRelayObject as(Name alias) {
        return new MediaRelayObject(alias, this);
    }

    @Override
    public MediaRelayObject as(Table<?> alias) {
        return new MediaRelayObject(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaRelayObject rename(String name) {
        return new MediaRelayObject(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaRelayObject rename(Name name) {
        return new MediaRelayObject(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaRelayObject rename(Table<?> name) {
        return new MediaRelayObject(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaRelayObject where(Condition condition) {
        return new MediaRelayObject(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaRelayObject where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaRelayObject where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaRelayObject where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaRelayObject where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaRelayObject where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaRelayObject where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaRelayObject where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaRelayObject whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaRelayObject whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
