/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables;


import dev.agenvas.db.Keys;
import dev.agenvas.db.Public;
import dev.agenvas.db.tables.MediaCapability.MediaCapabilityPath;
import dev.agenvas.db.tables.records.MediaCapabilityCreateKeyRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 媒体能力创建命令的幂等键与载荷摘要
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MediaCapabilityCreateKey extends TableImpl<MediaCapabilityCreateKeyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.media_capability_create_key</code>
     */
    public static final MediaCapabilityCreateKey MEDIA_CAPABILITY_CREATE_KEY = new MediaCapabilityCreateKey();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MediaCapabilityCreateKeyRecord> getRecordType() {
        return MediaCapabilityCreateKeyRecord.class;
    }

    /**
     * The column
     * <code>public.media_capability_create_key.idempotency_key</code>.
     * 作用域内的幂等命令键
     */
    public final TableField<MediaCapabilityCreateKeyRecord, String> IDEMPOTENCY_KEY = createField(DSL.name("idempotency_key"), SQLDataType.VARCHAR(160).nullable(false), this, "作用域内的幂等命令键");

    /**
     * The column
     * <code>public.media_capability_create_key.payload_sha256</code>. 规范化创建请求
     * SHA-256 摘要
     */
    public final TableField<MediaCapabilityCreateKeyRecord, String> PAYLOAD_SHA256 = createField(DSL.name("payload_sha256"), SQLDataType.CHAR(64).nullable(false), this, "规范化创建请求 SHA-256 摘要");

    /**
     * The column <code>public.media_capability_create_key.capability_id</code>.
     * 固定媒体能力身份
     */
    public final TableField<MediaCapabilityCreateKeyRecord, UUID> CAPABILITY_ID = createField(DSL.name("capability_id"), SQLDataType.UUID.nullable(false), this, "固定媒体能力身份");

    /**
     * The column <code>public.media_capability_create_key.created_at</code>.
     * 创建时间（UTC）
     */
    public final TableField<MediaCapabilityCreateKeyRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "创建时间（UTC）");

    private MediaCapabilityCreateKey(Name alias, Table<MediaCapabilityCreateKeyRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MediaCapabilityCreateKey(Name alias, Table<MediaCapabilityCreateKeyRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("媒体能力创建命令的幂等键与载荷摘要"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.media_capability_create_key</code> table
     * reference
     */
    public MediaCapabilityCreateKey(String alias) {
        this(DSL.name(alias), MEDIA_CAPABILITY_CREATE_KEY);
    }

    /**
     * Create an aliased <code>public.media_capability_create_key</code> table
     * reference
     */
    public MediaCapabilityCreateKey(Name alias) {
        this(alias, MEDIA_CAPABILITY_CREATE_KEY);
    }

    /**
     * Create a <code>public.media_capability_create_key</code> table reference
     */
    public MediaCapabilityCreateKey() {
        this(DSL.name("media_capability_create_key"), null);
    }

    public <O extends Record> MediaCapabilityCreateKey(Table<O> path, ForeignKey<O, MediaCapabilityCreateKeyRecord> childPath, InverseForeignKey<O, MediaCapabilityCreateKeyRecord> parentPath) {
        super(path, childPath, parentPath, MEDIA_CAPABILITY_CREATE_KEY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MediaCapabilityCreateKeyPath extends MediaCapabilityCreateKey implements Path<MediaCapabilityCreateKeyRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MediaCapabilityCreateKeyPath(Table<O> path, ForeignKey<O, MediaCapabilityCreateKeyRecord> childPath, InverseForeignKey<O, MediaCapabilityCreateKeyRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MediaCapabilityCreateKeyPath(Name alias, Table<MediaCapabilityCreateKeyRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MediaCapabilityCreateKeyPath as(String alias) {
            return new MediaCapabilityCreateKeyPath(DSL.name(alias), this);
        }

        @Override
        public MediaCapabilityCreateKeyPath as(Name alias) {
            return new MediaCapabilityCreateKeyPath(alias, this);
        }

        @Override
        public MediaCapabilityCreateKeyPath as(Table<?> alias) {
            return new MediaCapabilityCreateKeyPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<MediaCapabilityCreateKeyRecord> getPrimaryKey() {
        return Keys.MEDIA_CAPABILITY_CREATE_KEY_PKEY;
    }

    @Override
    public List<ForeignKey<MediaCapabilityCreateKeyRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MEDIA_CAPABILITY_CREATE_KEY__MEDIA_CAPABILITY_CREATE_KEY_CAPABILITY_ID_FKEY);
    }

    private transient MediaCapabilityPath _mediaCapability;

    /**
     * Get the implicit join path to the <code>public.media_capability</code>
     * table.
     */
    public MediaCapabilityPath mediaCapability() {
        if (_mediaCapability == null)
            _mediaCapability = new MediaCapabilityPath(this, Keys.MEDIA_CAPABILITY_CREATE_KEY__MEDIA_CAPABILITY_CREATE_KEY_CAPABILITY_ID_FKEY, null);

        return _mediaCapability;
    }

    @Override
    public List<Check<MediaCapabilityCreateKeyRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("media_capability_create_key_payload_sha256_check"), "((payload_sha256 ~ '^[0-9a-f]{64}$'::text))", true)
        );
    }

    @Override
    public MediaCapabilityCreateKey as(String alias) {
        return new MediaCapabilityCreateKey(DSL.name(alias), this);
    }

    @Override
    public MediaCapabilityCreateKey as(Name alias) {
        return new MediaCapabilityCreateKey(alias, this);
    }

    @Override
    public MediaCapabilityCreateKey as(Table<?> alias) {
        return new MediaCapabilityCreateKey(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaCapabilityCreateKey rename(String name) {
        return new MediaCapabilityCreateKey(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaCapabilityCreateKey rename(Name name) {
        return new MediaCapabilityCreateKey(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaCapabilityCreateKey rename(Table<?> name) {
        return new MediaCapabilityCreateKey(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaCapabilityCreateKey where(Condition condition) {
        return new MediaCapabilityCreateKey(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaCapabilityCreateKey where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaCapabilityCreateKey where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaCapabilityCreateKey where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaCapabilityCreateKey where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaCapabilityCreateKey where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaCapabilityCreateKey where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaCapabilityCreateKey where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaCapabilityCreateKey whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaCapabilityCreateKey whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
