/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables;


import dev.agenvas.db.Keys;
import dev.agenvas.db.Public;
import dev.agenvas.db.tables.MediaCapabilityCreateKey.MediaCapabilityCreateKeyPath;
import dev.agenvas.db.tables.MediaCapabilityVersion.MediaCapabilityVersionPath;
import dev.agenvas.db.tables.MediaDefault.MediaDefaultPath;
import dev.agenvas.db.tables.MediaDraft.MediaDraftPath;
import dev.agenvas.db.tables.MediaFunctionSetting.MediaFunctionSettingPath;
import dev.agenvas.db.tables.MediaProviderConnection.MediaProviderConnectionPath;
import dev.agenvas.db.tables.ProviderAttempt.ProviderAttemptPath;
import dev.agenvas.db.tables.Task.TaskPath;
import dev.agenvas.db.tables.records.MediaCapabilityRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 管理员媒体能力身份、可用状态和当前不可变版本
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MediaCapability extends TableImpl<MediaCapabilityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.media_capability</code>
     */
    public static final MediaCapability MEDIA_CAPABILITY = new MediaCapability();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MediaCapabilityRecord> getRecordType() {
        return MediaCapabilityRecord.class;
    }

    /**
     * The column <code>public.media_capability.id</code>. 记录身份
     */
    public final TableField<MediaCapabilityRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "记录身份");

    /**
     * The column <code>public.media_capability.connection_id</code>.
     * 不可变媒体连接所属身份或输入来源连线身份
     */
    public final TableField<MediaCapabilityRecord, UUID> CONNECTION_ID = createField(DSL.name("connection_id"), SQLDataType.UUID.nullable(false), this, "不可变媒体连接所属身份或输入来源连线身份");

    /**
     * The column <code>public.media_capability.name</code>. 显示名称
     */
    public final TableField<MediaCapabilityRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(160).nullable(false), this, "显示名称");

    /**
     * The column <code>public.media_capability.enabled</code>. 目录条目是否允许创建新任务
     */
    public final TableField<MediaCapabilityRecord, Boolean> ENABLED = createField(DSL.name("enabled"), SQLDataType.BOOLEAN.nullable(false), this, "目录条目是否允许创建新任务");

    /**
     * The column <code>public.media_capability.version</code>.
     * 乐观并发控制版本，更新时递增并校验预期值
     */
    public final TableField<MediaCapabilityRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT.nullable(false), this, "乐观并发控制版本，更新时递增并校验预期值");

    /**
     * The column <code>public.media_capability.current_version</code>.
     * 当前配置版本或单例配置版本计数
     */
    public final TableField<MediaCapabilityRecord, Integer> CURRENT_VERSION = createField(DSL.name("current_version"), SQLDataType.INTEGER.nullable(false), this, "当前配置版本或单例配置版本计数");

    /**
     * The column <code>public.media_capability.created_at</code>. 创建时间（UTC）
     */
    public final TableField<MediaCapabilityRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "创建时间（UTC）");

    /**
     * The column <code>public.media_capability.updated_at</code>.
     * 最后状态或配置更新时间（UTC）
     */
    public final TableField<MediaCapabilityRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "最后状态或配置更新时间（UTC）");

    /**
     * The column <code>public.media_capability.deleted_at</code>.
     * 能力删除时间；目录不再展示，历史任务保留不可变版本用于恢复
     */
    public final TableField<MediaCapabilityRecord, OffsetDateTime> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "能力删除时间；目录不再展示，历史任务保留不可变版本用于恢复");

    private MediaCapability(Name alias, Table<MediaCapabilityRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MediaCapability(Name alias, Table<MediaCapabilityRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("管理员媒体能力身份、可用状态和当前不可变版本"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.media_capability</code> table reference
     */
    public MediaCapability(String alias) {
        this(DSL.name(alias), MEDIA_CAPABILITY);
    }

    /**
     * Create an aliased <code>public.media_capability</code> table reference
     */
    public MediaCapability(Name alias) {
        this(alias, MEDIA_CAPABILITY);
    }

    /**
     * Create a <code>public.media_capability</code> table reference
     */
    public MediaCapability() {
        this(DSL.name("media_capability"), null);
    }

    public <O extends Record> MediaCapability(Table<O> path, ForeignKey<O, MediaCapabilityRecord> childPath, InverseForeignKey<O, MediaCapabilityRecord> parentPath) {
        super(path, childPath, parentPath, MEDIA_CAPABILITY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MediaCapabilityPath extends MediaCapability implements Path<MediaCapabilityRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MediaCapabilityPath(Table<O> path, ForeignKey<O, MediaCapabilityRecord> childPath, InverseForeignKey<O, MediaCapabilityRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MediaCapabilityPath(Name alias, Table<MediaCapabilityRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MediaCapabilityPath as(String alias) {
            return new MediaCapabilityPath(DSL.name(alias), this);
        }

        @Override
        public MediaCapabilityPath as(Name alias) {
            return new MediaCapabilityPath(alias, this);
        }

        @Override
        public MediaCapabilityPath as(Table<?> alias) {
            return new MediaCapabilityPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<MediaCapabilityRecord> getPrimaryKey() {
        return Keys.MEDIA_CAPABILITY_PKEY;
    }

    @Override
    public List<UniqueKey<MediaCapabilityRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UQ_MEDIA_CAPABILITY_CONNECTION_ID);
    }

    @Override
    public List<ForeignKey<MediaCapabilityRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MEDIA_CAPABILITY__MEDIA_CAPABILITY_CONNECTION_ID_FKEY);
    }

    private transient MediaProviderConnectionPath _mediaProviderConnection;

    /**
     * Get the implicit join path to the
     * <code>public.media_provider_connection</code> table.
     */
    public MediaProviderConnectionPath mediaProviderConnection() {
        if (_mediaProviderConnection == null)
            _mediaProviderConnection = new MediaProviderConnectionPath(this, Keys.MEDIA_CAPABILITY__MEDIA_CAPABILITY_CONNECTION_ID_FKEY, null);

        return _mediaProviderConnection;
    }

    private transient MediaDraftPath _mediaDraft;

    /**
     * Get the implicit to-many join path to the <code>public.media_draft</code>
     * table
     */
    public MediaDraftPath mediaDraft() {
        if (_mediaDraft == null)
            _mediaDraft = new MediaDraftPath(this, null, Keys.MEDIA_DRAFT__FK_MEDIA_DRAFT_CAPABILITY.getInverseKey());

        return _mediaDraft;
    }

    private transient ProviderAttemptPath _providerAttempt;

    /**
     * Get the implicit to-many join path to the
     * <code>public.provider_attempt</code> table
     */
    public ProviderAttemptPath providerAttempt() {
        if (_providerAttempt == null)
            _providerAttempt = new ProviderAttemptPath(this, null, Keys.PROVIDER_ATTEMPT__FK_PROVIDER_ATTEMPT_MEDIA_OWNER.getInverseKey());

        return _providerAttempt;
    }

    private transient TaskPath _task;

    /**
     * Get the implicit to-many join path to the <code>public.task</code> table
     */
    public TaskPath task() {
        if (_task == null)
            _task = new TaskPath(this, null, Keys.TASK__FK_TASK_MEDIA_OWNER.getInverseKey());

        return _task;
    }

    private transient MediaCapabilityCreateKeyPath _mediaCapabilityCreateKey;

    /**
     * Get the implicit to-many join path to the
     * <code>public.media_capability_create_key</code> table
     */
    public MediaCapabilityCreateKeyPath mediaCapabilityCreateKey() {
        if (_mediaCapabilityCreateKey == null)
            _mediaCapabilityCreateKey = new MediaCapabilityCreateKeyPath(this, null, Keys.MEDIA_CAPABILITY_CREATE_KEY__MEDIA_CAPABILITY_CREATE_KEY_CAPABILITY_ID_FKEY.getInverseKey());

        return _mediaCapabilityCreateKey;
    }

    private transient MediaCapabilityVersionPath _mediaCapabilityVersion;

    /**
     * Get the implicit to-many join path to the
     * <code>public.media_capability_version</code> table
     */
    public MediaCapabilityVersionPath mediaCapabilityVersion() {
        if (_mediaCapabilityVersion == null)
            _mediaCapabilityVersion = new MediaCapabilityVersionPath(this, null, Keys.MEDIA_CAPABILITY_VERSION__MEDIA_CAPABILITY_VERSION_CAPABILITY_ID_FKEY.getInverseKey());

        return _mediaCapabilityVersion;
    }

    private transient MediaDefaultPath _mediaDefault;

    /**
     * Get the implicit to-many join path to the
     * <code>public.media_default</code> table
     */
    public MediaDefaultPath mediaDefault() {
        if (_mediaDefault == null)
            _mediaDefault = new MediaDefaultPath(this, null, Keys.MEDIA_DEFAULT__MEDIA_DEFAULT_CAPABILITY_ID_FKEY.getInverseKey());

        return _mediaDefault;
    }

    private transient MediaFunctionSettingPath _mediaFunctionSetting;

    /**
     * Get the implicit to-many join path to the
     * <code>public.media_function_setting</code> table
     */
    public MediaFunctionSettingPath mediaFunctionSetting() {
        if (_mediaFunctionSetting == null)
            _mediaFunctionSetting = new MediaFunctionSettingPath(this, null, Keys.MEDIA_FUNCTION_SETTING__MEDIA_FUNCTION_SETTING_CAPABILITY_ID_FKEY.getInverseKey());

        return _mediaFunctionSetting;
    }

    @Override
    public List<Check<MediaCapabilityRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("media_capability_current_version_check"), "((current_version > 0))", true),
            Internal.createCheck(this, DSL.name("media_capability_name_check"), "((length(btrim((name)::text)) > 0))", true),
            Internal.createCheck(this, DSL.name("media_capability_version_check"), "((version >= 0))", true)
        );
    }

    @Override
    public MediaCapability as(String alias) {
        return new MediaCapability(DSL.name(alias), this);
    }

    @Override
    public MediaCapability as(Name alias) {
        return new MediaCapability(alias, this);
    }

    @Override
    public MediaCapability as(Table<?> alias) {
        return new MediaCapability(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaCapability rename(String name) {
        return new MediaCapability(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaCapability rename(Name name) {
        return new MediaCapability(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaCapability rename(Table<?> name) {
        return new MediaCapability(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaCapability where(Condition condition) {
        return new MediaCapability(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaCapability where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaCapability where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaCapability where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaCapability where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaCapability where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaCapability where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaCapability where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaCapability whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaCapability whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
