/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables;


import dev.agenvas.db.Keys;
import dev.agenvas.db.Public;
import dev.agenvas.db.tables.ArtifactVersion.ArtifactVersionPath;
import dev.agenvas.db.tables.records.MediaTemplateImportImageRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Template provenance with no LibraryEntry dependency; template deletion never
 * deletes project versions
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MediaTemplateImportImage extends TableImpl<MediaTemplateImportImageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.media_template_import_image</code>
     */
    public static final MediaTemplateImportImage MEDIA_TEMPLATE_IMPORT_IMAGE = new MediaTemplateImportImage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MediaTemplateImportImageRecord> getRecordType() {
        return MediaTemplateImportImageRecord.class;
    }

    /**
     * The column <code>public.media_template_import_image.project_id</code>.
     */
    public final TableField<MediaTemplateImportImageRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.media_template_import_image.version_id</code>.
     */
    public final TableField<MediaTemplateImportImageRecord, UUID> VERSION_ID = createField(DSL.name("version_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.media_template_import_image.template_id</code>.
     */
    public final TableField<MediaTemplateImportImageRecord, UUID> TEMPLATE_ID = createField(DSL.name("template_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column
     * <code>public.media_template_import_image.template_version</code>.
     */
    public final TableField<MediaTemplateImportImageRecord, Long> TEMPLATE_VERSION = createField(DSL.name("template_version"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.media_template_import_image.template_name</code>.
     */
    public final TableField<MediaTemplateImportImageRecord, String> TEMPLATE_NAME = createField(DSL.name("template_name"), SQLDataType.VARCHAR(160).nullable(false), this, "");

    private MediaTemplateImportImage(Name alias, Table<MediaTemplateImportImageRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MediaTemplateImportImage(Name alias, Table<MediaTemplateImportImageRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Template provenance with no LibraryEntry dependency; template deletion never deletes project versions"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.media_template_import_image</code> table
     * reference
     */
    public MediaTemplateImportImage(String alias) {
        this(DSL.name(alias), MEDIA_TEMPLATE_IMPORT_IMAGE);
    }

    /**
     * Create an aliased <code>public.media_template_import_image</code> table
     * reference
     */
    public MediaTemplateImportImage(Name alias) {
        this(alias, MEDIA_TEMPLATE_IMPORT_IMAGE);
    }

    /**
     * Create a <code>public.media_template_import_image</code> table reference
     */
    public MediaTemplateImportImage() {
        this(DSL.name("media_template_import_image"), null);
    }

    public <O extends Record> MediaTemplateImportImage(Table<O> path, ForeignKey<O, MediaTemplateImportImageRecord> childPath, InverseForeignKey<O, MediaTemplateImportImageRecord> parentPath) {
        super(path, childPath, parentPath, MEDIA_TEMPLATE_IMPORT_IMAGE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MediaTemplateImportImagePath extends MediaTemplateImportImage implements Path<MediaTemplateImportImageRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MediaTemplateImportImagePath(Table<O> path, ForeignKey<O, MediaTemplateImportImageRecord> childPath, InverseForeignKey<O, MediaTemplateImportImageRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MediaTemplateImportImagePath(Name alias, Table<MediaTemplateImportImageRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MediaTemplateImportImagePath as(String alias) {
            return new MediaTemplateImportImagePath(DSL.name(alias), this);
        }

        @Override
        public MediaTemplateImportImagePath as(Name alias) {
            return new MediaTemplateImportImagePath(alias, this);
        }

        @Override
        public MediaTemplateImportImagePath as(Table<?> alias) {
            return new MediaTemplateImportImagePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<MediaTemplateImportImageRecord> getPrimaryKey() {
        return Keys.MEDIA_TEMPLATE_IMPORT_IMAGE_PKEY;
    }

    @Override
    public List<ForeignKey<MediaTemplateImportImageRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MEDIA_TEMPLATE_IMPORT_IMAGE__MEDIA_TEMPLATE_IMPORT_IMAGE_PROJECT_ID_VERSION_ID_FKEY);
    }

    private transient ArtifactVersionPath _artifactVersion;

    /**
     * Get the implicit join path to the <code>public.artifact_version</code>
     * table.
     */
    public ArtifactVersionPath artifactVersion() {
        if (_artifactVersion == null)
            _artifactVersion = new ArtifactVersionPath(this, Keys.MEDIA_TEMPLATE_IMPORT_IMAGE__MEDIA_TEMPLATE_IMPORT_IMAGE_PROJECT_ID_VERSION_ID_FKEY, null);

        return _artifactVersion;
    }

    @Override
    public List<Check<MediaTemplateImportImageRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("media_template_import_image_template_version_check"), "((template_version >= 0))", true)
        );
    }

    @Override
    public MediaTemplateImportImage as(String alias) {
        return new MediaTemplateImportImage(DSL.name(alias), this);
    }

    @Override
    public MediaTemplateImportImage as(Name alias) {
        return new MediaTemplateImportImage(alias, this);
    }

    @Override
    public MediaTemplateImportImage as(Table<?> alias) {
        return new MediaTemplateImportImage(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaTemplateImportImage rename(String name) {
        return new MediaTemplateImportImage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaTemplateImportImage rename(Name name) {
        return new MediaTemplateImportImage(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaTemplateImportImage rename(Table<?> name) {
        return new MediaTemplateImportImage(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaTemplateImportImage where(Condition condition) {
        return new MediaTemplateImportImage(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaTemplateImportImage where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaTemplateImportImage where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaTemplateImportImage where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaTemplateImportImage where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaTemplateImportImage where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaTemplateImportImage where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaTemplateImportImage where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaTemplateImportImage whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaTemplateImportImage whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
