/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables;


import dev.agenvas.db.Indexes;
import dev.agenvas.db.Keys;
import dev.agenvas.db.Public;
import dev.agenvas.db.tables.Project.ProjectPath;
import dev.agenvas.db.tables.records.ProjectEventRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 与业务变化同事务提交的项目事件，项目内序号作为 SSE 水位
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProjectEvent extends TableImpl<ProjectEventRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.project_event</code>
     */
    public static final ProjectEvent PROJECT_EVENT = new ProjectEvent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProjectEventRecord> getRecordType() {
        return ProjectEventRecord.class;
    }

    /**
     * The column <code>public.project_event.project_id</code>. 所属项目及授权作用域
     */
    public final TableField<ProjectEventRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "所属项目及授权作用域");

    /**
     * The column <code>public.project_event.seq</code>. Commit-safe
     * project-local waterline allocated while holding the project row lock.
     */
    public final TableField<ProjectEventRecord, Long> SEQ = createField(DSL.name("seq"), SQLDataType.BIGINT.nullable(false), this, "Commit-safe project-local waterline allocated while holding the project row lock.");

    /**
     * The column <code>public.project_event.event_id</code>. 事件全局去重身份
     */
    public final TableField<ProjectEventRecord, UUID> EVENT_ID = createField(DSL.name("event_id"), SQLDataType.UUID.nullable(false), this, "事件全局去重身份");

    /**
     * The column <code>public.project_event.type</code>. 项目事件类型
     */
    public final TableField<ProjectEventRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(120).nullable(false), this, "项目事件类型");

    /**
     * The column <code>public.project_event.schema_version</code>. 持久 JSON
     * 内容格式版本
     */
    public final TableField<ProjectEventRecord, Integer> SCHEMA_VERSION = createField(DSL.name("schema_version"), SQLDataType.INTEGER.nullable(false), this, "持久 JSON 内容格式版本");

    /**
     * The column <code>public.project_event.aggregate_id</code>. 变化的业务对象身份
     */
    public final TableField<ProjectEventRecord, UUID> AGGREGATE_ID = createField(DSL.name("aggregate_id"), SQLDataType.UUID.nullable(false), this, "变化的业务对象身份");

    /**
     * The column <code>public.project_event.aggregate_version</code>. 变化对象的并发版本
     */
    public final TableField<ProjectEventRecord, Long> AGGREGATE_VERSION = createField(DSL.name("aggregate_version"), SQLDataType.BIGINT.nullable(false), this, "变化对象的并发版本");

    /**
     * The column <code>public.project_event.payload_json</code>.
     * 与业务变更同事务提交的公开事件载荷
     */
    public final TableField<ProjectEventRecord, JSONB> PAYLOAD_JSON = createField(DSL.name("payload_json"), SQLDataType.JSONB.nullable(false), this, "与业务变更同事务提交的公开事件载荷");

    /**
     * The column <code>public.project_event.occurred_at</code>. 业务事件发生时间
     */
    public final TableField<ProjectEventRecord, OffsetDateTime> OCCURRED_AT = createField(DSL.name("occurred_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "业务事件发生时间");

    private ProjectEvent(Name alias, Table<ProjectEventRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ProjectEvent(Name alias, Table<ProjectEventRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("与业务变化同事务提交的项目事件，项目内序号作为 SSE 水位"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.project_event</code> table reference
     */
    public ProjectEvent(String alias) {
        this(DSL.name(alias), PROJECT_EVENT);
    }

    /**
     * Create an aliased <code>public.project_event</code> table reference
     */
    public ProjectEvent(Name alias) {
        this(alias, PROJECT_EVENT);
    }

    /**
     * Create a <code>public.project_event</code> table reference
     */
    public ProjectEvent() {
        this(DSL.name("project_event"), null);
    }

    public <O extends Record> ProjectEvent(Table<O> path, ForeignKey<O, ProjectEventRecord> childPath, InverseForeignKey<O, ProjectEventRecord> parentPath) {
        super(path, childPath, parentPath, PROJECT_EVENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ProjectEventPath extends ProjectEvent implements Path<ProjectEventRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ProjectEventPath(Table<O> path, ForeignKey<O, ProjectEventRecord> childPath, InverseForeignKey<O, ProjectEventRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ProjectEventPath(Name alias, Table<ProjectEventRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ProjectEventPath as(String alias) {
            return new ProjectEventPath(DSL.name(alias), this);
        }

        @Override
        public ProjectEventPath as(Name alias) {
            return new ProjectEventPath(alias, this);
        }

        @Override
        public ProjectEventPath as(Table<?> alias) {
            return new ProjectEventPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IX_PROJECT_EVENT_OCCURRED_AT);
    }

    @Override
    public UniqueKey<ProjectEventRecord> getPrimaryKey() {
        return Keys.PROJECT_EVENT_PKEY;
    }

    @Override
    public List<UniqueKey<ProjectEventRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UQ_PROJECT_EVENT_ID);
    }

    @Override
    public List<ForeignKey<ProjectEventRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PROJECT_EVENT__FK_PROJECT_EVENT_PROJECT);
    }

    private transient ProjectPath _project;

    /**
     * Get the implicit join path to the <code>public.project</code> table.
     */
    public ProjectPath project() {
        if (_project == null)
            _project = new ProjectPath(this, Keys.PROJECT_EVENT__FK_PROJECT_EVENT_PROJECT, null);

        return _project;
    }

    @Override
    public List<Check<ProjectEventRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("ck_project_event_aggregate_version_non_negative"), "((aggregate_version >= 0))", true),
            Internal.createCheck(this, DSL.name("ck_project_event_payload_object"), "((jsonb_typeof(payload_json) = 'object'::text))", true),
            Internal.createCheck(this, DSL.name("ck_project_event_schema_version_positive"), "((schema_version > 0))", true),
            Internal.createCheck(this, DSL.name("ck_project_event_seq_positive"), "((seq > 0))", true),
            Internal.createCheck(this, DSL.name("ck_project_event_type_not_blank"), "((length(btrim((type)::text)) > 0))", true)
        );
    }

    @Override
    public ProjectEvent as(String alias) {
        return new ProjectEvent(DSL.name(alias), this);
    }

    @Override
    public ProjectEvent as(Name alias) {
        return new ProjectEvent(alias, this);
    }

    @Override
    public ProjectEvent as(Table<?> alias) {
        return new ProjectEvent(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProjectEvent rename(String name) {
        return new ProjectEvent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProjectEvent rename(Name name) {
        return new ProjectEvent(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProjectEvent rename(Table<?> name) {
        return new ProjectEvent(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProjectEvent where(Condition condition) {
        return new ProjectEvent(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProjectEvent where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProjectEvent where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProjectEvent where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProjectEvent where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProjectEvent where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProjectEvent where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProjectEvent where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProjectEvent whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProjectEvent whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
