/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables;


import dev.agenvas.db.Keys;
import dev.agenvas.db.Public;
import dev.agenvas.db.tables.records.PromptDefinitionRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 统一管理 Agent 与功能的创作提示词；消费者按稳定用途标识取用并冻结正文
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PromptDefinition extends TableImpl<PromptDefinitionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.prompt_definition</code>
     */
    public static final PromptDefinition PROMPT_DEFINITION = new PromptDefinition();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PromptDefinitionRecord> getRecordType() {
        return PromptDefinitionRecord.class;
    }

    /**
     * The column <code>public.prompt_definition.id</code>. 提示词条目身份
     */
    public final TableField<PromptDefinitionRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "提示词条目身份");

    /**
     * The column <code>public.prompt_definition.key</code>.
     * 不可变且全局唯一的用途标识，供消费者明确选用
     */
    public final TableField<PromptDefinitionRecord, String> KEY = createField(DSL.name("key"), SQLDataType.VARCHAR(120).nullable(false), this, "不可变且全局唯一的用途标识，供消费者明确选用");

    /**
     * The column <code>public.prompt_definition.kind</code>. 提示词用途类型：Agent
     * 默认配置或功能提示词
     */
    public final TableField<PromptDefinitionRecord, String> KIND = createField(DSL.name("kind"), SQLDataType.VARCHAR(16).nullable(false), this, "提示词用途类型：Agent 默认配置或功能提示词");

    /**
     * The column <code>public.prompt_definition.name</code>. 管理列表及新建 Agent
     * 的展示名称
     */
    public final TableField<PromptDefinitionRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(120).nullable(false), this, "管理列表及新建 Agent 的展示名称");

    /**
     * The column <code>public.prompt_definition.description</code>. 提示词的用途说明
     */
    public final TableField<PromptDefinitionRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(1000).nullable(false).defaultValue(DSL.field(DSL.raw("''::character varying"), SQLDataType.VARCHAR)), this, "提示词的用途说明");

    /**
     * The column <code>public.prompt_definition.content</code>. 可编辑创作提示词正文
     */
    public final TableField<PromptDefinitionRecord, String> CONTENT = createField(DSL.name("content"), SQLDataType.CLOB.nullable(false), this, "可编辑创作提示词正文");

    /**
     * The column <code>public.prompt_definition.built_in</code>.
     * 内置消费入口需要的条目，不可删除
     */
    public final TableField<PromptDefinitionRecord, Boolean> BUILT_IN = createField(DSL.name("built_in"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "内置消费入口需要的条目，不可删除");

    /**
     * The column <code>public.prompt_definition.version</code>. 乐观编辑和删除版本
     */
    public final TableField<PromptDefinitionRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.BIGINT)), this, "乐观编辑和删除版本");

    /**
     * The column <code>public.prompt_definition.created_at</code>. 创建时间
     */
    public final TableField<PromptDefinitionRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "创建时间");

    /**
     * The column <code>public.prompt_definition.updated_at</code>. 最近一次编辑时间
     */
    public final TableField<PromptDefinitionRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "最近一次编辑时间");

    private PromptDefinition(Name alias, Table<PromptDefinitionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PromptDefinition(Name alias, Table<PromptDefinitionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("统一管理 Agent 与功能的创作提示词；消费者按稳定用途标识取用并冻结正文"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.prompt_definition</code> table reference
     */
    public PromptDefinition(String alias) {
        this(DSL.name(alias), PROMPT_DEFINITION);
    }

    /**
     * Create an aliased <code>public.prompt_definition</code> table reference
     */
    public PromptDefinition(Name alias) {
        this(alias, PROMPT_DEFINITION);
    }

    /**
     * Create a <code>public.prompt_definition</code> table reference
     */
    public PromptDefinition() {
        this(DSL.name("prompt_definition"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<PromptDefinitionRecord> getPrimaryKey() {
        return Keys.PROMPT_DEFINITION_PKEY;
    }

    @Override
    public List<UniqueKey<PromptDefinitionRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.PROMPT_DEFINITION_KEY_KEY);
    }

    @Override
    public List<Check<PromptDefinitionRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("prompt_definition_content_check"), "(((length(btrim(content)) >= 1) AND (length(btrim(content)) <= 8000)))", true),
            Internal.createCheck(this, DSL.name("prompt_definition_key_check"), "(((key)::text ~ '^[a-z][a-z0-9._-]{0,119}$'::text))", true),
            Internal.createCheck(this, DSL.name("prompt_definition_kind_check"), "(((kind)::text = ANY ((ARRAY['AGENT'::character varying, 'FUNCTION'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("prompt_definition_name_check"), "(((length(btrim((name)::text)) >= 1) AND (length(btrim((name)::text)) <= 120)))", true),
            Internal.createCheck(this, DSL.name("prompt_definition_version_check"), "((version > 0))", true)
        );
    }

    @Override
    public PromptDefinition as(String alias) {
        return new PromptDefinition(DSL.name(alias), this);
    }

    @Override
    public PromptDefinition as(Name alias) {
        return new PromptDefinition(alias, this);
    }

    @Override
    public PromptDefinition as(Table<?> alias) {
        return new PromptDefinition(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PromptDefinition rename(String name) {
        return new PromptDefinition(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PromptDefinition rename(Name name) {
        return new PromptDefinition(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PromptDefinition rename(Table<?> name) {
        return new PromptDefinition(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PromptDefinition where(Condition condition) {
        return new PromptDefinition(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PromptDefinition where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PromptDefinition where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PromptDefinition where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PromptDefinition where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PromptDefinition where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PromptDefinition where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PromptDefinition where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PromptDefinition whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PromptDefinition whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
