/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables;


import dev.agenvas.db.Indexes;
import dev.agenvas.db.Keys;
import dev.agenvas.db.Public;
import dev.agenvas.db.tables.MediaCapability.MediaCapabilityPath;
import dev.agenvas.db.tables.MediaCapabilityVersion.MediaCapabilityVersionPath;
import dev.agenvas.db.tables.MediaProviderConnectionVersion.MediaProviderConnectionVersionPath;
import dev.agenvas.db.tables.Task.TaskPath;
import dev.agenvas.db.tables.records.ProviderAttemptRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 固定任务租约和连接能力版本的外部提交尝试；结果未知时禁止自动重提
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProviderAttempt extends TableImpl<ProviderAttemptRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.provider_attempt</code>
     */
    public static final ProviderAttempt PROVIDER_ATTEMPT = new ProviderAttempt();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProviderAttemptRecord> getRecordType() {
        return ProviderAttemptRecord.class;
    }

    /**
     * The column <code>public.provider_attempt.id</code>. 记录身份
     */
    public final TableField<ProviderAttemptRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "记录身份");

    /**
     * The column <code>public.provider_attempt.project_id</code>. 所属项目及授权作用域
     */
    public final TableField<ProviderAttemptRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "所属项目及授权作用域");

    /**
     * The column <code>public.provider_attempt.task_id</code>. 持久任务身份
     */
    public final TableField<ProviderAttemptRecord, UUID> TASK_ID = createField(DSL.name("task_id"), SQLDataType.UUID.nullable(false), this, "持久任务身份");

    /**
     * The column <code>public.provider_attempt.lease_epoch</code>. 任务租约 fencing
     * epoch，旧 Worker 不得回写结果
     */
    public final TableField<ProviderAttemptRecord, Long> LEASE_EPOCH = createField(DSL.name("lease_epoch"), SQLDataType.BIGINT.nullable(false), this, "任务租约 fencing epoch，旧 Worker 不得回写结果");

    /**
     * The column <code>public.provider_attempt.status</code>. REJECTED is an
     * explicit provider rejection; uncertain transport failures remain UNKNOWN.
     */
    public final TableField<ProviderAttemptRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(24).nullable(false), this, "REJECTED is an explicit provider rejection; uncertain transport failures remain UNKNOWN.");

    /**
     * The column <code>public.provider_attempt.request_key</code>.
     * 在外部调用前已提交的稳定请求去重键
     */
    public final TableField<ProviderAttemptRecord, UUID> REQUEST_KEY = createField(DSL.name("request_key"), SQLDataType.UUID.nullable(false), this, "在外部调用前已提交的稳定请求去重键");

    /**
     * The column <code>public.provider_attempt.provider_request_id</code>.
     * 外部已受理请求标识，供状态查询与结果归档
     */
    public final TableField<ProviderAttemptRecord, String> PROVIDER_REQUEST_ID = createField(DSL.name("provider_request_id"), SQLDataType.VARCHAR(240), this, "外部已受理请求标识，供状态查询与结果归档");

    /**
     * The column <code>public.provider_attempt.created_at</code>. 创建时间（UTC）
     */
    public final TableField<ProviderAttemptRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "创建时间（UTC）");

    /**
     * The column <code>public.provider_attempt.updated_at</code>.
     * 最后状态或配置更新时间（UTC）
     */
    public final TableField<ProviderAttemptRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "最后状态或配置更新时间（UTC）");

    /**
     * The column <code>public.provider_attempt.capability_id</code>. 固定媒体能力身份
     */
    public final TableField<ProviderAttemptRecord, UUID> CAPABILITY_ID = createField(DSL.name("capability_id"), SQLDataType.UUID, this, "固定媒体能力身份");

    /**
     * The column <code>public.provider_attempt.capability_version</code>.
     * 固定的不可变媒体能力版本
     */
    public final TableField<ProviderAttemptRecord, Integer> CAPABILITY_VERSION = createField(DSL.name("capability_version"), SQLDataType.INTEGER, this, "固定的不可变媒体能力版本");

    /**
     * The column <code>public.provider_attempt.connection_id</code>.
     * 不可变媒体连接所属身份或输入来源连线身份
     */
    public final TableField<ProviderAttemptRecord, UUID> CONNECTION_ID = createField(DSL.name("connection_id"), SQLDataType.UUID, this, "不可变媒体连接所属身份或输入来源连线身份");

    /**
     * The column <code>public.provider_attempt.connection_version</code>.
     * 任务固定使用的不可变媒体连接版本
     */
    public final TableField<ProviderAttemptRecord, Integer> CONNECTION_VERSION = createField(DSL.name("connection_version"), SQLDataType.INTEGER, this, "任务固定使用的不可变媒体连接版本");

    private ProviderAttempt(Name alias, Table<ProviderAttemptRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ProviderAttempt(Name alias, Table<ProviderAttemptRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("固定任务租约和连接能力版本的外部提交尝试；结果未知时禁止自动重提"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.provider_attempt</code> table reference
     */
    public ProviderAttempt(String alias) {
        this(DSL.name(alias), PROVIDER_ATTEMPT);
    }

    /**
     * Create an aliased <code>public.provider_attempt</code> table reference
     */
    public ProviderAttempt(Name alias) {
        this(alias, PROVIDER_ATTEMPT);
    }

    /**
     * Create a <code>public.provider_attempt</code> table reference
     */
    public ProviderAttempt() {
        this(DSL.name("provider_attempt"), null);
    }

    public <O extends Record> ProviderAttempt(Table<O> path, ForeignKey<O, ProviderAttemptRecord> childPath, InverseForeignKey<O, ProviderAttemptRecord> parentPath) {
        super(path, childPath, parentPath, PROVIDER_ATTEMPT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ProviderAttemptPath extends ProviderAttempt implements Path<ProviderAttemptRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ProviderAttemptPath(Table<O> path, ForeignKey<O, ProviderAttemptRecord> childPath, InverseForeignKey<O, ProviderAttemptRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ProviderAttemptPath(Name alias, Table<ProviderAttemptRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ProviderAttemptPath as(String alias) {
            return new ProviderAttemptPath(DSL.name(alias), this);
        }

        @Override
        public ProviderAttemptPath as(Name alias) {
            return new ProviderAttemptPath(alias, this);
        }

        @Override
        public ProviderAttemptPath as(Table<?> alias) {
            return new ProviderAttemptPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IX_PROVIDER_ATTEMPT_TASK);
    }

    @Override
    public UniqueKey<ProviderAttemptRecord> getPrimaryKey() {
        return Keys.PROVIDER_ATTEMPT_PKEY;
    }

    @Override
    public List<UniqueKey<ProviderAttemptRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UQ_PROVIDER_ATTEMPT_EPOCH, Keys.UQ_PROVIDER_ATTEMPT_REQUEST_KEY);
    }

    @Override
    public List<ForeignKey<ProviderAttemptRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PROVIDER_ATTEMPT__FK_PROVIDER_ATTEMPT_MEDIA_CAPABILITY, Keys.PROVIDER_ATTEMPT__FK_PROVIDER_ATTEMPT_MEDIA_CONNECTION, Keys.PROVIDER_ATTEMPT__FK_PROVIDER_ATTEMPT_MEDIA_OWNER, Keys.PROVIDER_ATTEMPT__FK_PROVIDER_ATTEMPT_TASK);
    }

    private transient MediaCapabilityVersionPath _mediaCapabilityVersion;

    /**
     * Get the implicit join path to the
     * <code>public.media_capability_version</code> table.
     */
    public MediaCapabilityVersionPath mediaCapabilityVersion() {
        if (_mediaCapabilityVersion == null)
            _mediaCapabilityVersion = new MediaCapabilityVersionPath(this, Keys.PROVIDER_ATTEMPT__FK_PROVIDER_ATTEMPT_MEDIA_CAPABILITY, null);

        return _mediaCapabilityVersion;
    }

    private transient MediaProviderConnectionVersionPath _mediaProviderConnectionVersion;

    /**
     * Get the implicit join path to the
     * <code>public.media_provider_connection_version</code> table.
     */
    public MediaProviderConnectionVersionPath mediaProviderConnectionVersion() {
        if (_mediaProviderConnectionVersion == null)
            _mediaProviderConnectionVersion = new MediaProviderConnectionVersionPath(this, Keys.PROVIDER_ATTEMPT__FK_PROVIDER_ATTEMPT_MEDIA_CONNECTION, null);

        return _mediaProviderConnectionVersion;
    }

    private transient MediaCapabilityPath _mediaCapability;

    /**
     * Get the implicit join path to the <code>public.media_capability</code>
     * table.
     */
    public MediaCapabilityPath mediaCapability() {
        if (_mediaCapability == null)
            _mediaCapability = new MediaCapabilityPath(this, Keys.PROVIDER_ATTEMPT__FK_PROVIDER_ATTEMPT_MEDIA_OWNER, null);

        return _mediaCapability;
    }

    private transient TaskPath _task;

    /**
     * Get the implicit join path to the <code>public.task</code> table.
     */
    public TaskPath task() {
        if (_task == null)
            _task = new TaskPath(this, Keys.PROVIDER_ATTEMPT__FK_PROVIDER_ATTEMPT_TASK, null);

        return _task;
    }

    @Override
    public List<Check<ProviderAttemptRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("ck_provider_attempt_media_binding"), "((((capability_id IS NULL) AND (capability_version IS NULL) AND (connection_id IS NULL) AND (connection_version IS NULL)) OR ((capability_id IS NOT NULL) AND (capability_version IS NOT NULL) AND (connection_id IS NOT NULL) AND (connection_version IS NOT NULL))))", true),
            Internal.createCheck(this, DSL.name("ck_provider_attempt_status"), "(((status)::text = ANY ((ARRAY['SUBMITTING'::character varying, 'ACCEPTED'::character varying, 'UNKNOWN'::character varying, 'REJECTED'::character varying])::text[])))", true)
        );
    }

    @Override
    public ProviderAttempt as(String alias) {
        return new ProviderAttempt(DSL.name(alias), this);
    }

    @Override
    public ProviderAttempt as(Name alias) {
        return new ProviderAttempt(alias, this);
    }

    @Override
    public ProviderAttempt as(Table<?> alias) {
        return new ProviderAttempt(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProviderAttempt rename(String name) {
        return new ProviderAttempt(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProviderAttempt rename(Name name) {
        return new ProviderAttempt(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProviderAttempt rename(Table<?> name) {
        return new ProviderAttempt(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProviderAttempt where(Condition condition) {
        return new ProviderAttempt(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProviderAttempt where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProviderAttempt where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProviderAttempt where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProviderAttempt where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProviderAttempt where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProviderAttempt where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProviderAttempt where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProviderAttempt whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProviderAttempt whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
