/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables;


import dev.agenvas.db.Indexes;
import dev.agenvas.db.Keys;
import dev.agenvas.db.Public;
import dev.agenvas.db.tables.AppUser.AppUserPath;
import dev.agenvas.db.tables.Artifact.ArtifactPath;
import dev.agenvas.db.tables.ArtifactVersion.ArtifactVersionPath;
import dev.agenvas.db.tables.Task.TaskPath;
import dev.agenvas.db.tables.records.ShotKeyframeSelectionRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Explicit human selection of one generated keyframe version for a current
 * shot.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShotKeyframeSelection extends TableImpl<ShotKeyframeSelectionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.shot_keyframe_selection</code>
     */
    public static final ShotKeyframeSelection SHOT_KEYFRAME_SELECTION = new ShotKeyframeSelection();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ShotKeyframeSelectionRecord> getRecordType() {
        return ShotKeyframeSelectionRecord.class;
    }

    /**
     * The column <code>public.shot_keyframe_selection.project_id</code>.
     */
    public final TableField<ShotKeyframeSelectionRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.shot_keyframe_selection.shot_artifact_id</code>.
     */
    public final TableField<ShotKeyframeSelectionRecord, UUID> SHOT_ARTIFACT_ID = createField(DSL.name("shot_artifact_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.shot_keyframe_selection.shot_version_id</code>.
     */
    public final TableField<ShotKeyframeSelectionRecord, UUID> SHOT_VERSION_ID = createField(DSL.name("shot_version_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.shot_keyframe_selection.image_artifact_id</code>.
     */
    public final TableField<ShotKeyframeSelectionRecord, UUID> IMAGE_ARTIFACT_ID = createField(DSL.name("image_artifact_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.shot_keyframe_selection.image_version_id</code>.
     */
    public final TableField<ShotKeyframeSelectionRecord, UUID> IMAGE_VERSION_ID = createField(DSL.name("image_version_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.shot_keyframe_selection.source_task_id</code>.
     */
    public final TableField<ShotKeyframeSelectionRecord, UUID> SOURCE_TASK_ID = createField(DSL.name("source_task_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column
     * <code>public.shot_keyframe_selection.selected_by_user_id</code>.
     */
    public final TableField<ShotKeyframeSelectionRecord, UUID> SELECTED_BY_USER_ID = createField(DSL.name("selected_by_user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.shot_keyframe_selection.version</code>.
     */
    public final TableField<ShotKeyframeSelectionRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.shot_keyframe_selection.created_at</code>.
     */
    public final TableField<ShotKeyframeSelectionRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.shot_keyframe_selection.updated_at</code>.
     */
    public final TableField<ShotKeyframeSelectionRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    private ShotKeyframeSelection(Name alias, Table<ShotKeyframeSelectionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ShotKeyframeSelection(Name alias, Table<ShotKeyframeSelectionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Explicit human selection of one generated keyframe version for a current shot."), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.shot_keyframe_selection</code> table
     * reference
     */
    public ShotKeyframeSelection(String alias) {
        this(DSL.name(alias), SHOT_KEYFRAME_SELECTION);
    }

    /**
     * Create an aliased <code>public.shot_keyframe_selection</code> table
     * reference
     */
    public ShotKeyframeSelection(Name alias) {
        this(alias, SHOT_KEYFRAME_SELECTION);
    }

    /**
     * Create a <code>public.shot_keyframe_selection</code> table reference
     */
    public ShotKeyframeSelection() {
        this(DSL.name("shot_keyframe_selection"), null);
    }

    public <O extends Record> ShotKeyframeSelection(Table<O> path, ForeignKey<O, ShotKeyframeSelectionRecord> childPath, InverseForeignKey<O, ShotKeyframeSelectionRecord> parentPath) {
        super(path, childPath, parentPath, SHOT_KEYFRAME_SELECTION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ShotKeyframeSelectionPath extends ShotKeyframeSelection implements Path<ShotKeyframeSelectionRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ShotKeyframeSelectionPath(Table<O> path, ForeignKey<O, ShotKeyframeSelectionRecord> childPath, InverseForeignKey<O, ShotKeyframeSelectionRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ShotKeyframeSelectionPath(Name alias, Table<ShotKeyframeSelectionRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ShotKeyframeSelectionPath as(String alias) {
            return new ShotKeyframeSelectionPath(DSL.name(alias), this);
        }

        @Override
        public ShotKeyframeSelectionPath as(Name alias) {
            return new ShotKeyframeSelectionPath(alias, this);
        }

        @Override
        public ShotKeyframeSelectionPath as(Table<?> alias) {
            return new ShotKeyframeSelectionPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IX_KEYFRAME_IMAGE);
    }

    @Override
    public UniqueKey<ShotKeyframeSelectionRecord> getPrimaryKey() {
        return Keys.SHOT_KEYFRAME_SELECTION_PKEY;
    }

    @Override
    public List<ForeignKey<ShotKeyframeSelectionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SHOT_KEYFRAME_SELECTION__FK_KEYFRAME_IMAGE, Keys.SHOT_KEYFRAME_SELECTION__FK_KEYFRAME_IMAGE_VERSION, Keys.SHOT_KEYFRAME_SELECTION__FK_KEYFRAME_SHOT, Keys.SHOT_KEYFRAME_SELECTION__FK_KEYFRAME_SHOT_VERSION, Keys.SHOT_KEYFRAME_SELECTION__FK_KEYFRAME_TASK, Keys.SHOT_KEYFRAME_SELECTION__FK_KEYFRAME_TASK_PROJECT, Keys.SHOT_KEYFRAME_SELECTION__FK_KEYFRAME_USER);
    }

    private transient ArtifactPath _fkKeyframeImage;

    /**
     * Get the implicit join path to the <code>public.artifact</code> table, via
     * the <code>fk_keyframe_image</code> key.
     */
    public ArtifactPath fkKeyframeImage() {
        if (_fkKeyframeImage == null)
            _fkKeyframeImage = new ArtifactPath(this, Keys.SHOT_KEYFRAME_SELECTION__FK_KEYFRAME_IMAGE, null);

        return _fkKeyframeImage;
    }

    private transient ArtifactVersionPath _fkKeyframeImageVersion;

    /**
     * Get the implicit join path to the <code>public.artifact_version</code>
     * table, via the <code>fk_keyframe_image_version</code> key.
     */
    public ArtifactVersionPath fkKeyframeImageVersion() {
        if (_fkKeyframeImageVersion == null)
            _fkKeyframeImageVersion = new ArtifactVersionPath(this, Keys.SHOT_KEYFRAME_SELECTION__FK_KEYFRAME_IMAGE_VERSION, null);

        return _fkKeyframeImageVersion;
    }

    private transient ArtifactPath _fkKeyframeShot;

    /**
     * Get the implicit join path to the <code>public.artifact</code> table, via
     * the <code>fk_keyframe_shot</code> key.
     */
    public ArtifactPath fkKeyframeShot() {
        if (_fkKeyframeShot == null)
            _fkKeyframeShot = new ArtifactPath(this, Keys.SHOT_KEYFRAME_SELECTION__FK_KEYFRAME_SHOT, null);

        return _fkKeyframeShot;
    }

    private transient ArtifactVersionPath _fkKeyframeShotVersion;

    /**
     * Get the implicit join path to the <code>public.artifact_version</code>
     * table, via the <code>fk_keyframe_shot_version</code> key.
     */
    public ArtifactVersionPath fkKeyframeShotVersion() {
        if (_fkKeyframeShotVersion == null)
            _fkKeyframeShotVersion = new ArtifactVersionPath(this, Keys.SHOT_KEYFRAME_SELECTION__FK_KEYFRAME_SHOT_VERSION, null);

        return _fkKeyframeShotVersion;
    }

    private transient TaskPath _fkKeyframeTask;

    /**
     * Get the implicit join path to the <code>public.task</code> table, via the
     * <code>fk_keyframe_task</code> key.
     */
    public TaskPath fkKeyframeTask() {
        if (_fkKeyframeTask == null)
            _fkKeyframeTask = new TaskPath(this, Keys.SHOT_KEYFRAME_SELECTION__FK_KEYFRAME_TASK, null);

        return _fkKeyframeTask;
    }

    private transient TaskPath _fkKeyframeTaskProject;

    /**
     * Get the implicit join path to the <code>public.task</code> table, via the
     * <code>fk_keyframe_task_project</code> key.
     */
    public TaskPath fkKeyframeTaskProject() {
        if (_fkKeyframeTaskProject == null)
            _fkKeyframeTaskProject = new TaskPath(this, Keys.SHOT_KEYFRAME_SELECTION__FK_KEYFRAME_TASK_PROJECT, null);

        return _fkKeyframeTaskProject;
    }

    private transient AppUserPath _appUser;

    /**
     * Get the implicit join path to the <code>public.app_user</code> table.
     */
    public AppUserPath appUser() {
        if (_appUser == null)
            _appUser = new AppUserPath(this, Keys.SHOT_KEYFRAME_SELECTION__FK_KEYFRAME_USER, null);

        return _appUser;
    }

    @Override
    public List<Check<ShotKeyframeSelectionRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("ck_keyframe_version"), "((version >= 0))", true)
        );
    }

    @Override
    public ShotKeyframeSelection as(String alias) {
        return new ShotKeyframeSelection(DSL.name(alias), this);
    }

    @Override
    public ShotKeyframeSelection as(Name alias) {
        return new ShotKeyframeSelection(alias, this);
    }

    @Override
    public ShotKeyframeSelection as(Table<?> alias) {
        return new ShotKeyframeSelection(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ShotKeyframeSelection rename(String name) {
        return new ShotKeyframeSelection(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShotKeyframeSelection rename(Name name) {
        return new ShotKeyframeSelection(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShotKeyframeSelection rename(Table<?> name) {
        return new ShotKeyframeSelection(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShotKeyframeSelection where(Condition condition) {
        return new ShotKeyframeSelection(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShotKeyframeSelection where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShotKeyframeSelection where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShotKeyframeSelection where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShotKeyframeSelection where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShotKeyframeSelection where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShotKeyframeSelection where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShotKeyframeSelection where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShotKeyframeSelection whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShotKeyframeSelection whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
