/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables;


import dev.agenvas.db.Indexes;
import dev.agenvas.db.Keys;
import dev.agenvas.db.Public;
import dev.agenvas.db.tables.AppUser.AppUserPath;
import dev.agenvas.db.tables.CreativeSkill.CreativeSkillPath;
import dev.agenvas.db.tables.SkillVersion.SkillVersionPath;
import dev.agenvas.db.tables.records.SkillPublishOperationRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Durable fenced local archival; no model or Provider execution
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SkillPublishOperation extends TableImpl<SkillPublishOperationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.skill_publish_operation</code>
     */
    public static final SkillPublishOperation SKILL_PUBLISH_OPERATION = new SkillPublishOperation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SkillPublishOperationRecord> getRecordType() {
        return SkillPublishOperationRecord.class;
    }

    /**
     * The column <code>public.skill_publish_operation.id</code>.
     */
    public final TableField<SkillPublishOperationRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.skill_publish_operation.owner_id</code>.
     */
    public final TableField<SkillPublishOperationRecord, UUID> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.skill_publish_operation.skill_id</code>.
     */
    public final TableField<SkillPublishOperationRecord, UUID> SKILL_ID = createField(DSL.name("skill_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.skill_publish_operation.command_key</code>.
     */
    public final TableField<SkillPublishOperationRecord, String> COMMAND_KEY = createField(DSL.name("command_key"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>public.skill_publish_operation.payload_hash</code>.
     */
    public final TableField<SkillPublishOperationRecord, String> PAYLOAD_HASH = createField(DSL.name("payload_hash"), SQLDataType.CHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.skill_publish_operation.input_json</code>.
     */
    public final TableField<SkillPublishOperationRecord, JSONB> INPUT_JSON = createField(DSL.name("input_json"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>public.skill_publish_operation.progress_json</code>.
     */
    public final TableField<SkillPublishOperationRecord, JSONB> PROGRESS_JSON = createField(DSL.name("progress_json"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "");

    /**
     * The column <code>public.skill_publish_operation.status</code>.
     */
    public final TableField<SkillPublishOperationRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>public.skill_publish_operation.epoch</code>.
     */
    public final TableField<SkillPublishOperationRecord, Long> EPOCH = createField(DSL.name("epoch"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.skill_publish_operation.lease_until</code>.
     */
    public final TableField<SkillPublishOperationRecord, OffsetDateTime> LEASE_UNTIL = createField(DSL.name("lease_until"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.skill_publish_operation.result_version_id</code>.
     */
    public final TableField<SkillPublishOperationRecord, UUID> RESULT_VERSION_ID = createField(DSL.name("result_version_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.skill_publish_operation.error_code</code>.
     */
    public final TableField<SkillPublishOperationRecord, String> ERROR_CODE = createField(DSL.name("error_code"), SQLDataType.VARCHAR(80), this, "");

    /**
     * The column <code>public.skill_publish_operation.error_detail</code>.
     */
    public final TableField<SkillPublishOperationRecord, String> ERROR_DETAIL = createField(DSL.name("error_detail"), SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>public.skill_publish_operation.pins_cleaned</code>.
     */
    public final TableField<SkillPublishOperationRecord, Boolean> PINS_CLEANED = createField(DSL.name("pins_cleaned"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.skill_publish_operation.created_at</code>.
     */
    public final TableField<SkillPublishOperationRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.skill_publish_operation.updated_at</code>.
     */
    public final TableField<SkillPublishOperationRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    private SkillPublishOperation(Name alias, Table<SkillPublishOperationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SkillPublishOperation(Name alias, Table<SkillPublishOperationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Durable fenced local archival; no model or Provider execution"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.skill_publish_operation</code> table
     * reference
     */
    public SkillPublishOperation(String alias) {
        this(DSL.name(alias), SKILL_PUBLISH_OPERATION);
    }

    /**
     * Create an aliased <code>public.skill_publish_operation</code> table
     * reference
     */
    public SkillPublishOperation(Name alias) {
        this(alias, SKILL_PUBLISH_OPERATION);
    }

    /**
     * Create a <code>public.skill_publish_operation</code> table reference
     */
    public SkillPublishOperation() {
        this(DSL.name("skill_publish_operation"), null);
    }

    public <O extends Record> SkillPublishOperation(Table<O> path, ForeignKey<O, SkillPublishOperationRecord> childPath, InverseForeignKey<O, SkillPublishOperationRecord> parentPath) {
        super(path, childPath, parentPath, SKILL_PUBLISH_OPERATION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SkillPublishOperationPath extends SkillPublishOperation implements Path<SkillPublishOperationRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SkillPublishOperationPath(Table<O> path, ForeignKey<O, SkillPublishOperationRecord> childPath, InverseForeignKey<O, SkillPublishOperationRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SkillPublishOperationPath(Name alias, Table<SkillPublishOperationRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SkillPublishOperationPath as(String alias) {
            return new SkillPublishOperationPath(DSL.name(alias), this);
        }

        @Override
        public SkillPublishOperationPath as(Name alias) {
            return new SkillPublishOperationPath(alias, this);
        }

        @Override
        public SkillPublishOperationPath as(Table<?> alias) {
            return new SkillPublishOperationPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IX_SKILL_PUBLISH_CLAIM);
    }

    @Override
    public UniqueKey<SkillPublishOperationRecord> getPrimaryKey() {
        return Keys.SKILL_PUBLISH_OPERATION_PKEY;
    }

    @Override
    public List<UniqueKey<SkillPublishOperationRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.SKILL_PUBLISH_OPERATION_OWNER_ID_COMMAND_KEY_KEY);
    }

    @Override
    public List<ForeignKey<SkillPublishOperationRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SKILL_PUBLISH_OPERATION__SKILL_PUBLISH_OPERATION_OWNER_ID_FKEY, Keys.SKILL_PUBLISH_OPERATION__SKILL_PUBLISH_OPERATION_OWNER_ID_SKILL_ID_FKEY, Keys.SKILL_PUBLISH_OPERATION__SKILL_PUBLISH_OPERATION_OWNER_ID_SKILL_ID_RESULT_VERSION_I_FKEY);
    }

    private transient AppUserPath _appUser;

    /**
     * Get the implicit join path to the <code>public.app_user</code> table.
     */
    public AppUserPath appUser() {
        if (_appUser == null)
            _appUser = new AppUserPath(this, Keys.SKILL_PUBLISH_OPERATION__SKILL_PUBLISH_OPERATION_OWNER_ID_FKEY, null);

        return _appUser;
    }

    private transient CreativeSkillPath _creativeSkill;

    /**
     * Get the implicit join path to the <code>public.creative_skill</code>
     * table.
     */
    public CreativeSkillPath creativeSkill() {
        if (_creativeSkill == null)
            _creativeSkill = new CreativeSkillPath(this, Keys.SKILL_PUBLISH_OPERATION__SKILL_PUBLISH_OPERATION_OWNER_ID_SKILL_ID_FKEY, null);

        return _creativeSkill;
    }

    private transient SkillVersionPath _skillVersion;

    /**
     * Get the implicit join path to the <code>public.skill_version</code>
     * table.
     */
    public SkillVersionPath skillVersion() {
        if (_skillVersion == null)
            _skillVersion = new SkillVersionPath(this, Keys.SKILL_PUBLISH_OPERATION__SKILL_PUBLISH_OPERATION_OWNER_ID_SKILL_ID_RESULT_VERSION_I_FKEY, null);

        return _skillVersion;
    }

    @Override
    public List<Check<SkillPublishOperationRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("skill_publish_operation_check"), "((((status)::text = 'ARCHIVING'::text) = (lease_until IS NOT NULL)))", true),
            Internal.createCheck(this, DSL.name("skill_publish_operation_check1"), "((((status)::text = 'SUCCEEDED'::text) = (result_version_id IS NOT NULL)))", true),
            Internal.createCheck(this, DSL.name("skill_publish_operation_command_key_check"), "((length(btrim((command_key)::text)) > 0))", true),
            Internal.createCheck(this, DSL.name("skill_publish_operation_epoch_check"), "((epoch >= 0))", true),
            Internal.createCheck(this, DSL.name("skill_publish_operation_input_json_check"), "(((jsonb_typeof(input_json) = 'object'::text) AND (input_json @> '{\"schemaVersion\": 1}'::jsonb)))", true),
            Internal.createCheck(this, DSL.name("skill_publish_operation_payload_hash_check"), "((payload_hash ~ '^[0-9a-f]{64}$'::text))", true),
            Internal.createCheck(this, DSL.name("skill_publish_operation_progress_json_check"), "((jsonb_typeof(progress_json) = 'object'::text))", true),
            Internal.createCheck(this, DSL.name("skill_publish_operation_status_check"), "(((status)::text = ANY ((ARRAY['ACCEPTED'::character varying, 'ARCHIVING'::character varying, 'SUCCEEDED'::character varying, 'FAILED'::character varying])::text[])))", true)
        );
    }

    @Override
    public SkillPublishOperation as(String alias) {
        return new SkillPublishOperation(DSL.name(alias), this);
    }

    @Override
    public SkillPublishOperation as(Name alias) {
        return new SkillPublishOperation(alias, this);
    }

    @Override
    public SkillPublishOperation as(Table<?> alias) {
        return new SkillPublishOperation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SkillPublishOperation rename(String name) {
        return new SkillPublishOperation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SkillPublishOperation rename(Name name) {
        return new SkillPublishOperation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SkillPublishOperation rename(Table<?> name) {
        return new SkillPublishOperation(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SkillPublishOperation where(Condition condition) {
        return new SkillPublishOperation(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SkillPublishOperation where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SkillPublishOperation where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SkillPublishOperation where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SkillPublishOperation where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SkillPublishOperation where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SkillPublishOperation where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SkillPublishOperation where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SkillPublishOperation whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SkillPublishOperation whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
