/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables;


import dev.agenvas.db.Keys;
import dev.agenvas.db.Public;
import dev.agenvas.db.tables.Task.TaskPath;
import dev.agenvas.db.tables.records.TaskProviderPollRetryRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 外部状态查询的重试计数；查询重试不代表重新提交生成
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TaskProviderPollRetry extends TableImpl<TaskProviderPollRetryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.task_provider_poll_retry</code>
     */
    public static final TaskProviderPollRetry TASK_PROVIDER_POLL_RETRY = new TaskProviderPollRetry();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TaskProviderPollRetryRecord> getRecordType() {
        return TaskProviderPollRetryRecord.class;
    }

    /**
     * The column <code>public.task_provider_poll_retry.task_id</code>. 持久任务身份
     */
    public final TableField<TaskProviderPollRetryRecord, UUID> TASK_ID = createField(DSL.name("task_id"), SQLDataType.UUID.nullable(false), this, "持久任务身份");

    /**
     * The column <code>public.task_provider_poll_retry.failure_count</code>.
     * 连续外部查询失败次数
     */
    public final TableField<TaskProviderPollRetryRecord, Integer> FAILURE_COUNT = createField(DSL.name("failure_count"), SQLDataType.INTEGER.nullable(false), this, "连续外部查询失败次数");

    /**
     * The column <code>public.task_provider_poll_retry.last_error_code</code>.
     * 最近外部查询失败的公开错误代码
     */
    public final TableField<TaskProviderPollRetryRecord, String> LAST_ERROR_CODE = createField(DSL.name("last_error_code"), SQLDataType.VARCHAR(120).nullable(false), this, "最近外部查询失败的公开错误代码");

    /**
     * The column <code>public.task_provider_poll_retry.updated_at</code>.
     * 最后状态或配置更新时间（UTC）
     */
    public final TableField<TaskProviderPollRetryRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "最后状态或配置更新时间（UTC）");

    private TaskProviderPollRetry(Name alias, Table<TaskProviderPollRetryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TaskProviderPollRetry(Name alias, Table<TaskProviderPollRetryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("外部状态查询的重试计数；查询重试不代表重新提交生成"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.task_provider_poll_retry</code> table
     * reference
     */
    public TaskProviderPollRetry(String alias) {
        this(DSL.name(alias), TASK_PROVIDER_POLL_RETRY);
    }

    /**
     * Create an aliased <code>public.task_provider_poll_retry</code> table
     * reference
     */
    public TaskProviderPollRetry(Name alias) {
        this(alias, TASK_PROVIDER_POLL_RETRY);
    }

    /**
     * Create a <code>public.task_provider_poll_retry</code> table reference
     */
    public TaskProviderPollRetry() {
        this(DSL.name("task_provider_poll_retry"), null);
    }

    public <O extends Record> TaskProviderPollRetry(Table<O> path, ForeignKey<O, TaskProviderPollRetryRecord> childPath, InverseForeignKey<O, TaskProviderPollRetryRecord> parentPath) {
        super(path, childPath, parentPath, TASK_PROVIDER_POLL_RETRY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TaskProviderPollRetryPath extends TaskProviderPollRetry implements Path<TaskProviderPollRetryRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TaskProviderPollRetryPath(Table<O> path, ForeignKey<O, TaskProviderPollRetryRecord> childPath, InverseForeignKey<O, TaskProviderPollRetryRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TaskProviderPollRetryPath(Name alias, Table<TaskProviderPollRetryRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TaskProviderPollRetryPath as(String alias) {
            return new TaskProviderPollRetryPath(DSL.name(alias), this);
        }

        @Override
        public TaskProviderPollRetryPath as(Name alias) {
            return new TaskProviderPollRetryPath(alias, this);
        }

        @Override
        public TaskProviderPollRetryPath as(Table<?> alias) {
            return new TaskProviderPollRetryPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TaskProviderPollRetryRecord> getPrimaryKey() {
        return Keys.TASK_PROVIDER_POLL_RETRY_PKEY;
    }

    @Override
    public List<ForeignKey<TaskProviderPollRetryRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TASK_PROVIDER_POLL_RETRY__TASK_PROVIDER_POLL_RETRY_TASK_ID_FKEY);
    }

    private transient TaskPath _task;

    /**
     * Get the implicit join path to the <code>public.task</code> table.
     */
    public TaskPath task() {
        if (_task == null)
            _task = new TaskPath(this, Keys.TASK_PROVIDER_POLL_RETRY__TASK_PROVIDER_POLL_RETRY_TASK_ID_FKEY, null);

        return _task;
    }

    @Override
    public List<Check<TaskProviderPollRetryRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("ck_task_provider_poll_retry_count"), "(((failure_count >= 1) AND (failure_count <= 6)))", true)
        );
    }

    @Override
    public TaskProviderPollRetry as(String alias) {
        return new TaskProviderPollRetry(DSL.name(alias), this);
    }

    @Override
    public TaskProviderPollRetry as(Name alias) {
        return new TaskProviderPollRetry(alias, this);
    }

    @Override
    public TaskProviderPollRetry as(Table<?> alias) {
        return new TaskProviderPollRetry(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TaskProviderPollRetry rename(String name) {
        return new TaskProviderPollRetry(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TaskProviderPollRetry rename(Name name) {
        return new TaskProviderPollRetry(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TaskProviderPollRetry rename(Table<?> name) {
        return new TaskProviderPollRetry(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TaskProviderPollRetry where(Condition condition) {
        return new TaskProviderPollRetry(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TaskProviderPollRetry where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TaskProviderPollRetry where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TaskProviderPollRetry where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TaskProviderPollRetry where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TaskProviderPollRetry where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TaskProviderPollRetry where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TaskProviderPollRetry where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TaskProviderPollRetry whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TaskProviderPollRetry whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
