/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables;


import dev.agenvas.db.Keys;
import dev.agenvas.db.Public;
import dev.agenvas.db.tables.AppUser.AppUserPath;
import dev.agenvas.db.tables.Task.TaskPath;
import dev.agenvas.db.tables.records.TaskManualReplacementRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 用户显式批准的 UNKNOWN 重试对应关系和确认记录
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TaskManualReplacement extends TableImpl<TaskManualReplacementRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.task_manual_replacement</code>
     */
    public static final TaskManualReplacement TASK_MANUAL_REPLACEMENT = new TaskManualReplacement();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TaskManualReplacementRecord> getRecordType() {
        return TaskManualReplacementRecord.class;
    }

    /**
     * The column <code>public.task_manual_replacement.original_task_id</code>.
     * 结果未知的原任务
     */
    public final TableField<TaskManualReplacementRecord, UUID> ORIGINAL_TASK_ID = createField(DSL.name("original_task_id"), SQLDataType.UUID.nullable(false), this, "结果未知的原任务");

    /**
     * The column <code>public.task_manual_replacement.project_id</code>.
     * 所属项目及授权作用域
     */
    public final TableField<TaskManualReplacementRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "所属项目及授权作用域");

    /**
     * The column
     * <code>public.task_manual_replacement.replacement_task_id</code>.
     * 用户显式创建的独立新尝试
     */
    public final TableField<TaskManualReplacementRecord, UUID> REPLACEMENT_TASK_ID = createField(DSL.name("replacement_task_id"), SQLDataType.UUID.nullable(false), this, "用户显式创建的独立新尝试");

    /**
     * The column
     * <code>public.task_manual_replacement.approved_by_user_id</code>.
     * 确认重复费用风险的可信用户身份
     */
    public final TableField<TaskManualReplacementRecord, UUID> APPROVED_BY_USER_ID = createField(DSL.name("approved_by_user_id"), SQLDataType.UUID.nullable(false), this, "确认重复费用风险的可信用户身份");

    /**
     * The column
     * <code>public.task_manual_replacement.original_task_version</code>.
     * 用户批准重试时核对的原任务版本
     */
    public final TableField<TaskManualReplacementRecord, Long> ORIGINAL_TASK_VERSION = createField(DSL.name("original_task_version"), SQLDataType.BIGINT.nullable(false), this, "用户批准重试时核对的原任务版本");

    /**
     * The column <code>public.task_manual_replacement.idempotency_key</code>.
     * 作用域内的幂等命令键
     */
    public final TableField<TaskManualReplacementRecord, String> IDEMPOTENCY_KEY = createField(DSL.name("idempotency_key"), SQLDataType.VARCHAR(120).nullable(false), this, "作用域内的幂等命令键");

    /**
     * The column <code>public.task_manual_replacement.confirmation_code</code>.
     * 明确重复成本确认的稳定代码
     */
    public final TableField<TaskManualReplacementRecord, String> CONFIRMATION_CODE = createField(DSL.name("confirmation_code"), SQLDataType.VARCHAR(80).nullable(false), this, "明确重复成本确认的稳定代码");

    /**
     * The column <code>public.task_manual_replacement.created_at</code>.
     * 创建时间（UTC）
     */
    public final TableField<TaskManualReplacementRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "创建时间（UTC）");

    private TaskManualReplacement(Name alias, Table<TaskManualReplacementRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TaskManualReplacement(Name alias, Table<TaskManualReplacementRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("用户显式批准的 UNKNOWN 重试对应关系和确认记录"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.task_manual_replacement</code> table
     * reference
     */
    public TaskManualReplacement(String alias) {
        this(DSL.name(alias), TASK_MANUAL_REPLACEMENT);
    }

    /**
     * Create an aliased <code>public.task_manual_replacement</code> table
     * reference
     */
    public TaskManualReplacement(Name alias) {
        this(alias, TASK_MANUAL_REPLACEMENT);
    }

    /**
     * Create a <code>public.task_manual_replacement</code> table reference
     */
    public TaskManualReplacement() {
        this(DSL.name("task_manual_replacement"), null);
    }

    public <O extends Record> TaskManualReplacement(Table<O> path, ForeignKey<O, TaskManualReplacementRecord> childPath, InverseForeignKey<O, TaskManualReplacementRecord> parentPath) {
        super(path, childPath, parentPath, TASK_MANUAL_REPLACEMENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TaskManualReplacementPath extends TaskManualReplacement implements Path<TaskManualReplacementRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TaskManualReplacementPath(Table<O> path, ForeignKey<O, TaskManualReplacementRecord> childPath, InverseForeignKey<O, TaskManualReplacementRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TaskManualReplacementPath(Name alias, Table<TaskManualReplacementRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TaskManualReplacementPath as(String alias) {
            return new TaskManualReplacementPath(DSL.name(alias), this);
        }

        @Override
        public TaskManualReplacementPath as(Name alias) {
            return new TaskManualReplacementPath(alias, this);
        }

        @Override
        public TaskManualReplacementPath as(Table<?> alias) {
            return new TaskManualReplacementPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TaskManualReplacementRecord> getPrimaryKey() {
        return Keys.TASK_MANUAL_REPLACEMENT_PKEY;
    }

    @Override
    public List<UniqueKey<TaskManualReplacementRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.TASK_MANUAL_REPLACEMENT_REPLACEMENT_TASK_ID_KEY, Keys.UQ_MANUAL_REPLACEMENT_COMMAND);
    }

    @Override
    public List<ForeignKey<TaskManualReplacementRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TASK_MANUAL_REPLACEMENT__FK_MANUAL_REPLACEMENT_NEW, Keys.TASK_MANUAL_REPLACEMENT__FK_MANUAL_REPLACEMENT_ORIGINAL, Keys.TASK_MANUAL_REPLACEMENT__TASK_MANUAL_REPLACEMENT_APPROVED_BY_USER_ID_FKEY);
    }

    private transient TaskPath _fkManualReplacementNew;

    /**
     * Get the implicit join path to the <code>public.task</code> table, via the
     * <code>fk_manual_replacement_new</code> key.
     */
    public TaskPath fkManualReplacementNew() {
        if (_fkManualReplacementNew == null)
            _fkManualReplacementNew = new TaskPath(this, Keys.TASK_MANUAL_REPLACEMENT__FK_MANUAL_REPLACEMENT_NEW, null);

        return _fkManualReplacementNew;
    }

    private transient TaskPath _fkManualReplacementOriginal;

    /**
     * Get the implicit join path to the <code>public.task</code> table, via the
     * <code>fk_manual_replacement_original</code> key.
     */
    public TaskPath fkManualReplacementOriginal() {
        if (_fkManualReplacementOriginal == null)
            _fkManualReplacementOriginal = new TaskPath(this, Keys.TASK_MANUAL_REPLACEMENT__FK_MANUAL_REPLACEMENT_ORIGINAL, null);

        return _fkManualReplacementOriginal;
    }

    private transient AppUserPath _appUser;

    /**
     * Get the implicit join path to the <code>public.app_user</code> table.
     */
    public AppUserPath appUser() {
        if (_appUser == null)
            _appUser = new AppUserPath(this, Keys.TASK_MANUAL_REPLACEMENT__TASK_MANUAL_REPLACEMENT_APPROVED_BY_USER_ID_FKEY, null);

        return _appUser;
    }

    @Override
    public List<Check<TaskManualReplacementRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("ck_manual_replacement_confirmation"), "(((confirmation_code)::text = 'ACCEPT_POSSIBLE_DUPLICATE_COST'::text))", true),
            Internal.createCheck(this, DSL.name("ck_manual_replacement_version"), "((original_task_version >= 0))", true)
        );
    }

    @Override
    public TaskManualReplacement as(String alias) {
        return new TaskManualReplacement(DSL.name(alias), this);
    }

    @Override
    public TaskManualReplacement as(Name alias) {
        return new TaskManualReplacement(alias, this);
    }

    @Override
    public TaskManualReplacement as(Table<?> alias) {
        return new TaskManualReplacement(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TaskManualReplacement rename(String name) {
        return new TaskManualReplacement(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TaskManualReplacement rename(Name name) {
        return new TaskManualReplacement(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TaskManualReplacement rename(Table<?> name) {
        return new TaskManualReplacement(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TaskManualReplacement where(Condition condition) {
        return new TaskManualReplacement(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TaskManualReplacement where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TaskManualReplacement where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TaskManualReplacement where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TaskManualReplacement where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TaskManualReplacement where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TaskManualReplacement where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TaskManualReplacement where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TaskManualReplacement whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TaskManualReplacement whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
