/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db.tables;


import dev.agenvas.db.Keys;
import dev.agenvas.db.Public;
import dev.agenvas.db.tables.ThirdPartyPrompt.ThirdPartyPromptPath;
import dev.agenvas.db.tables.records.ThirdPartyPromptSourceRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 第三方提示词源；每日同步租约与失败状态独立持久化
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ThirdPartyPromptSource extends TableImpl<ThirdPartyPromptSourceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.third_party_prompt_source</code>
     */
    public static final ThirdPartyPromptSource THIRD_PARTY_PROMPT_SOURCE = new ThirdPartyPromptSource();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ThirdPartyPromptSourceRecord> getRecordType() {
        return ThirdPartyPromptSourceRecord.class;
    }

    /**
     * The column <code>public.third_party_prompt_source.id</code>.
     * 不可变来源标识，作为提示词身份前缀
     */
    public final TableField<ThirdPartyPromptSourceRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(80).nullable(false), this, "不可变来源标识，作为提示词身份前缀");

    /**
     * The column <code>public.third_party_prompt_source.name</code>. 来源显示名称
     */
    public final TableField<ThirdPartyPromptSourceRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(160).nullable(false), this, "来源显示名称");

    /**
     * The column <code>public.third_party_prompt_source.target_kind</code>.
     * 来源媒体类型：图片或视频
     */
    public final TableField<ThirdPartyPromptSourceRecord, String> TARGET_KIND = createField(DSL.name("target_kind"), SQLDataType.VARCHAR(16).nullable(false), this, "来源媒体类型：图片或视频");

    /**
     * The column <code>public.third_party_prompt_source.format</code>. 上游格式适配器
     */
    public final TableField<ThirdPartyPromptSourceRecord, String> FORMAT = createField(DSL.name("format"), SQLDataType.VARCHAR(32).nullable(false), this, "上游格式适配器");

    /**
     * The column <code>public.third_party_prompt_source.url</code>. 无凭证的 HTTPS
     * 数据地址
     */
    public final TableField<ThirdPartyPromptSourceRecord, String> URL = createField(DSL.name("url"), SQLDataType.CLOB.nullable(false), this, "无凭证的 HTTPS 数据地址");

    /**
     * The column <code>public.third_party_prompt_source.model</code>.
     * 适配器使用的上游模型名称，仅作来源元数据
     */
    public final TableField<ThirdPartyPromptSourceRecord, String> MODEL = createField(DSL.name("model"), SQLDataType.VARCHAR(160).nullable(false).defaultValue(DSL.field(DSL.raw("''::character varying"), SQLDataType.VARCHAR)), this, "适配器使用的上游模型名称，仅作来源元数据");

    /**
     * The column <code>public.third_party_prompt_source.enabled</code>.
     * 停用后不再同步，缓存保留可读
     */
    public final TableField<ThirdPartyPromptSourceRecord, Boolean> ENABLED = createField(DSL.name("enabled"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "停用后不再同步，缓存保留可读");

    /**
     * The column <code>public.third_party_prompt_source.version</code>. 来源配置
     * CAS 版本
     */
    public final TableField<ThirdPartyPromptSourceRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "来源配置 CAS 版本");

    /**
     * The column <code>public.third_party_prompt_source.next_sync_at</code>.
     * 下次同步时间：成功后二十四小时，失败后一小时
     */
    public final TableField<ThirdPartyPromptSourceRecord, OffsetDateTime> NEXT_SYNC_AT = createField(DSL.name("next_sync_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "下次同步时间：成功后二十四小时，失败后一小时");

    /**
     * The column <code>public.third_party_prompt_source.last_synced_at</code>.
     * 最近一次成功发布缓存的时间
     */
    public final TableField<ThirdPartyPromptSourceRecord, OffsetDateTime> LAST_SYNCED_AT = createField(DSL.name("last_synced_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "最近一次成功发布缓存的时间");

    /**
     * The column <code>public.third_party_prompt_source.last_error</code>.
     * 最近失败的稳定错误码，不保存上游异常正文
     */
    public final TableField<ThirdPartyPromptSourceRecord, String> LAST_ERROR = createField(DSL.name("last_error"), SQLDataType.VARCHAR(80), this, "最近失败的稳定错误码，不保存上游异常正文");

    /**
     * The column <code>public.third_party_prompt_source.lease_token</code>.
     * 当前同步的 fencing token
     */
    public final TableField<ThirdPartyPromptSourceRecord, UUID> LEASE_TOKEN = createField(DSL.name("lease_token"), SQLDataType.UUID, this, "当前同步的 fencing token");

    /**
     * The column <code>public.third_party_prompt_source.lease_until</code>.
     * 同步租约过期时间
     */
    public final TableField<ThirdPartyPromptSourceRecord, OffsetDateTime> LEASE_UNTIL = createField(DSL.name("lease_until"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "同步租约过期时间");

    private ThirdPartyPromptSource(Name alias, Table<ThirdPartyPromptSourceRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ThirdPartyPromptSource(Name alias, Table<ThirdPartyPromptSourceRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("第三方提示词源；每日同步租约与失败状态独立持久化"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.third_party_prompt_source</code> table
     * reference
     */
    public ThirdPartyPromptSource(String alias) {
        this(DSL.name(alias), THIRD_PARTY_PROMPT_SOURCE);
    }

    /**
     * Create an aliased <code>public.third_party_prompt_source</code> table
     * reference
     */
    public ThirdPartyPromptSource(Name alias) {
        this(alias, THIRD_PARTY_PROMPT_SOURCE);
    }

    /**
     * Create a <code>public.third_party_prompt_source</code> table reference
     */
    public ThirdPartyPromptSource() {
        this(DSL.name("third_party_prompt_source"), null);
    }

    public <O extends Record> ThirdPartyPromptSource(Table<O> path, ForeignKey<O, ThirdPartyPromptSourceRecord> childPath, InverseForeignKey<O, ThirdPartyPromptSourceRecord> parentPath) {
        super(path, childPath, parentPath, THIRD_PARTY_PROMPT_SOURCE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ThirdPartyPromptSourcePath extends ThirdPartyPromptSource implements Path<ThirdPartyPromptSourceRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ThirdPartyPromptSourcePath(Table<O> path, ForeignKey<O, ThirdPartyPromptSourceRecord> childPath, InverseForeignKey<O, ThirdPartyPromptSourceRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ThirdPartyPromptSourcePath(Name alias, Table<ThirdPartyPromptSourceRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ThirdPartyPromptSourcePath as(String alias) {
            return new ThirdPartyPromptSourcePath(DSL.name(alias), this);
        }

        @Override
        public ThirdPartyPromptSourcePath as(Name alias) {
            return new ThirdPartyPromptSourcePath(alias, this);
        }

        @Override
        public ThirdPartyPromptSourcePath as(Table<?> alias) {
            return new ThirdPartyPromptSourcePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ThirdPartyPromptSourceRecord> getPrimaryKey() {
        return Keys.THIRD_PARTY_PROMPT_SOURCE_PKEY;
    }

    private transient ThirdPartyPromptPath _thirdPartyPrompt;

    /**
     * Get the implicit to-many join path to the
     * <code>public.third_party_prompt</code> table
     */
    public ThirdPartyPromptPath thirdPartyPrompt() {
        if (_thirdPartyPrompt == null)
            _thirdPartyPrompt = new ThirdPartyPromptPath(this, null, Keys.THIRD_PARTY_PROMPT__THIRD_PARTY_PROMPT_SOURCE_ID_FKEY.getInverseKey());

        return _thirdPartyPrompt;
    }

    @Override
    public List<Check<ThirdPartyPromptSourceRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("third_party_prompt_source_check"), "(((lease_token IS NULL) = (lease_until IS NULL)))", true),
            Internal.createCheck(this, DSL.name("third_party_prompt_source_format_check"), "(((format)::text = ANY ((ARRAY['NATIVE_JSON'::character varying, 'GITHUB_MARKDOWN'::character varying, 'DAVID_JSON'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("third_party_prompt_source_id_check"), "(((id)::text ~ '^[a-z][a-z0-9_-]{0,79}$'::text))", true),
            Internal.createCheck(this, DSL.name("third_party_prompt_source_target_kind_check"), "(((target_kind)::text = ANY ((ARRAY['IMAGE'::character varying, 'VIDEO'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("third_party_prompt_source_version_check"), "((version >= 0))", true)
        );
    }

    @Override
    public ThirdPartyPromptSource as(String alias) {
        return new ThirdPartyPromptSource(DSL.name(alias), this);
    }

    @Override
    public ThirdPartyPromptSource as(Name alias) {
        return new ThirdPartyPromptSource(alias, this);
    }

    @Override
    public ThirdPartyPromptSource as(Table<?> alias) {
        return new ThirdPartyPromptSource(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ThirdPartyPromptSource rename(String name) {
        return new ThirdPartyPromptSource(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ThirdPartyPromptSource rename(Name name) {
        return new ThirdPartyPromptSource(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ThirdPartyPromptSource rename(Table<?> name) {
        return new ThirdPartyPromptSource(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ThirdPartyPromptSource where(Condition condition) {
        return new ThirdPartyPromptSource(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ThirdPartyPromptSource where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ThirdPartyPromptSource where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ThirdPartyPromptSource where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ThirdPartyPromptSource where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ThirdPartyPromptSource where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ThirdPartyPromptSource where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ThirdPartyPromptSource where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ThirdPartyPromptSource whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ThirdPartyPromptSource whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
