/*
 * This file is generated by jOOQ.
 */
package dev.agenvas.db;


import dev.agenvas.db.tables.AgentBinding;
import dev.agenvas.db.tables.AgentConversation;
import dev.agenvas.db.tables.AgentInstance;
import dev.agenvas.db.tables.AgentMediaApproval;
import dev.agenvas.db.tables.AgentRun;
import dev.agenvas.db.tables.AppUser;
import dev.agenvas.db.tables.Artifact;
import dev.agenvas.db.tables.ArtifactVersion;
import dev.agenvas.db.tables.ArtifactVersionReference;
import dev.agenvas.db.tables.Asset;
import dev.agenvas.db.tables.CallLog;
import dev.agenvas.db.tables.CanvasConnection;
import dev.agenvas.db.tables.CanvasItem;
import dev.agenvas.db.tables.CanvasItemMediaInput;
import dev.agenvas.db.tables.CanvasItemMediaInputSource;
import dev.agenvas.db.tables.CreativeSkill;
import dev.agenvas.db.tables.IdempotencyRecord;
import dev.agenvas.db.tables.LibraryCleanup;
import dev.agenvas.db.tables.LibraryCommand;
import dev.agenvas.db.tables.LibraryEntry;
import dev.agenvas.db.tables.LlmProviderConfig;
import dev.agenvas.db.tables.LlmTurn;
import dev.agenvas.db.tables.MediaLegacyOriginMap;
import dev.agenvas.db.tables.Project;
import dev.agenvas.db.tables.ProjectEvent;
import dev.agenvas.db.tables.ProviderAttempt;
import dev.agenvas.db.tables.SkillInstallOperation;
import dev.agenvas.db.tables.SkillPublishOperation;
import dev.agenvas.db.tables.SpringSession;
import dev.agenvas.db.tables.Task;
import dev.agenvas.db.tables.TaskArtifactTarget;
import dev.agenvas.db.tables.TaskDependency;
import dev.agenvas.db.tables.ToolExecution;
import dev.agenvas.db.tables.UsageLedger;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IX_AGENT_BINDING_AGENT = Internal.createIndex(DSL.name("ix_agent_binding_agent"), AgentBinding.AGENT_BINDING, new OrderField[] { AgentBinding.AGENT_BINDING.PROJECT_ID, AgentBinding.AGENT_BINDING.AGENT_INSTANCE_ID }, false);
    public static final Index IX_AGENT_INSTANCE_PROJECT = Internal.createIndex(DSL.name("ix_agent_instance_project"), AgentInstance.AGENT_INSTANCE, new OrderField[] { AgentInstance.AGENT_INSTANCE.PROJECT_ID, AgentInstance.AGENT_INSTANCE.CREATED_AT, AgentInstance.AGENT_INSTANCE.ID }, false);
    public static final Index IX_AGENT_MEDIA_APPROVAL_OUTSTANDING = Internal.createIndex(DSL.name("ix_agent_media_approval_outstanding"), AgentMediaApproval.AGENT_MEDIA_APPROVAL, new OrderField[] { AgentMediaApproval.AGENT_MEDIA_APPROVAL.ID }, false);
    public static final Index IX_AGENT_MEDIA_APPROVAL_RUN = Internal.createIndex(DSL.name("ix_agent_media_approval_run"), AgentMediaApproval.AGENT_MEDIA_APPROVAL, new OrderField[] { AgentMediaApproval.AGENT_MEDIA_APPROVAL.PROJECT_ID, AgentMediaApproval.AGENT_MEDIA_APPROVAL.RUN_ID, AgentMediaApproval.AGENT_MEDIA_APPROVAL.CREATED_AT, AgentMediaApproval.AGENT_MEDIA_APPROVAL.ID }, false);
    public static final Index IX_AGENT_MEDIA_APPROVAL_TASKS = Internal.createIndex(DSL.name("ix_agent_media_approval_tasks"), AgentMediaApproval.AGENT_MEDIA_APPROVAL, new OrderField[] { AgentMediaApproval.AGENT_MEDIA_APPROVAL.TASK_IDS_JSON }, false);
    public static final Index IX_AGENT_RUN_PROJECT_CREATED = Internal.createIndex(DSL.name("ix_agent_run_project_created"), AgentRun.AGENT_RUN, new OrderField[] { AgentRun.AGENT_RUN.PROJECT_ID, AgentRun.AGENT_RUN.CREATED_AT.desc(), AgentRun.AGENT_RUN.ID.desc() }, false);
    public static final Index IX_AGENT_RUN_STATUS = Internal.createIndex(DSL.name("ix_agent_run_status"), AgentRun.AGENT_RUN, new OrderField[] { AgentRun.AGENT_RUN.STATUS, AgentRun.AGENT_RUN.UPDATED_AT }, false);
    public static final Index IX_ARTIFACT_PROJECT_ACTIVE = Internal.createIndex(DSL.name("ix_artifact_project_active"), Artifact.ARTIFACT, new OrderField[] { Artifact.ARTIFACT.PROJECT_ID, Artifact.ARTIFACT.ARCHIVED_AT, Artifact.ARTIFACT.CREATED_AT.desc() }, false);
    public static final Index IX_ARTIFACT_REFERENCE_TARGET = Internal.createIndex(DSL.name("ix_artifact_reference_target"), ArtifactVersionReference.ARTIFACT_VERSION_REFERENCE, new OrderField[] { ArtifactVersionReference.ARTIFACT_VERSION_REFERENCE.PROJECT_ID, ArtifactVersionReference.ARTIFACT_VERSION_REFERENCE.TARGET_VERSION_ID }, false);
    public static final Index IX_ARTIFACT_VERSION_HISTORY = Internal.createIndex(DSL.name("ix_artifact_version_history"), ArtifactVersion.ARTIFACT_VERSION, new OrderField[] { ArtifactVersion.ARTIFACT_VERSION.ARTIFACT_ID, ArtifactVersion.ARTIFACT_VERSION.VERSION_NO.desc() }, false);
    public static final Index IX_ASSET_PROJECT_CREATED = Internal.createIndex(DSL.name("ix_asset_project_created"), Asset.ASSET, new OrderField[] { Asset.ASSET.PROJECT_ID, Asset.ASSET.CREATED_AT.desc() }, false);
    public static final Index IX_CALL_LOG_PROJECT_TIME = Internal.createIndex(DSL.name("ix_call_log_project_time"), CallLog.CALL_LOG, new OrderField[] { CallLog.CALL_LOG.PROJECT_ID, CallLog.CALL_LOG.STARTED_AT.desc(), CallLog.CALL_LOG.ID.desc() }, false);
    public static final Index IX_CALL_LOG_ROUND = Internal.createIndex(DSL.name("ix_call_log_round"), CallLog.CALL_LOG, new OrderField[] { CallLog.CALL_LOG.RUN_ID, CallLog.CALL_LOG.STEP_INDEX }, false);
    public static final Index IX_CALL_LOG_TASK = Internal.createIndex(DSL.name("ix_call_log_task"), CallLog.CALL_LOG, new OrderField[] { CallLog.CALL_LOG.TASK_ID, CallLog.CALL_LOG.OPERATION }, false);
    public static final Index IX_CANVAS_CONNECTION_TARGET = Internal.createIndex(DSL.name("ix_canvas_connection_target"), CanvasConnection.CANVAS_CONNECTION, new OrderField[] { CanvasConnection.CANVAS_CONNECTION.PROJECT_ID, CanvasConnection.CANVAS_CONNECTION.TARGET_CANVAS_ITEM_ID }, false);
    public static final Index IX_CANVAS_ITEM_PROJECT = Internal.createIndex(DSL.name("ix_canvas_item_project"), CanvasItem.CANVAS_ITEM, new OrderField[] { CanvasItem.CANVAS_ITEM.PROJECT_ID, CanvasItem.CANVAS_ITEM.Z_INDEX, CanvasItem.CANVAS_ITEM.ID }, false);
    public static final Index IX_CANVAS_ITEM_SUBJECT = Internal.createIndex(DSL.name("ix_canvas_item_subject"), CanvasItem.CANVAS_ITEM, new OrderField[] { CanvasItem.CANVAS_ITEM.PROJECT_ID, CanvasItem.CANVAS_ITEM.SUBJECT_TYPE, CanvasItem.CANVAS_ITEM.SUBJECT_ID }, false);
    public static final Index IX_CONVERSATION_AGENT_UPDATED = Internal.createIndex(DSL.name("ix_conversation_agent_updated"), AgentConversation.AGENT_CONVERSATION, new OrderField[] { AgentConversation.AGENT_CONVERSATION.PROJECT_ID, AgentConversation.AGENT_CONVERSATION.AGENT_INSTANCE_ID, AgentConversation.AGENT_CONVERSATION.UPDATED_AT.desc(), AgentConversation.AGENT_CONVERSATION.ID.desc() }, false);
    public static final Index IX_CREATIVE_SKILL_LIST = Internal.createIndex(DSL.name("ix_creative_skill_list"), CreativeSkill.CREATIVE_SKILL, new OrderField[] { CreativeSkill.CREATIVE_SKILL.OWNER_ID, CreativeSkill.CREATIVE_SKILL.TRASHED_AT, CreativeSkill.CREATIVE_SKILL.UPDATED_AT.desc(), CreativeSkill.CREATIVE_SKILL.ID.desc() }, false);
    public static final Index IX_IDEMPOTENCY_EXPIRY = Internal.createIndex(DSL.name("ix_idempotency_expiry"), IdempotencyRecord.IDEMPOTENCY_RECORD, new OrderField[] { IdempotencyRecord.IDEMPOTENCY_RECORD.EXPIRES_AT }, false);
    public static final Index IX_LIBRARY_COMMAND_CLAIM = Internal.createIndex(DSL.name("ix_library_command_claim"), LibraryCommand.LIBRARY_COMMAND, new OrderField[] { LibraryCommand.LIBRARY_COMMAND.STATUS, LibraryCommand.LIBRARY_COMMAND.LEASE_UNTIL, LibraryCommand.LIBRARY_COMMAND.CREATED_AT }, false);
    public static final Index IX_LIBRARY_ENTRY_LIST = Internal.createIndex(DSL.name("ix_library_entry_list"), LibraryEntry.LIBRARY_ENTRY, new OrderField[] { LibraryEntry.LIBRARY_ENTRY.OWNER_ID, LibraryEntry.LIBRARY_ENTRY.TRASHED_AT, LibraryEntry.LIBRARY_ENTRY.CATEGORY, LibraryEntry.LIBRARY_ENTRY.CREATED_AT.desc(), LibraryEntry.LIBRARY_ENTRY.ID.desc() }, false);
    public static final Index IX_LLM_TURN_PROJECT_RUN = Internal.createIndex(DSL.name("ix_llm_turn_project_run"), LlmTurn.LLM_TURN, new OrderField[] { LlmTurn.LLM_TURN.PROJECT_ID, LlmTurn.LLM_TURN.RUN_ID, LlmTurn.LLM_TURN.STEP_INDEX }, false);
    public static final Index IX_MEDIA_LEGACY_ORIGIN_MAP_SHA = Internal.createIndex(DSL.name("ix_media_legacy_origin_map_sha"), MediaLegacyOriginMap.MEDIA_LEGACY_ORIGIN_MAP, new OrderField[] { MediaLegacyOriginMap.MEDIA_LEGACY_ORIGIN_MAP.ORIGIN_SHA256, MediaLegacyOriginMap.MEDIA_LEGACY_ORIGIN_MAP.CONFIG_VERSION }, false);
    public static final Index IX_PROJECT_EVENT_OCCURRED_AT = Internal.createIndex(DSL.name("ix_project_event_occurred_at"), ProjectEvent.PROJECT_EVENT, new OrderField[] { ProjectEvent.PROJECT_EVENT.OCCURRED_AT }, false);
    public static final Index IX_PROJECT_OWNER_CREATED = Internal.createIndex(DSL.name("ix_project_owner_created"), Project.PROJECT, new OrderField[] { Project.PROJECT.OWNER_ID, Project.PROJECT.CREATED_AT.desc(), Project.PROJECT.ID.desc() }, false);
    public static final Index IX_PROVIDER_ATTEMPT_TASK = Internal.createIndex(DSL.name("ix_provider_attempt_task"), ProviderAttempt.PROVIDER_ATTEMPT, new OrderField[] { ProviderAttempt.PROVIDER_ATTEMPT.TASK_ID, ProviderAttempt.PROVIDER_ATTEMPT.CREATED_AT }, false);
    public static final Index IX_SKILL_INSTALL_CLAIM = Internal.createIndex(DSL.name("ix_skill_install_claim"), SkillInstallOperation.SKILL_INSTALL_OPERATION, new OrderField[] { SkillInstallOperation.SKILL_INSTALL_OPERATION.STATUS, SkillInstallOperation.SKILL_INSTALL_OPERATION.LEASE_UNTIL, SkillInstallOperation.SKILL_INSTALL_OPERATION.CREATED_AT }, false);
    public static final Index IX_SKILL_PUBLISH_CLAIM = Internal.createIndex(DSL.name("ix_skill_publish_claim"), SkillPublishOperation.SKILL_PUBLISH_OPERATION, new OrderField[] { SkillPublishOperation.SKILL_PUBLISH_OPERATION.STATUS, SkillPublishOperation.SKILL_PUBLISH_OPERATION.LEASE_UNTIL, SkillPublishOperation.SKILL_PUBLISH_OPERATION.CREATED_AT }, false);
    public static final Index IX_TASK_ARTIFACT_TARGET_CANVAS_ITEM = Internal.createIndex(DSL.name("ix_task_artifact_target_canvas_item"), TaskArtifactTarget.TASK_ARTIFACT_TARGET, new OrderField[] { TaskArtifactTarget.TASK_ARTIFACT_TARGET.PROJECT_ID, TaskArtifactTarget.TASK_ARTIFACT_TARGET.CANVAS_ITEM_ID }, false);
    public static final Index IX_TASK_CLAIM_READY = Internal.createIndex(DSL.name("ix_task_claim_ready"), Task.TASK, new OrderField[] { Task.TASK.NEXT_ACTION_AT, Task.TASK.CREATED_AT, Task.TASK.ID }, false);
    public static final Index IX_TASK_DEPENDENCY_PREDECESSOR = Internal.createIndex(DSL.name("ix_task_dependency_predecessor"), TaskDependency.TASK_DEPENDENCY, new OrderField[] { TaskDependency.TASK_DEPENDENCY.PROJECT_ID, TaskDependency.TASK_DEPENDENCY.DEPENDS_ON_TASK_ID }, false);
    public static final Index IX_TASK_DIRECT_PROJECT = Internal.createIndex(DSL.name("ix_task_direct_project"), Task.TASK, new OrderField[] { Task.TASK.PROJECT_ID, Task.TASK.STATUS, Task.TASK.CREATED_AT }, false);
    public static final Index IX_TASK_OBSERVABLE_STATES = Internal.createIndex(DSL.name("ix_task_observable_states"), Task.TASK, new OrderField[] { Task.TASK.STATUS }, false);
    public static final Index IX_TASK_RECLAIM_RUNNING = Internal.createIndex(DSL.name("ix_task_reclaim_running"), Task.TASK, new OrderField[] { Task.TASK.LEASE_UNTIL, Task.TASK.CREATED_AT, Task.TASK.ID }, false);
    public static final Index IX_TASK_RUN = Internal.createIndex(DSL.name("ix_task_run"), Task.TASK, new OrderField[] { Task.TASK.PROJECT_ID, Task.TASK.RUN_ID, Task.TASK.CREATED_AT, Task.TASK.ID }, false);
    public static final Index IX_TASK_SUBMITTING_LEASE = Internal.createIndex(DSL.name("ix_task_submitting_lease"), Task.TASK, new OrderField[] { Task.TASK.LEASE_UNTIL, Task.TASK.ID }, false);
    public static final Index IX_TOOL_EXECUTION_RUN = Internal.createIndex(DSL.name("ix_tool_execution_run"), ToolExecution.TOOL_EXECUTION, new OrderField[] { ToolExecution.TOOL_EXECUTION.PROJECT_ID, ToolExecution.TOOL_EXECUTION.RUN_ID, ToolExecution.TOOL_EXECUTION.STATUS }, false);
    public static final Index IX_USAGE_LEDGER_PROJECT_CREATED = Internal.createIndex(DSL.name("ix_usage_ledger_project_created"), UsageLedger.USAGE_LEDGER, new OrderField[] { UsageLedger.USAGE_LEDGER.PROJECT_ID, UsageLedger.USAGE_LEDGER.CREATED_AT.desc(), UsageLedger.USAGE_LEDGER.ID.desc() }, false);
    public static final Index LIBRARY_CLEANUP_DUE_IDX = Internal.createIndex(DSL.name("library_cleanup_due_idx"), LibraryCleanup.LIBRARY_CLEANUP, new OrderField[] { LibraryCleanup.LIBRARY_CLEANUP.NEXT_ATTEMPT_AT, LibraryCleanup.LIBRARY_CLEANUP.CREATED_AT, LibraryCleanup.LIBRARY_CLEANUP.ID }, false);
    public static final Index SPRING_SESSION_IX1 = Internal.createIndex(DSL.name("spring_session_ix1"), SpringSession.SPRING_SESSION, new OrderField[] { SpringSession.SPRING_SESSION.SESSION_ID }, true);
    public static final Index SPRING_SESSION_IX2 = Internal.createIndex(DSL.name("spring_session_ix2"), SpringSession.SPRING_SESSION, new OrderField[] { SpringSession.SPRING_SESSION.EXPIRY_TIME }, false);
    public static final Index SPRING_SESSION_IX3 = Internal.createIndex(DSL.name("spring_session_ix3"), SpringSession.SPRING_SESSION, new OrderField[] { SpringSession.SPRING_SESSION.PRINCIPAL_NAME }, false);
    public static final Index UQ_APP_USER_SINGLE_ACTIVE_ADMIN = Internal.createIndex(DSL.name("uq_app_user_single_active_admin"), AppUser.APP_USER, new OrderField[] { AppUser.APP_USER.STATUS }, true);
    public static final Index UQ_CANVAS_ITEM_MEDIA_INPUT_CONNECTION_SOURCE = Internal.createIndex(DSL.name("uq_canvas_item_media_input_connection_source"), CanvasItemMediaInputSource.CANVAS_ITEM_MEDIA_INPUT_SOURCE, new OrderField[] { CanvasItemMediaInputSource.CANVAS_ITEM_MEDIA_INPUT_SOURCE.CONNECTION_ID }, true);
    public static final Index UQ_CANVAS_ITEM_MEDIA_INPUT_END_FRAME = Internal.createIndex(DSL.name("uq_canvas_item_media_input_end_frame"), CanvasItemMediaInput.CANVAS_ITEM_MEDIA_INPUT, new OrderField[] { CanvasItemMediaInput.CANVAS_ITEM_MEDIA_INPUT.PROJECT_ID, CanvasItemMediaInput.CANVAS_ITEM_MEDIA_INPUT.CANVAS_ITEM_ID, CanvasItemMediaInput.CANVAS_ITEM_MEDIA_INPUT.INPUT_ROLE }, true);
    public static final Index UQ_CANVAS_ITEM_MEDIA_INPUT_MANUAL_SOURCE = Internal.createIndex(DSL.name("uq_canvas_item_media_input_manual_source"), CanvasItemMediaInputSource.CANVAS_ITEM_MEDIA_INPUT_SOURCE, new OrderField[] { CanvasItemMediaInputSource.CANVAS_ITEM_MEDIA_INPUT_SOURCE.PROJECT_ID, CanvasItemMediaInputSource.CANVAS_ITEM_MEDIA_INPUT_SOURCE.CANVAS_ITEM_ID, CanvasItemMediaInputSource.CANVAS_ITEM_MEDIA_INPUT_SOURCE.ARTIFACT_VERSION_ID }, true);
    public static final Index UQ_CANVAS_ITEM_MEDIA_INPUT_START_FRAME = Internal.createIndex(DSL.name("uq_canvas_item_media_input_start_frame"), CanvasItemMediaInput.CANVAS_ITEM_MEDIA_INPUT, new OrderField[] { CanvasItemMediaInput.CANVAS_ITEM_MEDIA_INPUT.PROJECT_ID, CanvasItemMediaInput.CANVAS_ITEM_MEDIA_INPUT.CANVAS_ITEM_ID, CanvasItemMediaInput.CANVAS_ITEM_MEDIA_INPUT.INPUT_ROLE }, true);
    public static final Index UQ_TASK_DIRECT_KEY = Internal.createIndex(DSL.name("uq_task_direct_key"), Task.TASK, new OrderField[] { Task.TASK.PROJECT_ID, Task.TASK.STEP_KEY }, true);
    public static final Index UQ_TASK_RUN_STEP_ATTEMPT = Internal.createIndex(DSL.name("uq_task_run_step_attempt"), Task.TASK, new OrderField[] { Task.TASK.RUN_ID, Task.TASK.STEP_KEY, Task.TASK.ATTEMPT_NO }, true);
    public static final Index UX_LLM_PROVIDER_CONFIG_ACTIVE = Internal.createIndex(DSL.name("ux_llm_provider_config_active"), LlmProviderConfig.LLM_PROVIDER_CONFIG, new OrderField[] { LlmProviderConfig.LLM_PROVIDER_CONFIG.ACTIVE }, true);
}
